# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chat_req_pb2 as chat__req__pb2
import chat_response_pb2 as chat__response__pb2
import embedding_req_pb2 as embedding__req__pb2
import embedding_response_pb2 as embedding__response__pb2
import generate_req_pb2 as generate__req__pb2
import generate_response_pb2 as generate__response__pb2
import image_generation_request_pb2 as image__generation__request__pb2
import image_generation_response_pb2 as image__generation__response__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatStream = channel.unary_stream(
                '/proto.InferenceService/ChatStream',
                request_serializer=chat__req__pb2.ChatReq.SerializeToString,
                response_deserializer=chat__response__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.GenerateStream = channel.unary_stream(
                '/proto.InferenceService/GenerateStream',
                request_serializer=generate__req__pb2.GenerateReq.SerializeToString,
                response_deserializer=generate__response__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.GetEmbedding = channel.unary_unary(
                '/proto.InferenceService/GetEmbedding',
                request_serializer=embedding__req__pb2.EmbeddingReq.SerializeToString,
                response_deserializer=embedding__response__pb2.EmbeddingResponse.FromString,
                _registered_method=True)
        self.GenerateImage = channel.unary_unary(
                '/proto.InferenceService/GenerateImage',
                request_serializer=image__generation__request__pb2.ImageGenerateRequest.SerializeToString,
                response_deserializer=image__generation__response__pb2.ImageGenerateResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ChatStream(self, request, context):
        """Chat service with streaming response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateStream(self, request, context):
        """Generate text (non-chat) with streaming response
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbedding(self, request, context):
        """Get embeddings from text
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateImage(self, request, context):
        """Image generation with non-streaming response (returns image ID for status check)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ChatStream,
                    request_deserializer=chat__req__pb2.ChatReq.FromString,
                    response_serializer=chat__response__pb2.ChatResponse.SerializeToString,
            ),
            'GenerateStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateStream,
                    request_deserializer=generate__req__pb2.GenerateReq.FromString,
                    response_serializer=generate__response__pb2.GenerateResponse.SerializeToString,
            ),
            'GetEmbedding': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbedding,
                    request_deserializer=embedding__req__pb2.EmbeddingReq.FromString,
                    response_serializer=embedding__response__pb2.EmbeddingResponse.SerializeToString,
            ),
            'GenerateImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateImage,
                    request_deserializer=image__generation__request__pb2.ImageGenerateRequest.FromString,
                    response_serializer=image__generation__response__pb2.ImageGenerateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ChatStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.InferenceService/ChatStream',
            chat__req__pb2.ChatReq.SerializeToString,
            chat__response__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/proto.InferenceService/GenerateStream',
            generate__req__pb2.GenerateReq.SerializeToString,
            generate__response__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmbedding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.InferenceService/GetEmbedding',
            embedding__req__pb2.EmbeddingReq.SerializeToString,
            embedding__response__pb2.EmbeddingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.InferenceService/GenerateImage',
            image__generation__request__pb2.ImageGenerateRequest.SerializeToString,
            image__generation__response__pb2.ImageGenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
