// GENERATED CODE - DO NOT EDIT
// Generated by schema2code proto generator

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: chat_response.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ChatResponse represents a response from the Ollama chat API
type ChatResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Done               bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	Message            *ChatMessage           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Model              string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Context            []float64              `protobuf:"fixed64,5,rep,packed,name=context,proto3" json:"context,omitempty"`
	DoneReason         string                 `protobuf:"bytes,6,opt,name=done_reason,json=doneReason,proto3" json:"done_reason,omitempty"`
	TotalDuration      float64                `protobuf:"fixed64,7,opt,name=total_duration,json=totalDuration,proto3" json:"total_duration,omitempty"`
	LoadDuration       float64                `protobuf:"fixed64,8,opt,name=load_duration,json=loadDuration,proto3" json:"load_duration,omitempty"`
	PromptEvalCount    float64                `protobuf:"fixed64,9,opt,name=prompt_eval_count,json=promptEvalCount,proto3" json:"prompt_eval_count,omitempty"`
	PromptEvalDuration float64                `protobuf:"fixed64,10,opt,name=prompt_eval_duration,json=promptEvalDuration,proto3" json:"prompt_eval_duration,omitempty"`
	EvalCount          float64                `protobuf:"fixed64,11,opt,name=eval_count,json=evalCount,proto3" json:"eval_count,omitempty"`
	EvalDuration       float64                `protobuf:"fixed64,12,opt,name=eval_duration,json=evalDuration,proto3" json:"eval_duration,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_chat_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chat_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_chat_response_proto_rawDescGZIP(), []int{0}
}

func (x *ChatResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChatResponse) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ChatResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ChatResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatResponse) GetContext() []float64 {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ChatResponse) GetDoneReason() string {
	if x != nil {
		return x.DoneReason
	}
	return ""
}

func (x *ChatResponse) GetTotalDuration() float64 {
	if x != nil {
		return x.TotalDuration
	}
	return 0
}

func (x *ChatResponse) GetLoadDuration() float64 {
	if x != nil {
		return x.LoadDuration
	}
	return 0
}

func (x *ChatResponse) GetPromptEvalCount() float64 {
	if x != nil {
		return x.PromptEvalCount
	}
	return 0
}

func (x *ChatResponse) GetPromptEvalDuration() float64 {
	if x != nil {
		return x.PromptEvalDuration
	}
	return 0
}

func (x *ChatResponse) GetEvalCount() float64 {
	if x != nil {
		return x.EvalCount
	}
	return 0
}

func (x *ChatResponse) GetEvalDuration() float64 {
	if x != nil {
		return x.EvalDuration
	}
	return 0
}

var File_chat_response_proto protoreflect.FileDescriptor

const file_chat_response_proto_rawDesc = "" +
	"\n" +
	"\x13chat_response.proto\x12\x05proto\x1a\x12chat_message.proto\"\xae\x03\n" +
	"\fChatResponse\x12\x12\n" +
	"\x04done\x18\x01 \x01(\bR\x04done\x12,\n" +
	"\amessage\x18\x02 \x01(\v2\x12.proto.ChatMessageR\amessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12\x18\n" +
	"\acontext\x18\x05 \x03(\x01R\acontext\x12\x1f\n" +
	"\vdone_reason\x18\x06 \x01(\tR\n" +
	"doneReason\x12%\n" +
	"\x0etotal_duration\x18\a \x01(\x01R\rtotalDuration\x12#\n" +
	"\rload_duration\x18\b \x01(\x01R\floadDuration\x12*\n" +
	"\x11prompt_eval_count\x18\t \x01(\x01R\x0fpromptEvalCount\x120\n" +
	"\x14prompt_eval_duration\x18\n" +
	" \x01(\x01R\x12promptEvalDuration\x12\x1d\n" +
	"\n" +
	"eval_count\x18\v \x01(\x01R\tevalCount\x12#\n" +
	"\reval_duration\x18\f \x01(\x01R\fevalDurationB\x0fZ\rmaistro/protob\x06proto3"

var (
	file_chat_response_proto_rawDescOnce sync.Once
	file_chat_response_proto_rawDescData []byte
)

func file_chat_response_proto_rawDescGZIP() []byte {
	file_chat_response_proto_rawDescOnce.Do(func() {
		file_chat_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chat_response_proto_rawDesc), len(file_chat_response_proto_rawDesc)))
	})
	return file_chat_response_proto_rawDescData
}

var file_chat_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_chat_response_proto_goTypes = []any{
	(*ChatResponse)(nil), // 0: proto.ChatResponse
	(*ChatMessage)(nil),  // 1: proto.ChatMessage
}
var file_chat_response_proto_depIdxs = []int32{
	1, // 0: proto.ChatResponse.message:type_name -> proto.ChatMessage
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chat_response_proto_init() }
func file_chat_response_proto_init() {
	if File_chat_response_proto != nil {
		return
	}
	file_chat_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chat_response_proto_rawDesc), len(file_chat_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chat_response_proto_goTypes,
		DependencyIndexes: file_chat_response_proto_depIdxs,
		MessageInfos:      file_chat_response_proto_msgTypes,
	}.Build()
	File_chat_response_proto = out.File
	file_chat_response_proto_goTypes = nil
	file_chat_response_proto_depIdxs = nil
}
