// GENERATED CODE - DO NOT EDIT
// Generated by schema2code proto generator

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: embedding_req.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EmbeddingReq represents a request to the Ollama embeddings API
type EmbeddingReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model name
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// Text to generate embeddings for
	Input []string `protobuf:"bytes,2,rep,name=input,proto3" json:"input,omitempty"`
	// Whether to truncate the input to the model's maximum length
	Truncate bool `protobuf:"varint,3,opt,name=truncate,proto3" json:"truncate,omitempty"`
	// Additional model parameters listed in the documentation for the Modelfile such as temperature
	Options *EmbeddingReq_Options `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	// Controls how long the model will stay loaded into memory
	KeepAlive     int32 `protobuf:"varint,5,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingReq) Reset() {
	*x = EmbeddingReq{}
	mi := &file_embedding_req_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingReq) ProtoMessage() {}

func (x *EmbeddingReq) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_req_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingReq.ProtoReflect.Descriptor instead.
func (*EmbeddingReq) Descriptor() ([]byte, []int) {
	return file_embedding_req_proto_rawDescGZIP(), []int{0}
}

func (x *EmbeddingReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *EmbeddingReq) GetInput() []string {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *EmbeddingReq) GetTruncate() bool {
	if x != nil {
		return x.Truncate
	}
	return false
}

func (x *EmbeddingReq) GetOptions() *EmbeddingReq_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *EmbeddingReq) GetKeepAlive() int32 {
	if x != nil {
		return x.KeepAlive
	}
	return 0
}

// Additional model parameters listed in the documentation for the Modelfile such as temperature
type EmbeddingReq_Options struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingReq_Options) Reset() {
	*x = EmbeddingReq_Options{}
	mi := &file_embedding_req_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingReq_Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingReq_Options) ProtoMessage() {}

func (x *EmbeddingReq_Options) ProtoReflect() protoreflect.Message {
	mi := &file_embedding_req_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingReq_Options.ProtoReflect.Descriptor instead.
func (*EmbeddingReq_Options) Descriptor() ([]byte, []int) {
	return file_embedding_req_proto_rawDescGZIP(), []int{0, 0}
}

var File_embedding_req_proto protoreflect.FileDescriptor

const file_embedding_req_proto_rawDesc = "" +
	"\n" +
	"\x13embedding_req.proto\x12\x05proto\"\xbd\x01\n" +
	"\fEmbeddingReq\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x14\n" +
	"\x05input\x18\x02 \x03(\tR\x05input\x12\x1a\n" +
	"\btruncate\x18\x03 \x01(\bR\btruncate\x125\n" +
	"\aoptions\x18\x04 \x01(\v2\x1b.proto.EmbeddingReq.OptionsR\aoptions\x12\x1d\n" +
	"\n" +
	"keep_alive\x18\x05 \x01(\x05R\tkeepAlive\x1a\x0f\n" +
	"\aOptionsJ\x04\b\x01\x10\x02B\x0fZ\rmaistro/protob\x06proto3"

var (
	file_embedding_req_proto_rawDescOnce sync.Once
	file_embedding_req_proto_rawDescData []byte
)

func file_embedding_req_proto_rawDescGZIP() []byte {
	file_embedding_req_proto_rawDescOnce.Do(func() {
		file_embedding_req_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_embedding_req_proto_rawDesc), len(file_embedding_req_proto_rawDesc)))
	})
	return file_embedding_req_proto_rawDescData
}

var file_embedding_req_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_embedding_req_proto_goTypes = []any{
	(*EmbeddingReq)(nil),         // 0: proto.EmbeddingReq
	(*EmbeddingReq_Options)(nil), // 1: proto.EmbeddingReq.Options
}
var file_embedding_req_proto_depIdxs = []int32{
	1, // 0: proto.EmbeddingReq.options:type_name -> proto.EmbeddingReq.Options
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_embedding_req_proto_init() }
func file_embedding_req_proto_init() {
	if File_embedding_req_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_embedding_req_proto_rawDesc), len(file_embedding_req_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_embedding_req_proto_goTypes,
		DependencyIndexes: file_embedding_req_proto_depIdxs,
		MessageInfos:      file_embedding_req_proto_msgTypes,
	}.Build()
	File_embedding_req_proto = out.File
	file_embedding_req_proto_goTypes = nil
	file_embedding_req_proto_depIdxs = nil
}
