// GENERATED CODE - DO NOT EDIT
// Generated by schema2code proto generator

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: generate_req.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerateReq represents a request to the Ollama embeddings API
type GenerateReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Model name
	Model string `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	// Prompt to send to the model
	Prompt string `protobuf:"bytes,2,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Suffix to append to the prompt
	Suffix string `protobuf:"bytes,3,opt,name=suffix,proto3" json:"suffix,omitempty"`
	// Images to include with the prompt
	Images []string `protobuf:"bytes,4,rep,name=images,proto3" json:"images,omitempty"`
	// The format to return a response in. Format can be json or a JSON schema
	Format *GenerateReq_Format `protobuf:"bytes,5,opt,name=format,proto3" json:"format,omitempty"`
	// Additional model parameters listed in the documentation for the Modelfile such as temperature
	Options *ModelParameters `protobuf:"bytes,6,opt,name=options,proto3" json:"options,omitempty"`
	// System message to (overrides what is defined in the Modelfile)
	System string `protobuf:"bytes,7,opt,name=system,proto3" json:"system,omitempty"`
	// The prompt template to use (overrides what is defined in the Modelfile)
	Template string `protobuf:"bytes,8,opt,name=template,proto3" json:"template,omitempty"`
	// If false the response will be returned as a single response object
	Stream bool `protobuf:"varint,9,opt,name=stream,proto3" json:"stream,omitempty"`
	// If true no formatting will be applied to the prompt
	Raw bool `protobuf:"varint,10,opt,name=raw,proto3" json:"raw,omitempty"`
	// Controls how long the model will stay loaded into memory
	KeepAlive int32 `protobuf:"varint,11,opt,name=keep_alive,json=keepAlive,proto3" json:"keep_alive,omitempty"`
	// the context parameter returned from a previous request
	Context string `protobuf:"bytes,12,opt,name=context,proto3" json:"context,omitempty"`
	// If true, the model will think before responding, useful for complex queries
	Think         bool `protobuf:"varint,13,opt,name=think,proto3" json:"think,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReq) Reset() {
	*x = GenerateReq{}
	mi := &file_generate_req_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReq) ProtoMessage() {}

func (x *GenerateReq) ProtoReflect() protoreflect.Message {
	mi := &file_generate_req_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReq.ProtoReflect.Descriptor instead.
func (*GenerateReq) Descriptor() ([]byte, []int) {
	return file_generate_req_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateReq) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *GenerateReq) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateReq) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *GenerateReq) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *GenerateReq) GetFormat() *GenerateReq_Format {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *GenerateReq) GetOptions() *ModelParameters {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *GenerateReq) GetSystem() string {
	if x != nil {
		return x.System
	}
	return ""
}

func (x *GenerateReq) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *GenerateReq) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *GenerateReq) GetRaw() bool {
	if x != nil {
		return x.Raw
	}
	return false
}

func (x *GenerateReq) GetKeepAlive() int32 {
	if x != nil {
		return x.KeepAlive
	}
	return 0
}

func (x *GenerateReq) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *GenerateReq) GetThink() bool {
	if x != nil {
		return x.Think
	}
	return false
}

// The format to return a response in. Format can be json or a JSON schema
type GenerateReq_Format struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReq_Format) Reset() {
	*x = GenerateReq_Format{}
	mi := &file_generate_req_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReq_Format) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReq_Format) ProtoMessage() {}

func (x *GenerateReq_Format) ProtoReflect() protoreflect.Message {
	mi := &file_generate_req_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReq_Format.ProtoReflect.Descriptor instead.
func (*GenerateReq_Format) Descriptor() ([]byte, []int) {
	return file_generate_req_proto_rawDescGZIP(), []int{0, 0}
}

var File_generate_req_proto protoreflect.FileDescriptor

const file_generate_req_proto_rawDesc = "" +
	"\n" +
	"\x12generate_req.proto\x12\x05proto\x1a\x16model_parameters.proto\"\x8d\x03\n" +
	"\vGenerateReq\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x12\x16\n" +
	"\x06prompt\x18\x02 \x01(\tR\x06prompt\x12\x16\n" +
	"\x06suffix\x18\x03 \x01(\tR\x06suffix\x12\x16\n" +
	"\x06images\x18\x04 \x03(\tR\x06images\x121\n" +
	"\x06format\x18\x05 \x01(\v2\x19.proto.GenerateReq.FormatR\x06format\x120\n" +
	"\aoptions\x18\x06 \x01(\v2\x16.proto.ModelParametersR\aoptions\x12\x16\n" +
	"\x06system\x18\a \x01(\tR\x06system\x12\x1a\n" +
	"\btemplate\x18\b \x01(\tR\btemplate\x12\x16\n" +
	"\x06stream\x18\t \x01(\bR\x06stream\x12\x10\n" +
	"\x03raw\x18\n" +
	" \x01(\bR\x03raw\x12\x1d\n" +
	"\n" +
	"keep_alive\x18\v \x01(\x05R\tkeepAlive\x12\x18\n" +
	"\acontext\x18\f \x01(\tR\acontext\x12\x14\n" +
	"\x05think\x18\r \x01(\bR\x05think\x1a\x0e\n" +
	"\x06FormatJ\x04\b\x01\x10\x02B\x0fZ\rmaistro/protob\x06proto3"

var (
	file_generate_req_proto_rawDescOnce sync.Once
	file_generate_req_proto_rawDescData []byte
)

func file_generate_req_proto_rawDescGZIP() []byte {
	file_generate_req_proto_rawDescOnce.Do(func() {
		file_generate_req_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_generate_req_proto_rawDesc), len(file_generate_req_proto_rawDesc)))
	})
	return file_generate_req_proto_rawDescData
}

var file_generate_req_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_generate_req_proto_goTypes = []any{
	(*GenerateReq)(nil),        // 0: proto.GenerateReq
	(*GenerateReq_Format)(nil), // 1: proto.GenerateReq.Format
	(*ModelParameters)(nil),    // 2: proto.ModelParameters
}
var file_generate_req_proto_depIdxs = []int32{
	1, // 0: proto.GenerateReq.format:type_name -> proto.GenerateReq.Format
	2, // 1: proto.GenerateReq.options:type_name -> proto.ModelParameters
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_generate_req_proto_init() }
func file_generate_req_proto_init() {
	if File_generate_req_proto != nil {
		return
	}
	file_model_parameters_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_generate_req_proto_rawDesc), len(file_generate_req_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_generate_req_proto_goTypes,
		DependencyIndexes: file_generate_req_proto_depIdxs,
		MessageInfos:      file_generate_req_proto_msgTypes,
	}.Build()
	File_generate_req_proto = out.File
	file_generate_req_proto_goTypes = nil
	file_generate_req_proto_depIdxs = nil
}
