// GENERATED CODE - DO NOT EDIT
// Generated by schema2code proto generator

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: image_generation_response.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Response from generating an image
type ImageGenerateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base64-encoded image
	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// URL to download the image
	Download      string `protobuf:"bytes,2,opt,name=download,proto3" json:"download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageGenerateResponse) Reset() {
	*x = ImageGenerateResponse{}
	mi := &file_image_generation_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageGenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageGenerateResponse) ProtoMessage() {}

func (x *ImageGenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_generation_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageGenerateResponse.ProtoReflect.Descriptor instead.
func (*ImageGenerateResponse) Descriptor() ([]byte, []int) {
	return file_image_generation_response_proto_rawDescGZIP(), []int{0}
}

func (x *ImageGenerateResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ImageGenerateResponse) GetDownload() string {
	if x != nil {
		return x.Download
	}
	return ""
}

var File_image_generation_response_proto protoreflect.FileDescriptor

const file_image_generation_response_proto_rawDesc = "" +
	"\n" +
	"\x1fimage_generation_response.proto\x12\x05proto\"I\n" +
	"\x15ImageGenerateResponse\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12\x1a\n" +
	"\bdownload\x18\x02 \x01(\tR\bdownloadB\x0fZ\rmaistro/protob\x06proto3"

var (
	file_image_generation_response_proto_rawDescOnce sync.Once
	file_image_generation_response_proto_rawDescData []byte
)

func file_image_generation_response_proto_rawDescGZIP() []byte {
	file_image_generation_response_proto_rawDescOnce.Do(func() {
		file_image_generation_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_image_generation_response_proto_rawDesc), len(file_image_generation_response_proto_rawDesc)))
	})
	return file_image_generation_response_proto_rawDescData
}

var file_image_generation_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_image_generation_response_proto_goTypes = []any{
	(*ImageGenerateResponse)(nil), // 0: proto.ImageGenerateResponse
}
var file_image_generation_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_image_generation_response_proto_init() }
func file_image_generation_response_proto_init() {
	if File_image_generation_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_image_generation_response_proto_rawDesc), len(file_image_generation_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_image_generation_response_proto_goTypes,
		DependencyIndexes: file_image_generation_response_proto_depIdxs,
		MessageInfos:      file_image_generation_response_proto_msgTypes,
	}.Build()
	File_image_generation_response_proto = out.File
	file_image_generation_response_proto_goTypes = nil
	file_image_generation_response_proto_depIdxs = nil
}
