// GENERATED CODE - DO NOT EDIT
// Generated by schema2code proto generator

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: image_generation_request.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for generating an image
type ImageGenerateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The prompt for image generation
	Prompt string `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	// Width of the generated image
	Width int32 `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	// Height of the generated image
	Height int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// Number of inference steps
	InferenceSteps int32 `protobuf:"varint,4,opt,name=inference_steps,json=inferenceSteps,proto3" json:"inference_steps,omitempty"`
	// Guidance scale for image generation
	GuidanceScale float32 `protobuf:"fixed32,5,opt,name=guidance_scale,json=guidanceScale,proto3" json:"guidance_scale,omitempty"`
	// Whether to use low memory mode
	LowMemoryMode bool `protobuf:"varint,6,opt,name=low_memory_mode,json=lowMemoryMode,proto3" json:"low_memory_mode,omitempty"`
	// Negative prompt for image generation
	NegativePrompt string `protobuf:"bytes,7,opt,name=negative_prompt,json=negativePrompt,proto3" json:"negative_prompt,omitempty"`
	// Model to use for image generation
	Model string `protobuf:"bytes,8,opt,name=model,proto3" json:"model,omitempty"`
	// List of LoRA models to apply to the image generation
	Loras []string `protobuf:"bytes,9,rep,name=loras,proto3" json:"loras,omitempty"`
	// ID of the image to use as a base for image generation (for img2img)
	ImageId int32 `protobuf:"varint,10,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	// URL of the image to use as a base for image generation (for img2img)
	Url string `protobuf:"bytes,11,opt,name=url,proto3" json:"url,omitempty"`
	// Name of the file to save the generated image as
	Filename      string `protobuf:"bytes,12,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageGenerateRequest) Reset() {
	*x = ImageGenerateRequest{}
	mi := &file_image_generation_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageGenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageGenerateRequest) ProtoMessage() {}

func (x *ImageGenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_generation_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageGenerateRequest.ProtoReflect.Descriptor instead.
func (*ImageGenerateRequest) Descriptor() ([]byte, []int) {
	return file_image_generation_request_proto_rawDescGZIP(), []int{0}
}

func (x *ImageGenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *ImageGenerateRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageGenerateRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageGenerateRequest) GetInferenceSteps() int32 {
	if x != nil {
		return x.InferenceSteps
	}
	return 0
}

func (x *ImageGenerateRequest) GetGuidanceScale() float32 {
	if x != nil {
		return x.GuidanceScale
	}
	return 0
}

func (x *ImageGenerateRequest) GetLowMemoryMode() bool {
	if x != nil {
		return x.LowMemoryMode
	}
	return false
}

func (x *ImageGenerateRequest) GetNegativePrompt() string {
	if x != nil {
		return x.NegativePrompt
	}
	return ""
}

func (x *ImageGenerateRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ImageGenerateRequest) GetLoras() []string {
	if x != nil {
		return x.Loras
	}
	return nil
}

func (x *ImageGenerateRequest) GetImageId() int32 {
	if x != nil {
		return x.ImageId
	}
	return 0
}

func (x *ImageGenerateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageGenerateRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

var File_image_generation_request_proto protoreflect.FileDescriptor

const file_image_generation_request_proto_rawDesc = "" +
	"\n" +
	"\x1eimage_generation_request.proto\x12\x05proto\"\xf2\x02\n" +
	"\x14ImageGenerateRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height\x12'\n" +
	"\x0finference_steps\x18\x04 \x01(\x05R\x0einferenceSteps\x12%\n" +
	"\x0eguidance_scale\x18\x05 \x01(\x02R\rguidanceScale\x12&\n" +
	"\x0flow_memory_mode\x18\x06 \x01(\bR\rlowMemoryMode\x12'\n" +
	"\x0fnegative_prompt\x18\a \x01(\tR\x0enegativePrompt\x12\x14\n" +
	"\x05model\x18\b \x01(\tR\x05model\x12\x14\n" +
	"\x05loras\x18\t \x03(\tR\x05loras\x12\x19\n" +
	"\bimage_id\x18\n" +
	" \x01(\x05R\aimageId\x12\x10\n" +
	"\x03url\x18\v \x01(\tR\x03url\x12\x1a\n" +
	"\bfilename\x18\f \x01(\tR\bfilenameB\x0fZ\rmaistro/protob\x06proto3"

var (
	file_image_generation_request_proto_rawDescOnce sync.Once
	file_image_generation_request_proto_rawDescData []byte
)

func file_image_generation_request_proto_rawDescGZIP() []byte {
	file_image_generation_request_proto_rawDescOnce.Do(func() {
		file_image_generation_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_image_generation_request_proto_rawDesc), len(file_image_generation_request_proto_rawDesc)))
	})
	return file_image_generation_request_proto_rawDescData
}

var file_image_generation_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_image_generation_request_proto_goTypes = []any{
	(*ImageGenerateRequest)(nil), // 0: proto.ImageGenerateRequest
}
var file_image_generation_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_image_generation_request_proto_init() }
func file_image_generation_request_proto_init() {
	if File_image_generation_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_image_generation_request_proto_rawDesc), len(file_image_generation_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_image_generation_request_proto_goTypes,
		DependencyIndexes: file_image_generation_request_proto_depIdxs,
		MessageInfos:      file_image_generation_request_proto_msgTypes,
	}.Build()
	File_image_generation_request_proto = out.File
	file_image_generation_request_proto_goTypes = nil
	file_image_generation_request_proto_depIdxs = nil
}
