// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: inference.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\x05proto\x1a\x0echat_req.proto\x1a\x13chat_response.proto\x1a\x12generate_req.proto\x1a\x13embedding_req.proto\x1a\x1eimage_generation_request.proto\x1a\x1fimage_generation_response.proto\x1a\x17generate_response.proto\x1a\x18embedding_response.proto2\x93\x02\n" +
	"\x10InferenceService\x123\n" +
	"\n" +
	"ChatStream\x12\x0e.proto.ChatReq\x1a\x13.proto.ChatResponse0\x01\x12?\n" +
	"\x0eGenerateStream\x12\x12.proto.GenerateReq\x1a\x17.proto.GenerateResponse0\x01\x12=\n" +
	"\fGetEmbedding\x12\x13.proto.EmbeddingReq\x1a\x18.proto.EmbeddingResponse\x12J\n" +
	"\rGenerateImage\x12\x1b.proto.ImageGenerateRequest\x1a\x1c.proto.ImageGenerateResponseB\x0fZ\rmaistro/protob\x06proto3"

var file_inference_proto_goTypes = []any{
	(*ChatReq)(nil),               // 0: proto.ChatReq
	(*GenerateReq)(nil),           // 1: proto.GenerateReq
	(*EmbeddingReq)(nil),          // 2: proto.EmbeddingReq
	(*ImageGenerateRequest)(nil),  // 3: proto.ImageGenerateRequest
	(*ChatResponse)(nil),          // 4: proto.ChatResponse
	(*GenerateResponse)(nil),      // 5: proto.GenerateResponse
	(*EmbeddingResponse)(nil),     // 6: proto.EmbeddingResponse
	(*ImageGenerateResponse)(nil), // 7: proto.ImageGenerateResponse
}
var file_inference_proto_depIdxs = []int32{
	0, // 0: proto.InferenceService.ChatStream:input_type -> proto.ChatReq
	1, // 1: proto.InferenceService.GenerateStream:input_type -> proto.GenerateReq
	2, // 2: proto.InferenceService.GetEmbedding:input_type -> proto.EmbeddingReq
	3, // 3: proto.InferenceService.GenerateImage:input_type -> proto.ImageGenerateRequest
	4, // 4: proto.InferenceService.ChatStream:output_type -> proto.ChatResponse
	5, // 5: proto.InferenceService.GenerateStream:output_type -> proto.GenerateResponse
	6, // 6: proto.InferenceService.GetEmbedding:output_type -> proto.EmbeddingResponse
	7, // 7: proto.InferenceService.GenerateImage:output_type -> proto.ImageGenerateResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	file_chat_req_proto_init()
	file_chat_response_proto_init()
	file_generate_req_proto_init()
	file_embedding_req_proto_init()
	file_image_generation_request_proto_init()
	file_image_generation_response_proto_init()
	file_generate_response_proto_init()
	file_embedding_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
