// GENERATED CODE - DO NOT EDIT
// Generated by schema2code proto generator

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: message_type.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of message
type MessageType int32

const (
	MessageType_MESSAGETYPE_UNSPECIFIED MessageType = 0
	MessageType_CONNECT                 MessageType = 1
	MessageType_CONNECTED               MessageType = 2
	MessageType_PAUSE                   MessageType = 3
	MessageType_PAUSED                  MessageType = 4
	MessageType_RESUME                  MessageType = 5
	MessageType_RESUMED                 MessageType = 6
	MessageType_CANCEL                  MessageType = 7
	MessageType_CANCELLED               MessageType = 8
	MessageType_COMPLETE                MessageType = 9
	MessageType_ERROR                   MessageType = 10
	MessageType_WARNING                 MessageType = 11
	MessageType_INFO                    MessageType = 12
	MessageType_FAILED                  MessageType = 13
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:  "MESSAGETYPE_UNSPECIFIED",
		1:  "CONNECT",
		2:  "CONNECTED",
		3:  "PAUSE",
		4:  "PAUSED",
		5:  "RESUME",
		6:  "RESUMED",
		7:  "CANCEL",
		8:  "CANCELLED",
		9:  "COMPLETE",
		10: "ERROR",
		11: "WARNING",
		12: "INFO",
		13: "FAILED",
	}
	MessageType_value = map[string]int32{
		"MESSAGETYPE_UNSPECIFIED": 0,
		"CONNECT":                 1,
		"CONNECTED":               2,
		"PAUSE":                   3,
		"PAUSED":                  4,
		"RESUME":                  5,
		"RESUMED":                 6,
		"CANCEL":                  7,
		"CANCELLED":               8,
		"COMPLETE":                9,
		"ERROR":                   10,
		"WARNING":                 11,
		"INFO":                    12,
		"FAILED":                  13,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_message_type_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_message_type_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_message_type_proto_rawDescGZIP(), []int{0}
}

var File_message_type_proto protoreflect.FileDescriptor

const file_message_type_proto_rawDesc = "" +
	"\n" +
	"\x12message_type.proto\x12\x05proto*\xcd\x01\n" +
	"\vMessageType\x12\x1b\n" +
	"\x17MESSAGETYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCONNECT\x10\x01\x12\r\n" +
	"\tCONNECTED\x10\x02\x12\t\n" +
	"\x05PAUSE\x10\x03\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x04\x12\n" +
	"\n" +
	"\x06RESUME\x10\x05\x12\v\n" +
	"\aRESUMED\x10\x06\x12\n" +
	"\n" +
	"\x06CANCEL\x10\a\x12\r\n" +
	"\tCANCELLED\x10\b\x12\f\n" +
	"\bCOMPLETE\x10\t\x12\t\n" +
	"\x05ERROR\x10\n" +
	"\x12\v\n" +
	"\aWARNING\x10\v\x12\b\n" +
	"\x04INFO\x10\f\x12\n" +
	"\n" +
	"\x06FAILED\x10\rB\x0fZ\rmaistro/protob\x06proto3"

var (
	file_message_type_proto_rawDescOnce sync.Once
	file_message_type_proto_rawDescData []byte
)

func file_message_type_proto_rawDescGZIP() []byte {
	file_message_type_proto_rawDescOnce.Do(func() {
		file_message_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_message_type_proto_rawDesc), len(file_message_type_proto_rawDesc)))
	})
	return file_message_type_proto_rawDescData
}

var file_message_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_message_type_proto_goTypes = []any{
	(MessageType)(0), // 0: proto.MessageType
}
var file_message_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_message_type_proto_init() }
func file_message_type_proto_init() {
	if File_message_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_message_type_proto_rawDesc), len(file_message_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_message_type_proto_goTypes,
		DependencyIndexes: file_message_type_proto_depIdxs,
		EnumInfos:         file_message_type_proto_enumTypes,
	}.Build()
	File_message_type_proto = out.File
	file_message_type_proto_goTypes = nil
	file_message_type_proto_depIdxs = nil
}
