apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-models
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-models
  namespace: ollama
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/ollama-models
    type: DirectoryOrCreate
  claimRef:
    namespace: ollama
    name: ollama-models
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sd-models
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sd-models
  namespace: ollama
spec:
  storageClassName: ""
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/sd-models
    type: DirectoryOrCreate
  claimRef:
    namespace: ollama
    name: sd-models
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: generated-images
  namespace: ollama
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: generated-images
  namespace: ollama
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/generated-images
    type: DirectoryOrCreate
  claimRef:
    namespace: ollama
    name: generated-images
