// Code generated by schema2code at 2025-06-27 14:37:43. DO NOT EDIT.

package models


// AuthConfig Authentication configuration
type AuthConfig struct {
	JwksURI      string `json:"jwks_uri" yaml:"jwks_uri"` // JWKS URI
	Audience     string `json:"audience" yaml:"audience"` // Audience
	ClientID     string `json:"client_id" yaml:"client_id"` // Client ID
	ClientSecret string `json:"client_secret" yaml:"client_secret"` // Client secret
}
