// Code generated by schema2code at 2025-07-09 14:22:03. DO NOT EDIT.

package models


// ChatResponse ChatResponse represents a response from the Ollama chat API
type ChatResponse struct {
	Done               bool        `json:"done" yaml:"done"`
	Message            *ChatMessage `json:"message" yaml:"message"`
	CreatedAt          string      `json:"createdAt" yaml:"createdAt"`
	Model              string      `json:"model" yaml:"model"`
	Context            []float32   `json:"context" yaml:"context"`
	DoneReason         *string     `json:"done_reason" yaml:"done_reason"`
	TotalDuration      *float32    `json:"total_duration" yaml:"total_duration"`
	LoadDuration       *float32    `json:"load_duration" yaml:"load_duration"`
	PromptEvalCount    *float32    `json:"prompt_eval_count" yaml:"prompt_eval_count"`
	PromptEvalDuration *float32    `json:"prompt_eval_duration" yaml:"prompt_eval_duration"`
	EvalCount          *float32    `json:"eval_count" yaml:"eval_count"`
	EvalDuration       *float32    `json:"eval_duration" yaml:"eval_duration"`
}
