// Code generated by schema2code at 2025-07-18 21:27:30. DO NOT EDIT.

package models



// ChatRequest ChatRequest represents a request from the UI
type ChatRequest struct {
	Content        string              `json:"content" yaml:"content"` // Message to send to the model, each message is a struct with role and content
	ConversationID int                 `json:"conversation_id" yaml:"conversation_id"` // reference to the conversation this message belongs to
	Metadata       *ChatMessageMetadata `json:"metadata" yaml:"metadata"`
}
