// Code generated by schema2code at 2025-06-15 17:08:55. DO NOT EDIT.

package models



// ChatMessage Message in a chat conversation
type ChatMessage struct {
	ID             *int                     `json:"id" yaml:"id"` // Unique identifier for the message
	ConversationID int                      `json:"conversation_id" yaml:"conversation_id"` // Identifier for the conversation this message belongs to
	Role           string                   `json:"role" yaml:"role"` // Role of the message sender (e.g., user, assistant)
	Content        string                   `json:"content" yaml:"content"` // Text content of the message
	Images         []string                 `json:"images" yaml:"images"` // Optional images associated with the message
	ToolCalls      []map[string]interface{} `json:"tool_calls" yaml:"tool_calls"` // Optional tool calls associated with the message
	Thinking       *string                  `json:"thinking" yaml:"thinking"` // Optional thinking process of the model, if applicable
	Metadata       *ChatMessageMetadata     `json:"metadata" yaml:"metadata"`
}
