// Code generated by schema2code at 2025-06-15 17:08:55. DO NOT EDIT.

package models














// Config Application configuration
type Config struct {
	Server            ServerConfig           `json:"server" yaml:"server"`
	Database          DatabaseConfig         `json:"database" yaml:"database"`
	Redis             RedisConfig            `json:"redis" yaml:"redis"`
	Auth              AuthConfig             `json:"auth" yaml:"auth"`
	InferenceServices InferenceServiceConfig `json:"inference_services" yaml:"inference_services"`
	Summarization     SummarizationConfig    `json:"summarization" yaml:"summarization"`
	Memory            MemoryConfig           `json:"memory" yaml:"memory"`
	WebSearch         WebSearchConfig        `json:"web_search" yaml:"web_search"`
	Preferences       PreferencesConfig      `json:"preferences" yaml:"preferences"`
	ModelProfiles     ModelProfileConfig     `json:"model_profiles" yaml:"model_profiles"`
	Refinement        RefinementConfig       `json:"refinement" yaml:"refinement"`
	ImageGeneration   ImageGenerationConfig  `json:"image_generation" yaml:"image_generation"`
	LogLevel          string                 `json:"log_level" yaml:"log_level"` // Log level
}
