// Code generated by schema2code at 2025-06-11 16:13:27. DO NOT EDIT.

package models













// Config Application configuration
type Config struct {
	Server            ServerConfig           `json:"server"`
	Database          DatabaseConfig         `json:"database"`
	Redis             RedisConfig            `json:"redis"`
	Auth              AuthConfig             `json:"auth"`
	PreferenceMap     map[string]interface{} `json:"preference_map"`     // User-specific configuration map
	InferenceServices InferenceServiceConfig `json:"inference_services"`
	Summarization     SummarizationConfig    `json:"summarization"`
	Memory            MemoryConfig           `json:"memory"`
	WebSearch         WebSearchConfig        `json:"web_search"`
	Preferences       PreferencesConfig      `json:"preferences"`
	ModelProfiles     ModelProfileConfig     `json:"model_profiles"`
	Refinement        RefinementConfig       `json:"refinement"`
	LogLevel          string                 `json:"log_level"`          // Log level
}
