// Code generated by schema2code at 2025-06-11 16:13:27. DO NOT EDIT.

package models

import (
	"time"
)

// Conversation Conversation represents a conversation between a user and the LLM
type Conversation struct {
	ID        int       `json:"id"`         // Unique identifier for the conversation
	UserID    string    `json:"user_id"`    // Id of the user who owns the conversation
	Title     string    `json:"title"`      // Title of the conversation
	Model     string    `json:"model"`      // Model used for the conversation
	CreatedAt time.Time `json:"created_at"` // Timestamp of when the conversation was created
	UpdatedAt time.Time `json:"updated_at"` // Timestamp of when the conversation was last updated
}
