// Code generated by schema2code at 2025-08-13 20:54:41. DO NOT EDIT.

package models


// CreateResearchRequest Request to create a new research task
type CreateResearchRequest struct {
	Query          string `json:"query" yaml:"query"` // Original research query
	Model          *string `json:"model" yaml:"model"` // Model to use for the research
	ConversationID *int   `json:"conversation_id" yaml:"conversation_id"` // Id of the conversation to associate with this task
}
