// Code generated by schema2code at 2025-06-11 16:13:28. DO NOT EDIT.

package models


// CreateResearchRequest Request to create a new research task
type CreateResearchRequest struct {
	Query          string `json:"query"`           // Original research query
	Model          *string `json:"model"`           // Model to use for the research
	ConversationID *int   `json:"conversation_id"` // Id of the conversation to associate with this task
}
