// Code generated by schema2code at 2025-06-11 16:13:28. DO NOT EDIT.

package models


// DatabaseConfig Database configuration
type DatabaseConfig struct {
	Host             string `json:"host"`              // Database host
	Port             int    `json:"port"`              // Database port
	User             string `json:"user"`              // Database user
	Password         string `json:"password"`          // Database password
	Dbname           string `json:"dbname"`            // Database name
	Sslmode          string `json:"sslmode"`           // SSL mode
	ConnectionString string `json:"connection_string"` // Connection string
}
