// Code generated by schema2code at 2025-06-11 16:13:28. DO NOT EDIT.

package models


// EmbeddingReq EmbeddingReq represents a request to the Ollama embeddings API
type EmbeddingReq struct {
	Model     string                 `json:"model"`      // Model name
	Input     []string               `json:"input"`      // Text to generate embeddings for
	Truncate  *bool                  `json:"truncate"`   // Whether to truncate the input to the model's maximum length
	Options   map[string]interface{} `json:"options"`    // Additional model parameters listed in the documentation for the Modelfile such as temperature
	KeepAlive *string                `json:"keep_alive"` // Controls how long the model will stay loaded into memory
}
