// Code generated by schema2code at 2025-06-15 17:08:56. DO NOT EDIT.

package models


// ImageGenerationNotificationType Type of notification (e.g., "image_generated")
type ImageGenerationNotificationType string

const (
	ImageGenerationNotificationTypeImageGenerated ImageGenerationNotificationType = "image_generated"
	ImageGenerationNotificationTypeImageGenerationFailed ImageGenerationNotificationType = "image_generation_failed"
)
// ImageGenerationNotification Notification sent to clients when an image is generated.
type ImageGenerationNotification struct {
	Type           ImageGenerationNotificationType `json:"type" yaml:"type"` // Type of notification (e.g., "image_generated")
	ImageID        *string `json:"image_id" yaml:"image_id"` // ID of the generated image
	DownloadURL    *string `json:"download_url" yaml:"download_url"` // URL to download the image
	ThumbnailURL   *string `json:"thumbnail_url" yaml:"thumbnail_url"` // URL to view a thumbnail
	OriginalPrompt *string `json:"original_prompt" yaml:"original_prompt"` // The prompt used to generate the image
	Error          *string `json:"error" yaml:"error"` // Error message if generation failed
	B64Data        *string `json:"b64_data" yaml:"b64_data"` // Base64 encoded image data if applicable
	ConversationID int    `json:"conversation_id" yaml:"conversation_id"` // Identifier for the conversation this notification belongs to
}
