// Code generated by schema2code at 2025-08-13 20:54:42. DO NOT EDIT.

package models


// ImageGenerateResponse Response from generating an image
type ImageGenerateResponse struct {
	Image    string `json:"image" yaml:"image"` // Base64-encoded image
	Download string `json:"download" yaml:"download"` // URL to download the image
}
