// Code generated by schema2code at 2025-06-27 14:37:44. DO NOT EDIT.

package models

import (
	"time"
)

// InferenceQueueMessageType Type of the request, e.g., "chat", "image_generation", etc.
type InferenceQueueMessageType string

const (
	InferenceQueueMessageTypeImage InferenceQueueMessageType = "image"
	InferenceQueueMessageTypeResearch InferenceQueueMessageType = "research"
)
// InferenceQueueMessage Schema for an inference request in the LLM system
type InferenceQueueMessage struct {
	CorrelationID  string      `json:"correlation_id" yaml:"correlation_id"` // Unique identifier for the request and response correlation
	Priority       int         `json:"priority" yaml:"priority"` // Priority of the request
	Timestamp      time.Time   `json:"timestamp" yaml:"timestamp"` // Timestamp of the request
	Payload        interface{} `json:"payload" yaml:"payload"` // Payload containing the inference request details
	Type           InferenceQueueMessageType `json:"type" yaml:"type"` // Type of the request, e.g., "chat", "image_generation", etc.
	MemoryRequired float32     `json:"memory_required" yaml:"memory_required"` // Required memory in bytes for processing the request
}
