// Code generated by schema2code at 2025-07-09 14:22:04. DO NOT EDIT.

package models



// InferenceServiceConfig Inference services configuration
type InferenceServiceConfig struct {
	Ollama          InferenceService `json:"ollama" yaml:"ollama"`
	StableDiffusion InferenceService `json:"stable_diffusion" yaml:"stable_diffusion"`
}
