// Code generated by schema2code at 2025-07-09 14:22:04. DO NOT EDIT.

package models


// InferenceService Inference service configuration
type InferenceService struct {
	BaseURL string `json:"base_url" yaml:"base_url"` // Base URL for the inference service
}
