// Code generated by schema2code at 2025-07-07 14:00:00. DO NOT EDIT.

package models

// InferenceConfig Configuration for inference service
type InferenceConfig struct {
	BaseURL             string  `json:"base_url" yaml:"base_url"`                           // Base URL for inference service HTTP API
	APIKey              string  `json:"api_key" yaml:"api_key"`                             // API key for authentication
	MemoryThreshold     float32 `json:"memory_threshold" yaml:"memory_threshold"`           // Memory threshold for inference (0.0-1.0)
	UseGRPC             bool    `json:"use_grpc" yaml:"use_grpc"`                           // Use gRPC for inference service communication
	GRPCAddress         string  `json:"grpc_address" yaml:"grpc_address"`                   // Address for gRPC server (host:port)
	UseSecureConnection bool    `json:"use_secure_connection" yaml:"use_secure_connection"` // Use TLS for gRPC connections
}
