// Code generated by schema2code at 2025-06-15 17:08:56. DO NOT EDIT.

package models



// InferenceServiceConfig Inference services configuration
type InferenceServiceConfig struct {
	Ollama          InferenceService `json:"ollama" yaml:"ollama"`
	StableDiffusion InferenceService `json:"stable_diffusion" yaml:"stable_diffusion"`
}
