// Code generated by schema2code at 2025-06-27 14:37:45. DO NOT EDIT.

package models


// InferenceService Inference service configuration
type InferenceService struct {
	BaseURL string `json:"base_url" yaml:"base_url"` // Base URL for the inference service
}
