// Code generated by schema2code at 2025-08-05 21:50:57. DO NOT EDIT.

package models


// InternalConfig Configuration for internal services, including API keys and allowed IPs.
type InternalConfig struct {
	APIKey     string `json:"APIKey" yaml:"APIKey"` // API key for internal service auth
	AllowedIPs string `json:"AllowedIPs" yaml:"AllowedIPs"` // Comma-separated list of allowed IPs
}
