// Code generated by schema2code at 2025-08-05 21:50:58. DO NOT EDIT.

package models


// MemoryFragment Content item that is similar to a user's query
type MemoryFragment struct {
	ID      int         `json:"id" yaml:"id"` // Unique identifier for the memory fragment
	Role    MessageRole `json:"role" yaml:"role"` // Role of the message (e.g., 'user', 'assistant')
	Content string      `json:"content" yaml:"content"` // Content of the message
}
