// Code generated by schema2code at 2025-06-11 16:13:30. DO NOT EDIT.

package models


// MemoryConfig Memory retrieval settings
type MemoryConfig struct {
	Enabled                 bool    `json:"enabled"`                   // Whether memory retrieval is enabled
	Limit                   int     `json:"limit"`                     // Retrieval limit
	ProfileID               string  `json:"profile_id"`                // Profile ID
	EnableCrossUser         bool    `json:"enable_cross_user"`         // Enable cross-user retrieval
	EnableCrossConversation bool    `json:"enable_cross_conversation"` // Enable cross-conversation retrieval
	SimilarityThreshold     float32 `json:"similarity_threshold"`      // Similarity threshold
	AlwaysRetrieve          bool    `json:"always_retrieve"`           // Always retrieve
}
