// Code generated by schema2code at 2025-08-05 21:50:58. DO NOT EDIT.

package models


// MessageRole Role of a participant in a chat conversation
type MessageRole string

const (
	MessageRoleUser MessageRole = "user"
	MessageRoleAssistant MessageRole = "assistant"
	MessageRoleSystem MessageRole = "system"
	MessageRoleTool MessageRole = "tool"
	MessageRoleAgent MessageRole = "agent"
	MessageRoleObserver MessageRole = "observer"
)