// Code generated by schema2code at 2025-08-05 21:50:58. DO NOT EDIT.

package models


// MessageContent Content of a message in a chat conversation
type MessageContent struct {
	Type MessageContentType `json:"type" yaml:"type"` // Type of the message content (e.g., text, image, tool call)
	Text *string            `json:"text" yaml:"text"` // Text content of the message, if applicable
	URL  *string            `json:"url" yaml:"url"` // URL of the image or resource, if applicable
}
