// Code generated by schema2code at 2025-06-11 16:13:28. DO NOT EDIT.

package models

import (
	"time"
)

// Message Message represents a single exchange in the conversation
type Message struct {
	Role           string                   `json:"role"`            // Role of the message sender (e.g., user, assistant)
	Content        string                   `json:"content"`         // Text content of the message
	Images         []string                 `json:"images"`          // Optional images associated with the message
	ToolCalls      []map[string]interface{} `json:"tool_calls"`      // Optional tool calls associated with the message
	ID             int                      `json:"id"`              // Unique identifier for the message
	CreatedAt      *time.Time               `json:"createdAt"`       // Timestamp of when the message was created
	ConversationID *int                     `json:"conversation_id"` // Id of the conversation this message belongs to
}
