// Code generated by schema2code at 2025-06-15 17:08:57. DO NOT EDIT.

package models

import (
	"time"
)

// Message Message represents a single exchange in the conversation
type Message struct {
	Role           string                   `json:"role" yaml:"role"` // Role of the message sender (e.g., user, assistant)
	Content        string                   `json:"content" yaml:"content"` // Text content of the message
	Images         []string                 `json:"images" yaml:"images"` // Optional images associated with the message
	ToolCalls      []map[string]interface{} `json:"tool_calls" yaml:"tool_calls"` // Optional tool calls associated with the message
	ID             int                      `json:"id" yaml:"id"` // Unique identifier for the message
	CreatedAt      *time.Time               `json:"createdAt" yaml:"createdAt"` // Timestamp of when the message was created
	ConversationID *int                     `json:"conversation_id" yaml:"conversation_id"` // Id of the conversation this message belongs to
}
