// Code generated by schema2code at 2025-07-01 15:06:46. DO NOT EDIT.

package models


// MessageType Type of message
type MessageType string

const (
	MessageTypeConnect MessageType = "connect"
	MessageTypeConnected MessageType = "connected"
	MessageTypePause MessageType = "pause"
	MessageTypePaused MessageType = "paused"
	MessageTypeResume MessageType = "resume"
	MessageTypeResumed MessageType = "resumed"
	MessageTypeCancel MessageType = "cancel"
	MessageTypeCancelled MessageType = "cancelled"
	MessageTypeComplete MessageType = "complete"
	MessageTypeError MessageType = "error"
	MessageTypeWarning MessageType = "warning"
	MessageTypeInfo MessageType = "info"
	MessageTypeFailed MessageType = "failed"
)