// Code generated by schema2code at 2025-06-15 17:08:57. DO NOT EDIT.

package models

import (
	"github.com/google/uuid"
	"time"
)


// ModelProfile ModelProfile represents a model profile used for generating responses
type ModelProfile struct {
	ID            uuid.UUID                 `json:"id" yaml:"id"` // Unique identifier for the profile
	UserID        string                    `json:"userId" yaml:"userId"` // Id of the user who owns the profile
	Name          string                    `json:"name" yaml:"name"` // Name of the profile
	Description   *string                   `json:"description" yaml:"description"` // Description of the profile
	ModelName     string                    `json:"modelName" yaml:"modelName"` // Name of the model to use
	Parameters    ModelParameters           `json:"parameters" yaml:"parameters"` // Parameters for configuring the model
	SystemPrompt  string                    `json:"systemPrompt" yaml:"systemPrompt"` // System prompt to send to the model
	CreatedAt     time.Time                 `json:"createdAt" yaml:"createdAt"` // Timestamp of when the profile was created
	UpdatedAt     time.Time                 `json:"updatedAt" yaml:"updatedAt"` // Timestamp of when the profile was last updated
	ModelVersion  *string                   `json:"modelVersion" yaml:"modelVersion"` // Version of the model
	Type          int                       `json:"type" yaml:"type"` // Type of the model profile
	ImageSettings *ModelProfileImageSettings `json:"image_settings" yaml:"image_settings"` // Image settings for the model profile
}
