// Code generated by schema2code at 2025-06-15 17:08:57. DO NOT EDIT.

package models


// ModelDetailsSpecialization Specialization of the model (e.g., 'LoRA', 'Embedding', 'TextToImage', 'Audio', 'Vision')
type ModelDetailsSpecialization string

const (
	ModelDetailsSpecializationLoRA ModelDetailsSpecialization = "LoRA"
	ModelDetailsSpecializationEmbedding ModelDetailsSpecialization = "Embedding"
	ModelDetailsSpecializationTextToImage ModelDetailsSpecialization = "TextToImage"
	ModelDetailsSpecializationAudio ModelDetailsSpecialization = "Audio"
	ModelDetailsSpecializationVision ModelDetailsSpecialization = "Vision"
)
// ModelDetails ModelDetails contains additional information about a model
type ModelDetails struct {
	ParentModel       *string  `json:"parent_model" yaml:"parent_model"` // Identifier of the parent model if this is a derivative
	Format            string   `json:"format" yaml:"format"` // Format of the model file (e.g., gguf)
	Family            string   `json:"family" yaml:"family"` // Primary model family this belongs to (e.g., llama, phi3)
	Families          []string `json:"families" yaml:"families"` // All model families this belongs to
	ParameterSize     string   `json:"parameter_size" yaml:"parameter_size"` // Size of model parameters (e.g., '7.2B')
	QuantizationLevel string   `json:"quantization_level" yaml:"quantization_level"` // Level of quantization applied to the model (e.g., 'Q4_0')
	Specialization    *ModelDetailsSpecialization `json:"specialization" yaml:"specialization"` // Specialization of the model (e.g., 'LoRA', 'Embedding', 'TextToImage', 'Audio', 'Vision')
	Description       *string  `json:"description" yaml:"description"` // Description of the model
	Weight            *float32 `json:"weight" yaml:"weight"` // Weight of the model (applies to LoRA models)
}
