// Code generated by schema2code at 2025-06-15 17:08:57. DO NOT EDIT.

package models


// Model Model represents a machine learning model used for generating responses
type Model struct {
	Name       string       `json:"name" yaml:"name"` // Display name of the model
	Model      string       `json:"model" yaml:"model"` // Identifier used to reference the model
	ModifiedAt string       `json:"modified_at" yaml:"modified_at"` // Timestamp of when the model was last modified
	Size       int          `json:"size" yaml:"size"` // Size of the model in bytes
	Digest     string       `json:"digest" yaml:"digest"` // Hash digest identifying the model version
	Details    ModelDetails `json:"details" yaml:"details"` // Additional information about the model
}
