// Code generated by schema2code at 2025-06-11 16:13:29. DO NOT EDIT.

package models


// ModelDetails ModelDetails contains additional information about a model
type ModelDetails struct {
	ParentModel       string   `json:"parent_model"`       // Identifier of the parent model if this is a derivative
	Format            string   `json:"format"`             // Format of the model file (e.g., gguf)
	Family            string   `json:"family"`             // Primary model family this belongs to (e.g., llama, phi3)
	Families          []string `json:"families"`           // All model families this belongs to
	ParameterSize     string   `json:"parameter_size"`     // Size of model parameters (e.g., '7.2B')
	QuantizationLevel string   `json:"quantization_level"` // Level of quantization applied to the model (e.g., 'Q4_0')
}
