// Code generated by schema2code at 2025-06-11 16:13:28. DO NOT EDIT.

package models


// Model Model represents a machine learning model used for generating responses
type Model struct {
	Name       string       `json:"name"`        // Display name of the model
	Model      string       `json:"model"`       // Identifier used to reference the model
	ModifiedAt string       `json:"modified_at"` // Timestamp of when the model was last modified
	Size       int          `json:"size"`        // Size of the model in bytes
	Digest     string       `json:"digest"`      // Hash digest identifying the model version
	Details    ModelDetails `json:"details"`     // Additional information about the model
}
