// Code generated by schema2code at 2025-06-11 16:13:29. DO NOT EDIT.

package models


// RedisConfig Redis configuration
type RedisConfig struct {
	Host               string `json:"host"`                 // Redis host
	Port               int    `json:"port"`                 // Redis port
	Password           *string `json:"password"`             // Redis password
	DB                 int    `json:"db"`                   // Redis database index
	Enabled            bool   `json:"enabled"`              // Whether Redis is enabled
	ConversationTtl    string `json:"conversation_ttl"`     // Conversation TTL
	MessageTtl         string `json:"message_ttl"`          // Message TTL
	SummaryTtl         string `json:"summary_ttl"`          // Summary TTL
	PoolSize           int    `json:"pool_size"`            // Connection pool size
	MinIdleConnections int    `json:"min_idle_connections"` // Minimum idle connections
	ConnectTimeout     string `json:"connect_timeout"`      // Connection timeout
}
