// Code generated by schema2code at 2025-07-09 14:22:07. DO NOT EDIT.

package models


// RefinementConfig Response refinement settings
type RefinementConfig struct {
	EnableResponseFiltering bool `json:"enable_response_filtering" yaml:"enable_response_filtering"` // Enable response filtering
	EnableResponseCritique  bool `json:"enable_response_critique" yaml:"enable_response_critique"` // Enable response critique
}
