// Code generated by schema2code at 2025-06-11 16:13:30. DO NOT EDIT.

package models


// RefinementConfig Response refinement settings
type RefinementConfig struct {
	EnableResponseFiltering *bool `json:"enable_response_filtering"` // Enable response filtering
	EnableResponseCritique  *bool `json:"enable_response_critique"`  // Enable response critique
}
