// Code generated by schema2code at 2025-06-15 17:09:00. DO NOT EDIT.

package models


// RefinementConfig Response refinement settings
type RefinementConfig struct {
	EnableResponseFiltering bool `json:"enable_response_filtering" yaml:"enable_response_filtering"` // Enable response filtering
	EnableResponseCritique  bool `json:"enable_response_critique" yaml:"enable_response_critique"` // Enable response critique
}
