// Code generated by schema2code at 2025-06-11 16:13:29. DO NOT EDIT.

package models


// ResearchQuestion Sub-question in a research plan
type ResearchQuestion struct {
	ID       int      `json:"id"`       // Unique identifier for the question
	Question string   `json:"question"` // The question to investigate
	Keywords []string `json:"keywords"` // Keywords relevant to the question
}
