// Code generated by schema2code at 2025-07-09 14:22:06. DO NOT EDIT.

package models


// ResearchQuestion Sub-question in a research plan
type ResearchQuestion struct {
	ID       int      `json:"id" yaml:"id"` // Unique identifier for the question
	Question string   `json:"question" yaml:"question"` // The question to investigate
	Keywords []string `json:"keywords" yaml:"keywords"` // Keywords relevant to the question
}
