// Code generated by schema2code at 2025-07-18 21:27:34. DO NOT EDIT.

package models


// ServerConfig Server configuration
type ServerConfig struct {
	Host    string `json:"host" yaml:"host"` // Server host
	Port    int    `json:"port" yaml:"port"` // Server port
	BaseURL string `json:"base_url" yaml:"base_url"` // Base URL
}
