// Code generated by schema2code at 2025-06-11 16:13:30. DO NOT EDIT.

package models


// ServerConfig Server configuration
type ServerConfig struct {
	Host    string `json:"host"`     // Server host
	Port    int    `json:"port"`     // Server port
	BaseURL string `json:"base_url"` // Base URL
}
