// Code generated by schema2code at 2025-07-09 14:22:06. DO NOT EDIT.

package models


// SocketStageType The current processing stage.
type SocketStageType string

const (
	SocketStageTypeInitializing SocketStageType = "initializing"
	SocketStageTypeRetrievingMemories SocketStageType = "retrieving_memories"
	SocketStageTypeSearchingWeb SocketStageType = "searching_web"
	SocketStageTypeSummarizing SocketStageType = "summarizing"
	SocketStageTypeGeneratingImage SocketStageType = "generating_image"
	SocketStageTypeProcessing SocketStageType = "processing"
	SocketStageTypeRendering SocketStageType = "rendering"
	SocketStageTypeInterpreting SocketStageType = "interpreting"
	SocketStageTypeOpen SocketStageType = "open"
)