// Code generated by schema2code at 2025-07-01 15:06:46. DO NOT EDIT.

package models


// SocketConnectionType SocketConnectionType represents the type of connection used in a WebSocket communication
type SocketConnectionType string

const (
	SocketConnectionTypeImage SocketConnectionType = "image"
	SocketConnectionTypeChat SocketConnectionType = "chat"
	SocketConnectionTypeStatus SocketConnectionType = "status"
)