// Code generated by schema2code at 2025-07-09 14:22:06. DO NOT EDIT.

package models


// SocketConnectionType SocketConnectionType represents the type of connection used in a WebSocket communication
type SocketConnectionType string

const (
	SocketConnectionTypeImage SocketConnectionType = "image"
	SocketConnectionTypeChat SocketConnectionType = "chat"
	SocketConnectionTypeStatus SocketConnectionType = "status"
)