// Code generated by schema2code at 2025-06-15 17:08:59. DO NOT EDIT.

package models


// StatusUpdateType The type of status update (info, warning, error).
type StatusUpdateType string

const (
	StatusUpdateTypeInfo StatusUpdateType = "info"
	StatusUpdateTypeWarning StatusUpdateType = "warning"
	StatusUpdateTypeError StatusUpdateType = "error"
)
// StatusUpdateStage The current processing stage.
type StatusUpdateStage string

const (
	StatusUpdateStageInitializing StatusUpdateStage = "initializing"
	StatusUpdateStageRetrievingMemories StatusUpdateStage = "retrieving_memories"
	StatusUpdateStageSearchingWeb StatusUpdateStage = "searching_web"
	StatusUpdateStageSummarizing StatusUpdateStage = "summarizing"
	StatusUpdateStageGenerating StatusUpdateStage = "generating"
	StatusUpdateStageProcessing StatusUpdateStage = "processing"
	StatusUpdateStageRendering StatusUpdateStage = "rendering"
	StatusUpdateStageCompleted StatusUpdateStage = "completed"
	StatusUpdateStageError StatusUpdateStage = "error"
)
// StatusUpdate StatusUpdate represents a status update message sent via WebSocket
type StatusUpdate struct {
	UserID   string `json:"UserID" yaml:"UserID"` // The ID of the user associated with the status update.
	Type     StatusUpdateType `json:"Type" yaml:"Type"` // The type of status update (info, warning, error).
	Stage    StatusUpdateStage `json:"Stage" yaml:"Stage"` // The current processing stage.
	Message  *string `json:"Message" yaml:"Message"` // Optional detailed message.
	Progress int    `json:"Progress" yaml:"Progress"` // 0-100 progress percentage.
	Done     bool   `json:"Done" yaml:"Done"` // Whether processing is complete.
}
