// Code generated by schema2code at 2025-06-11 16:13:30. DO NOT EDIT.

package models

import (
	"time"
)

// Summary Summary represents a consolidated summary of messages or other summaries
type Summary struct {
	Content        string    `json:"content"`         // Text content of the summary
	Level          int       `json:"level"`           // Level of the summary in the hierarchy
	ID             int       `json:"id"`              // Unique identifier for the summary
	ConversationID int       `json:"conversation_id"` // Id of the conversation this summary belongs to
	SourceIds      []int     `json:"source_ids"`      // IDs of the source messages or summaries
	CreatedAt      time.Time `json:"created_at"`      // Timestamp of when the summary was created
}
