// Code generated by schema2code at 2025-06-11 16:13:30. DO NOT EDIT.

package models


// SummarizationConfig Conversation summarization settings
type SummarizationConfig struct {
	Enabled                      *bool   `json:"enabled"`                        // Whether summarization is enabled
	MessagesBeforeSummary        *int    `json:"messages_before_summary"`        // Number of messages before summary
	SummariesBeforeConsolidation *int    `json:"summaries_before_consolidation"` // Number of summaries before consolidation
	EmbeddingModel               *string `json:"embedding_model"`                // Embedding model
	EmbeddingDimension           *int    `json:"embedding_dimension"`            // Embedding dimension
	MaxSummaryLevels             *int    `json:"max_summary_levels"`             // Maximum summary levels
	SummaryWeightCoefficient     *float32 `json:"summary_weight_coefficient"`     // Summary weight coefficient
}
