// Code generated by schema2code at 2025-06-15 17:09:00. DO NOT EDIT.

package models









// UserConfig User-specific configuration
type UserConfig struct {
	UserID          string                `json:"user_id" yaml:"user_id"` // User ID
	Summarization   *SummarizationConfig  `json:"summarization" yaml:"summarization"`
	Memory          *MemoryConfig         `json:"memory" yaml:"memory"`
	WebSearch       *WebSearchConfig      `json:"web_search" yaml:"web_search"`
	Preferences     *PreferencesConfig    `json:"preferences" yaml:"preferences"`
	ModelProfiles   *ModelProfileConfig   `json:"model_profiles" yaml:"model_profiles"`
	Refinement      *RefinementConfig     `json:"refinement" yaml:"refinement"`
	ImageGeneration *ImageGenerationConfig `json:"image_generation" yaml:"image_generation"`
}
