// Code generated by schema2code at 2025-06-11 16:13:30. DO NOT EDIT.

package models

import (
	"time"
)

// User User represents a user of the system
type User struct {
	ID        string    `json:"id"`         // Unique identifier for the user
	Username  string    `json:"username"`   // Username of the user
	UID       string    `json:"uid"`        // User identification number
	CreatedAt time.Time `json:"created_at"` // Timestamp of when the user was created
}
