// Code generated by schema2code at 2025-06-15 17:09:00. DO NOT EDIT.

package models

import (
	"time"
)

// WebSocketConnectionType Type of WebSocket connection (e.g., chat, image, status)
type WebSocketConnectionType string

const (
	WebSocketConnectionTypeChat WebSocketConnectionType = "chat"
	WebSocketConnectionTypeImage WebSocketConnectionType = "image"
	WebSocketConnectionTypeStatus WebSocketConnectionType = "status"
)
// WebSocketConnection WebSocketConnection represents an active WebSocket connection
type WebSocketConnection struct {
	ID        string      `json:"ID" yaml:"ID"` // Unique identifier for the connection
	UserID    string      `json:"UserID" yaml:"UserID"` // Identifier of the user associated with the connection
	Type      WebSocketConnectionType `json:"Type" yaml:"Type"` // Type of WebSocket connection (e.g., chat, image, status)
	Conn      interface{} `json:"Conn" yaml:"Conn"` // The WebSocket connection object (represented as string)
	CreatedAt time.Time   `json:"CreatedAt" yaml:"CreatedAt"` // Timestamp indicating when the connection was established
}
