// Code generated by schema2code at 2025-06-11 16:13:30. DO NOT EDIT.

package models


// WebSearchConfig Web search settings
type WebSearchConfig struct {
	Enabled        *bool `json:"enabled"`         // Whether web search is enabled
	AutoDetect     *bool `json:"auto_detect"`     // Auto-detect web search
	MaxResults     *int `json:"max_results"`     // Maximum number of results
	IncludeResults *bool `json:"include_results"` // Include results in response
}
