# Code generated by schema2code at 2026-02-28 18:59:54. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ThinkingContentBlock(BaseModel):
    """Extended thinking block (beta). Present in responses when extended thinking is enabled."""
    type: Annotated[Literal["thinking"], Field(...)]
    thinking: Annotated[str, Field(...)]

    model_config = ConfigDict(extra="ignore")

class ToolUseContentBlock(BaseModel):
    """A tool invocation block in an assistant message."""
    type: Annotated[Literal["tool_use"], Field(...)]
    id: Annotated[str, Field(..., description="Unique identifier for this tool use.")]
    """Unique identifier for this tool use."""
    name: Annotated[str, Field(...)]
    input: Annotated[Dict[str, Any], Field(..., description="Tool input as a JSON object.")]
    """Tool input as a JSON object."""

    model_config = ConfigDict(extra="ignore")

class TextContentBlock(BaseModel):
    type: Annotated[Literal["text"], Field(...)]
    text: Annotated[str, Field(...)]
    cache_control: Annotated[Optional[CacheControl], Field(default=None)] = None

    model_config = ConfigDict(extra="ignore")

class CacheControl(BaseModel):
    type: Annotated[Literal["ephemeral"], Field(...)]
    ttl: Annotated[Optional[str], Field(default=None, description="Time-to-live for the cache entry. Defaults to `5m`.")] = None
    """Time-to-live for the cache entry. Defaults to `5m`."""

    model_config = ConfigDict(extra="ignore")

class RedactedThinkingContentBlock(BaseModel):
    """Redacted thinking block (beta)."""
    type: Annotated[Literal["redacted_thinking"], Field(...)]
    data: Annotated[str, Field(...)]

    model_config = ConfigDict(extra="ignore")

OutputContentBlock = Union[TextContentBlock, ToolUseContentBlock, ThinkingContentBlock, RedactedThinkingContentBlock]