"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Button } from "../ui/button";
import { Separator } from "../ui/separator";
import { Tooltip, TooltipContent, TooltipTrigger } from "../ui/tooltip";
import { cn } from "../../lib/utils";
import { BookmarkIcon } from "lucide-react";
export const Checkpoint = ({ className, children, ...props }) => (_jsxs("div", { className: cn("flex items-center gap-0.5 text-muted-foreground overflow-hidden", className), ...props, children: [children, _jsx(Separator, {})] }));
export const CheckpointIcon = ({ className, children, ...props }) => children ?? (_jsx(BookmarkIcon, { className: cn("size-4 shrink-0", className), ...props }));
export const CheckpointTrigger = ({ children, className, variant = "ghost", size = "sm", tooltip, ...props }) => tooltip ? (_jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx(Button, { size: size, type: "button", variant: variant, ...props, children: children }) }), _jsx(TooltipContent, { align: "start", side: "bottom", children: tooltip })] })) : (_jsx(Button, { size: size, type: "button", variant: variant, ...props, children: children }));
