# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc as grpcio
import warnings

from . import composer_runner_pb2 as composer__runner__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = getattr(grpcio, '__version__', '1.78.0')
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except (ImportError, AttributeError):
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpcio package installed is at version {GRPC_VERSION},'
        + ' but the generated code in composer_runner_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpcio module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RunnerServiceStub(object):
    """RunnerService provides pipeline management and execution
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpcio.Channel.
        """
        self.CreatePipeline = channel.unary_unary(
                '/composer_runner.RunnerService/CreatePipeline',
                request_serializer=composer__runner__pb2.CreatePipelineRequest.SerializeToString,
                response_deserializer=composer__runner__pb2.PipelineHandle.FromString,
                _registered_method=True)
        self.ExecutePipeline = channel.unary_stream(
                '/composer_runner.RunnerService/ExecutePipeline',
                request_serializer=composer__runner__pb2.ExecutePipelineRequest.SerializeToString,
                response_deserializer=composer__runner__pb2.PipelineEvent.FromString,
                _registered_method=True)
        self.GenerateEmbeddings = channel.unary_unary(
                '/composer_runner.RunnerService/GenerateEmbeddings',
                request_serializer=composer__runner__pb2.GenerateEmbeddingsRequest.SerializeToString,
                response_deserializer=composer__runner__pb2.GenerateEmbeddingsResponse.FromString,
                _registered_method=True)
        self.GetCacheStats = channel.unary_unary(
                '/composer_runner.RunnerService/GetCacheStats',
                request_serializer=composer__runner__pb2.GetCacheStatsRequest.SerializeToString,
                response_deserializer=composer__runner__pb2.CacheStats.FromString,
                _registered_method=True)
        self.EvictPipeline = channel.unary_unary(
                '/composer_runner.RunnerService/EvictPipeline',
                request_serializer=composer__runner__pb2.EvictPipelineRequest.SerializeToString,
                response_deserializer=composer__runner__pb2.EvictPipelineResponse.FromString,
                _registered_method=True)


class RunnerServiceServicer(object):
    """RunnerService provides pipeline management and execution
    """

    def CreatePipeline(self, request, context):
        """CreatePipeline creates a new pipeline from profile
        """
        context.set_code(grpcio.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutePipeline(self, request, context):
        """ExecutePipeline executes a pipeline with streaming output
        """
        context.set_code(grpcio.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateEmbeddings(self, request, context):
        """GenerateEmbeddings generates embeddings for texts
        """
        context.set_code(grpcio.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCacheStats(self, request, context):
        """GetCacheStats returns pipeline cache statistics
        """
        context.set_code(grpcio.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EvictPipeline(self, request, context):
        """EvictPipeline evicts a pipeline from cache
        """
        context.set_code(grpcio.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RunnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePipeline': grpcio.unary_unary_rpc_method_handler(
                    servicer.CreatePipeline,
                    request_deserializer=composer__runner__pb2.CreatePipelineRequest.FromString,
                    response_serializer=composer__runner__pb2.PipelineHandle.SerializeToString,
            ),
            'ExecutePipeline': grpcio.unary_stream_rpc_method_handler(
                    servicer.ExecutePipeline,
                    request_deserializer=composer__runner__pb2.ExecutePipelineRequest.FromString,
                    response_serializer=composer__runner__pb2.PipelineEvent.SerializeToString,
            ),
            'GenerateEmbeddings': grpcio.unary_unary_rpc_method_handler(
                    servicer.GenerateEmbeddings,
                    request_deserializer=composer__runner__pb2.GenerateEmbeddingsRequest.FromString,
                    response_serializer=composer__runner__pb2.GenerateEmbeddingsResponse.SerializeToString,
            ),
            'GetCacheStats': grpcio.unary_unary_rpc_method_handler(
                    servicer.GetCacheStats,
                    request_deserializer=composer__runner__pb2.GetCacheStatsRequest.FromString,
                    response_serializer=composer__runner__pb2.CacheStats.SerializeToString,
            ),
            'EvictPipeline': grpcio.unary_unary_rpc_method_handler(
                    servicer.EvictPipeline,
                    request_deserializer=composer__runner__pb2.EvictPipelineRequest.FromString,
                    response_serializer=composer__runner__pb2.EvictPipelineResponse.SerializeToString,
            ),
    }
    generic_handler = grpcio.method_handlers_generic_handler(
            'composer_runner.RunnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('composer_runner.RunnerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RunnerService(object):
    """RunnerService provides pipeline management and execution
    """

    @staticmethod
    def CreatePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpcio.experimental.unary_unary(
            request,
            target,
            '/composer_runner.RunnerService/CreatePipeline',
            composer__runner__pb2.CreatePipelineRequest.SerializeToString,
            composer__runner__pb2.PipelineHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecutePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpcio.experimental.unary_stream(
            request,
            target,
            '/composer_runner.RunnerService/ExecutePipeline',
            composer__runner__pb2.ExecutePipelineRequest.SerializeToString,
            composer__runner__pb2.PipelineEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateEmbeddings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpcio.experimental.unary_unary(
            request,
            target,
            '/composer_runner.RunnerService/GenerateEmbeddings',
            composer__runner__pb2.GenerateEmbeddingsRequest.SerializeToString,
            composer__runner__pb2.GenerateEmbeddingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCacheStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpcio.experimental.unary_unary(
            request,
            target,
            '/composer_runner.RunnerService/GetCacheStats',
            composer__runner__pb2.GetCacheStatsRequest.SerializeToString,
            composer__runner__pb2.CacheStats.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EvictPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpcio.experimental.unary_unary(
            request,
            target,
            '/composer_runner.RunnerService/EvictPipeline',
            composer__runner__pb2.EvictPipelineRequest.SerializeToString,
            composer__runner__pb2.EvictPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
