# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import server_composer_pb2 as server__composer__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in server_composer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComposerServiceStub(object):
    """ComposerService provides workflow composition and execution
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComposeWorkflow = channel.unary_unary(
                '/server_composer.ComposerService/ComposeWorkflow',
                request_serializer=server__composer__pb2.ComposeWorkflowRequest.SerializeToString,
                response_deserializer=server__composer__pb2.WorkflowHandle.FromString,
                _registered_method=True)
        self.ExecuteWorkflow = channel.unary_stream(
                '/server_composer.ComposerService/ExecuteWorkflow',
                request_serializer=server__composer__pb2.ExecuteWorkflowRequest.SerializeToString,
                response_deserializer=server__composer__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.CreateInitialState = channel.unary_unary(
                '/server_composer.ComposerService/CreateInitialState',
                request_serializer=server__composer__pb2.CreateInitialStateRequest.SerializeToString,
                response_deserializer=server__composer__pb2.WorkflowState.FromString,
                _registered_method=True)
        self.ClearWorkflowCache = channel.unary_unary(
                '/server_composer.ComposerService/ClearWorkflowCache',
                request_serializer=server__composer__pb2.ClearWorkflowCacheRequest.SerializeToString,
                response_deserializer=server__composer__pb2.ClearWorkflowCacheResponse.FromString,
                _registered_method=True)


class ComposerServiceServicer(object):
    """ComposerService provides workflow composition and execution
    """

    def ComposeWorkflow(self, request, context):
        """ComposeWorkflow creates a new workflow from requirements
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteWorkflow(self, request, context):
        """ExecuteWorkflow executes a workflow with streaming responses
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateInitialState(self, request, context):
        """CreateInitialState creates initial state for a workflow
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearWorkflowCache(self, request, context):
        """ClearWorkflowCache clears cached workflows for a user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComposerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComposeWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.ComposeWorkflow,
                    request_deserializer=server__composer__pb2.ComposeWorkflowRequest.FromString,
                    response_serializer=server__composer__pb2.WorkflowHandle.SerializeToString,
            ),
            'ExecuteWorkflow': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteWorkflow,
                    request_deserializer=server__composer__pb2.ExecuteWorkflowRequest.FromString,
                    response_serializer=server__composer__pb2.ChatResponse.SerializeToString,
            ),
            'CreateInitialState': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateInitialState,
                    request_deserializer=server__composer__pb2.CreateInitialStateRequest.FromString,
                    response_serializer=server__composer__pb2.WorkflowState.SerializeToString,
            ),
            'ClearWorkflowCache': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearWorkflowCache,
                    request_deserializer=server__composer__pb2.ClearWorkflowCacheRequest.FromString,
                    response_serializer=server__composer__pb2.ClearWorkflowCacheResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'server_composer.ComposerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('server_composer.ComposerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComposerService(object):
    """ComposerService provides workflow composition and execution
    """

    @staticmethod
    def ComposeWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_composer.ComposerService/ComposeWorkflow',
            server__composer__pb2.ComposeWorkflowRequest.SerializeToString,
            server__composer__pb2.WorkflowHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/server_composer.ComposerService/ExecuteWorkflow',
            server__composer__pb2.ExecuteWorkflowRequest.SerializeToString,
            server__composer__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateInitialState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_composer.ComposerService/CreateInitialState',
            server__composer__pb2.CreateInitialStateRequest.SerializeToString,
            server__composer__pb2.WorkflowState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearWorkflowCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/server_composer.ComposerService/ClearWorkflowCache',
            server__composer__pb2.ClearWorkflowCacheRequest.SerializeToString,
            server__composer__pb2.ClearWorkflowCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
