// Code generated by schema2code at 2026-02-21 22:33:23. DO NOT EDIT.


/**
 * Controls diagnostic tracing during the session.
 */
export interface WorkflowTracingParam {
  /**
   * Whether tracing is enabled during the session. Defaults to true.
   */
  enabled?: boolean;
}