// Code generated by schema2code at 2026-02-23 16:02:22. DO NOT EDIT.


/**
 * Status values reported for apply_patch tool calls.
 */
export type ApplyPatchCallStatusParam = 'in_progress' | 'completed';

/**
 * Constant values for ApplyPatchCallStatusParam
 */
export const ApplyPatchCallStatusParamValues = {
  /** in_progress */
  IN_PROGRESS: 'in_progress',
  /** completed */
  COMPLETED: 'completed'
} as const;