// Code generated by schema2code at 2026-02-23 16:06:02. DO NOT EDIT.


export interface ApproximateLocation {
  city?: string | unknown;
  country?: string | unknown;
  region?: string | unknown;
  timezone?: string | unknown;
  /**
   * The type of location approximation. Always `approximate`.
   */
  type: 'approximate';
}