// Code generated by schema2code at 2026-02-23 16:02:31. DO NOT EDIT.


/**
 * The user who performed the audit logged action.
 */
export interface AuditLogActorUser {
  /**
   * The user email.
   */
  email?: string;
  /**
   * The user id.
   */
  id?: string;
}