// Code generated by schema2code at 2026-02-23 16:02:31. DO NOT EDIT.


import { AuditLogActorUser } from './AuditLogActorUser';



/**
 * The session in which the audit logged action was performed.
 */
export interface AuditLogActorSession {
  /**
   * The IP address from which the action was performed.
   */
  ip_address?: string;
  user?: AuditLogActorUser;
}