

export interface ChatCompletionRequestMessageContentPartRefusal {
  /**
   * The refusal message generated by the model.
   */
  refusal: string;
  /**
   * The type of the content part.
   */
  type: 'refusal';
}