// Code generated by schema2code at 2026-02-23 17:51:55. DO NOT EDIT.


/**
 * Automatic thread title preferences for the session.
 */
export interface ChatSessionAutomaticThreadTitling {
  /**
   * Whether automatic thread titling is enabled.
   */
  enabled: boolean;
}