// Code generated by schema2code at 2026-02-23 16:02:39. DO NOT EDIT.


export interface ChatCompletionRequestMessageContentPartRefusal {
  /**
   * The refusal message generated by the model.
   */
  refusal: string;
  /**
   * The type of the content part.
   */
  type: 'refusal';
}