// Code generated by schema2code at 2026-02-23 16:02:45. DO NOT EDIT.


/**
 * Controls diagnostic tracing during the session.
 */
export interface ChatkitWorkflowTracing {
  /**
   * Indicates whether tracing is enabled.
   */
  enabled: boolean;
}