// Code generated by schema2code at 2026-02-23 16:05:35. DO NOT EDIT.


/**
 * Indicates that a thread has been closed.
 */
export interface ClosedStatus {
  reason: string | unknown;
  /**
   * Status discriminator that is always `closed`.
   */
  type: 'closed';
}