// Code generated by schema2code at 2026-02-23 16:03:03. DO NOT EDIT.


/**
 * A chat message that makes up the prompt or context. May include variable references to the `item` namespace, ie {{item.name}}.
 */
export interface CreateEvalItem {
}