// Code generated by schema2code at 2026-02-23 16:03:05. DO NOT EDIT.


export interface CreateFineTuningCheckpointPermissionRequest {
  /**
   * The project identifiers to grant access to.
   */
  project_ids: (string)[];
}