// Code generated by schema2code at 2026-02-23 16:03:00. DO NOT EDIT.


export interface CreateContainerFileBody {
  /**
   * The File object (not file name) to be uploaded.

   */
  file?: string;
  /**
   * Name of the file to create.
   */
  file_id?: string;
}