// Code generated by schema2code at 2026-02-23 16:03:28. DO NOT EDIT.


/**
 * An object representing an error response from the Eval API.

 */
export interface EvalApiError {
  /**
   * The error code.
   */
  code: string;
  /**
   * The error message.
   */
  message: string;
}