// Code generated by schema2code at 2026-02-23 16:03:25. DO NOT EDIT.


/**
 * A single content item: input text, output text, input image, or input audio.

 */
export interface EvalItemContentItem {
}