// Code generated by schema2code at 2026-02-23 17:52:20. DO NOT EDIT.


/**
 * Controls when the session expires relative to an anchor timestamp.
 */
export interface ExpiresAfterParam {
  /**
   * Base timestamp used to calculate expiration. Currently fixed to `created_at`.
   */
  anchor: 'created_at';
  /**
   * Number of seconds after the anchor when the session expires.
   */
  seconds: number;
}