// Code generated by schema2code at 2026-02-23 17:52:40. DO NOT EDIT.


import { FineTuneDPOHyperparameters } from './FineTuneDpoHyperparameters';



/**
 * Configuration for the DPO fine-tuning method.
 */
export interface FineTuneDPOMethod {
  hyperparameters?: FineTuneDPOHyperparameters;
}