// Code generated by schema2code at 2026-02-23 17:52:41. DO NOT EDIT.


import { FineTuneSupervisedHyperparameters } from './FineTuneSupervisedHyperparameters';



/**
 * Configuration for the supervised fine-tuning method.
 */
export interface FineTuneSupervisedMethod {
  hyperparameters?: FineTuneSupervisedHyperparameters;
}