// Code generated by schema2code at 2026-02-23 16:03:58. DO NOT EDIT.


/**
 * An item representing a message, tool call, tool output, reasoning, or other response element.
 */
export interface ItemField {
}