// Code generated by schema2code at 2026-02-23 16:04:01. DO NOT EDIT.


import { FineTuningJobEvent } from './FineTuningJobEvent';



export interface ListFineTuningJobEventsResponse {
  data: (FineTuningJobEvent)[];
  has_more: boolean;
  object: 'list';
}