// Code generated by schema2code at 2026-02-23 16:04:00. DO NOT EDIT.


import { Certificate } from './Certificate';



export interface ListCertificatesResponse {
  data: (Certificate)[];
  first_id?: string;
  has_more: boolean;
  last_id?: string;
  object: 'list';
}