// Code generated by schema2code at 2026-02-23 16:04:01. DO NOT EDIT.


import { FineTuningJob } from './FineTuningJob';



export interface ListPaginatedFineTuningJobsResponse {
  data: (FineTuningJob)[];
  has_more: boolean;
  object: 'list';
}