// Code generated by schema2code at 2026-02-23 16:04:00. DO NOT EDIT.


import { FineTuningCheckpointPermission } from './FineTuningCheckpointPermission';



export interface ListFineTuningCheckpointPermissionResponse {
  data: (FineTuningCheckpointPermission)[];
  first_id?: string | unknown;
  has_more: boolean;
  last_id?: string | unknown;
  object: 'list';
}