// Code generated by schema2code at 2026-02-23 16:03:59. DO NOT EDIT.


import { AuditLog } from './AuditLog';



export interface ListAuditLogsResponse {
  data: (AuditLog)[];
  first_id: string;
  has_more: boolean;
  last_id: string;
  object: 'list';
}