// Code generated by schema2code at 2026-02-23 16:04:10. DO NOT EDIT.


import { Metadata } from './Metadata';



export interface ModifyThreadRequest {
  metadata?: Metadata;
  tool_resources?: ToolResourcesOption0 | unknown;
}