// Code generated by schema2code at 2026-02-23 16:04:18. DO NOT EDIT.


import { ProjectServiceAccount } from './ProjectServiceAccount';



export interface ProjectServiceAccountListResponse {
  data: (ProjectServiceAccount)[];
  first_id: string;
  has_more: boolean;
  last_id: string;
  object: 'list';
}