// Code generated by schema2code at 2026-02-23 16:04:18. DO NOT EDIT.


export interface ProjectServiceAccountApiKey {
  created_at: number;
  id: string;
  name: string;
  /**
   * The object type, which is always `organization.project.service_account.api_key`
   */
  object: 'organization.project.service_account.api_key';
  value: string;
}