// Code generated by schema2code at 2026-02-23 16:04:20. DO NOT EDIT.


import { ProjectUser } from './ProjectUser';



export interface ProjectUserListResponse {
  data: (ProjectUser)[];
  first_id: string;
  has_more: boolean;
  last_id: string;
  object: string;
}