// Code generated by schema2code at 2026-02-23 16:05:11. DO NOT EDIT.


/**
 * Default response format. Used to generate text responses.

 */
export interface ResponseFormatText {
  /**
   * The type of response format being defined. Always `text`.
   */
  type: 'text';
}