// Code generated by schema2code at 2026-02-23 16:05:24. DO NOT EDIT.


/**
 * Confirmation payload returned after deleting a role.
 */
export interface RoleDeletedResource {
  /**
   * Whether the role was deleted.
   */
  deleted: boolean;
  /**
   * Identifier of the deleted role.
   */
  id: string;
  /**
   * Always `role.deleted`.
   */
  object: 'role.deleted';
}