// Code generated by schema2code at 2026-02-23 16:05:31. DO NOT EDIT.


import { StaticChunkingStrategy } from './StaticChunkingStrategy';



export interface StaticChunkingStrategyResponseParam {
  static: StaticChunkingStrategy;
  /**
   * Always `static`.
   */
  type: 'static';
}