// Code generated by schema2code at 2026-02-23 16:05:32. DO NOT EDIT.


/**
 * A summary text from the model.
 */
export interface Summary {
  /**
   * A summary of the reasoning output from the model so far.
   */
  text: string;
  /**
   * The type of the object. Always `summary_text`.
   */
  type: 'summary_text';
}