// Code generated by schema2code at 2026-02-23 16:05:37. DO NOT EDIT.


/**
 * Tool selection that the assistant should honor when executing the item.
 */
export interface ToolChoice {
  /**
   * Identifier of the requested tool.
   */
  id: string;
}