// Code generated by schema2code at 2026-02-23 16:05:40. DO NOT EDIT.


export type TruncationEnum = 'auto' | 'disabled';

/**
 * Constant values for TruncationEnum
 */
export const TruncationEnumValues = {
  /** auto */
  AUTO: 'auto',
  /** disabled */
  DISABLED: 'disabled'
} as const;