// Code generated by schema2code at 2026-02-23 17:51:37. DO NOT EDIT.


export type ApplyPatchCallOutputStatus = 'completed' | 'failed';

/**
 * Constant values for ApplyPatchCallOutputStatus
 */
export const ApplyPatchCallOutputStatusValues = {
  /** completed */
  COMPLETED: 'completed',
  /** failed */
  FAILED: 'failed'
} as const;