// Code generated by schema2code at 2026-02-23 17:51:37. DO NOT EDIT.


/**
 * Outcome values reported for apply_patch tool call outputs.
 */
export type ApplyPatchCallOutputStatusParam = 'completed' | 'failed';

/**
 * Constant values for ApplyPatchCallOutputStatusParam
 */
export const ApplyPatchCallOutputStatusParamValues = {
  /** completed */
  COMPLETED: 'completed',
  /** failed */
  FAILED: 'failed'
} as const;