// Code generated by schema2code at 2026-02-23 17:51:38. DO NOT EDIT.


import { FunctionObject } from './FunctionObject';



export interface AssistantToolsFunction {
  function: FunctionObject;
  /**
   * The type of tool being defined: `function`
   */
  type: 'function';
}