// Code generated by schema2code at 2026-02-23 17:51:43. DO NOT EDIT.


export type AttachmentType = 'image' | 'file';

/**
 * Constant values for AttachmentType
 */
export const AttachmentTypeValues = {
  /** image */
  IMAGE: 'image',
  /** file */
  FILE: 'file'
} as const;