// Code generated by schema2code at 2026-02-23 17:51:43. DO NOT EDIT.


/**
 * Learn about [text inputs](https://platform.openai.com/docs/guides/text-generation).

 */
export interface ChatCompletionRequestMessageContentPartText {
  /**
   * The text content.
   */
  text: string;
  /**
   * The type of the content part.
   */
  type: 'text';
}