// Code generated by schema2code at 2026-02-23 17:51:54. DO NOT EDIT.


/**
 * History retention preferences returned for the session.
 */
export interface ChatSessionHistory {
  /**
   * Indicates if chat history is persisted for the session.
   */
  enabled: boolean;
  recent_threads: number | unknown;
}