// Code generated by schema2code at 2026-02-23 17:51:54. DO NOT EDIT.


/**
 * The logs output from the code interpreter.
 */
export interface CodeInterpreterOutputLogs {
  /**
   * The logs output from the code interpreter.
   */
  logs: string;
  /**
   * The type of the output. Always `logs`.
   */
  type: 'logs';
}