// Code generated by schema2code at 2026-02-23 17:52:09. DO NOT EDIT.


/**
 * The conversation that this response belongs to.
 */
export interface ConversationParam-2 {
  /**
   * The unique ID of the conversation.
   */
  id: string;
}