// Code generated by schema2code at 2026-02-23 16:05:42. DO NOT EDIT.


import { VectorStoreFileAttributes } from './VectorStoreFileAttributes';



export interface UpdateVectorStoreFileAttributesRequest {
  attributes: VectorStoreFileAttributes;
}