// Code generated by schema2code at 2026-02-23 16:05:42. DO NOT EDIT.


export interface UploadCertificateRequest {
  /**
   * The certificate content in PEM format
   */
  content: string;
  /**
   * An optional name for the certificate
   */
  name?: string;
}