// Code generated by schema2code at 2026-02-23 16:05:47. DO NOT EDIT.


import { User } from './User';



export interface UserListResponse {
  data: (User)[];
  first_id: string;
  has_more: boolean;
  last_id: string;
  object: 'list';
}