// Code generated by schema2code at 2025-06-11 16:13:30. DO NOT EDIT.


/**
 * ChatRequest represents a request from the UI
 */
export interface ChatRequest {
  /**
   * Message to send to the model, each message is a struct with role and content
   */
  content: string;
  /**
   * reference to the conversation this message belongs to
   */
  conversation_id: number;
}