// Code generated by schema2code at 2025-06-15 17:09:00. DO NOT EDIT.


import { ChatMessageMetadata } from './ChatMessageMetadata';



/**
 * Message in a chat conversation
 */
export interface ChatMessage {
  /**
   * Unique identifier for the message
   */
  id?: number;
  /**
   * Identifier for the conversation this message belongs to
   */
  conversation_id: number;
  /**
   * Role of the message sender (e.g., user, assistant)
   */
  role: string;
  /**
   * Text content of the message
   */
  content: string;
  /**
   * Optional images associated with the message
   */
  images?: string[];
  /**
   * Optional tool calls associated with the message
   */
  tool_calls?: Record<string, unknown>[];
  /**
   * Optional thinking process of the model, if applicable
   */
  thinking?: string;
  metadata?: ChatMessageMetadata;
}