// Code generated by schema2code at 2025-07-18 21:27:35. DO NOT EDIT.


import { ChatMessageMetadata } from './ChatMessageMetadata';



/**
 * ChatRequest represents a request from the UI
 */
export interface ChatRequest {
  /**
   * Message to send to the model, each message is a struct with role and content
   */
  content: string;
  /**
   * reference to the conversation this message belongs to
   */
  conversation_id: number;
  metadata?: ChatMessageMetadata;
}