// Code generated by schema2code at 2025-12-01 22:30:26. DO NOT EDIT.
/**
 * Constant values for ComplexityLevel
 */
export const ComplexityLevelValues = {
    /** TRIVIAL */
    TRIVIAL: 'TRIVIAL',
    /** SIMPLE */
    SIMPLE: 'SIMPLE',
    /** MODERATE */
    MODERATE: 'MODERATE',
    /** COMPLEX */
    COMPLEX: 'COMPLEX',
    /** SPECIALIZED */
    SPECIALIZED: 'SPECIALIZED'
};
