// Code generated by schema2code at 2026-03-05 12:20:57. DO NOT EDIT.


/**
 * Computational requirement levels for request processing
 */
export type ComputationalRequirement = 'MINIMAL' | 'LOW' | 'MODERATE' | 'HIGH' | 'INTENSIVE';

/**
 * Constant values for ComputationalRequirement
 */
export const ComputationalRequirementValues = {
  /** MINIMAL */
  MINIMAL: 'MINIMAL',
  /** LOW */
  LOW: 'LOW',
  /** MODERATE */
  MODERATE: 'MODERATE',
  /** HIGH */
  HIGH: 'HIGH',
  /** INTENSIVE */
  INTENSIVE: 'INTENSIVE'
} as const;