// Code generated by schema2code at 2025-11-06 20:59:23. DO NOT EDIT.


/**
 * Complexity level assessment for requests and operations
 */
export type ComplexityLevel = 'TRIVIAL' | 'SIMPLE' | 'MODERATE' | 'COMPLEX' | 'SPECIALIZED';

/**
 * Constant values for ComplexityLevel
 */
export const ComplexityLevelValues = {
  /** TRIVIAL */
  TRIVIAL: 'TRIVIAL',
  /** SIMPLE */
  SIMPLE: 'SIMPLE',
  /** MODERATE */
  MODERATE: 'MODERATE',
  /** COMPLEX */
  COMPLEX: 'COMPLEX',
  /** SPECIALIZED */
  SPECIALIZED: 'SPECIALIZED'
} as const;