// Code generated by schema2code at 2025-11-18 15:07:34. DO NOT EDIT.


/**
 * Current state of the generation process.
 */
export type GenerationState = 'analyzing' | 'thinking' | 'executing' | 'responding';

/**
 * Constant values for GenerationState
 */
export const GenerationStateValues = {
  /** analyzing */
  ANALYZING: 'analyzing',
  /** thinking */
  THINKING: 'thinking',
  /** executing */
  EXECUTING: 'executing',
  /** responding */
  RESPONDING: 'responding'
} as const;