// Code generated by schema2code at 2025-12-01 22:30:37. DO NOT EDIT.
/**
 * Constant values for GenerationState
 */
export const GenerationStateValues = {
    /** analyzing */
    ANALYZING: 'analyzing',
    /** thinking */
    THINKING: 'thinking',
    /** executing */
    EXECUTING: 'executing',
    /** responding */
    RESPONDING: 'responding'
};
