// Code generated by schema2code at 2025-06-15 17:09:01. DO NOT EDIT.


/**
 * Request for generating an image
 */
export interface ImageGenerateRequest {
  /**
   * The prompt for image generation
   */
  prompt: string;
  /**
   * Width of the generated image
   */
  width?: number;
  /**
   * Height of the generated image
   */
  height?: number;
  /**
   * Number of inference steps
   */
  inference_steps?: number;
  /**
   * Guidance scale for image generation
   */
  guidance_scale?: number;
  /**
   * Whether to use low memory mode
   */
  low_memory_mode?: boolean;
  /**
   * Negative prompt for image generation
   */
  negative_prompt?: string;
  /**
   * Identifier for the conversation this request belongs to
   */
  conversation_id: number;
  /**
   * Model to use for image generation
   */
  model: string;
  /**
   * List of LoRA models to apply to the image generation
   */
  loras?: string[];
}