// Code generated by schema2code at 2025-07-09 14:22:08. DO NOT EDIT.


/**
 * Response from generating an image
 */
export interface ImageGenerateResponse {
  /**
   * Base64-encoded image
   */
  image: string;
  /**
   * URL to download the image
   */
  download: string;
}