// Code generated by schema2code at 2025-06-15 17:09:01. DO NOT EDIT.


/**
 * Notification sent to clients when an image is generated.
 */
export interface ImageGenerationNotification {
  /**
   * Type of notification (e.g., "image_generated")
   */
  type: 'image_generated' | 'image_generation_failed';
  /**
   * ID of the generated image
   */
  image_id?: string;
  /**
   * URL to download the image
   */
  download_url?: string;
  /**
   * URL to view a thumbnail
   */
  thumbnail_url?: string;
  /**
   * The prompt used to generate the image
   */
  original_prompt?: string;
  /**
   * Error message if generation failed
   */
  error?: string;
  /**
   * Base64 encoded image data if applicable
   */
  b64_data?: string;
  /**
   * Identifier for the conversation this notification belongs to
   */
  conversation_id: number;
}