// Code generated by schema2code at 2025-12-01 22:30:38. DO NOT EDIT.
/**
 * Constant values for MessageType
 */
export const MessageTypeValues = {
    /** connect */
    CONNECT: 'connect',
    /** connected */
    CONNECTED: 'connected',
    /** pause */
    PAUSE: 'pause',
    /** paused */
    PAUSED: 'paused',
    /** resume */
    RESUME: 'resume',
    /** resumed */
    RESUMED: 'resumed',
    /** cancel */
    CANCEL: 'cancel',
    /** cancelled */
    CANCELLED: 'cancelled',
    /** complete */
    COMPLETE: 'complete',
    /** error */
    ERROR: 'error',
    /** warning */
    WARNING: 'warning',
    /** info */
    INFO: 'info',
    /** failed */
    FAILED: 'failed'
};
