// Code generated by schema2code at 2025-09-18 21:58:02. DO NOT EDIT.


import { MessageContent } from './MessageContent';

import { MessageRole } from './MessageRole';



/**
 * Message represents a single exchange in the conversation
 */
export interface Message {
  /**
   * Role of the message sender (e.g., user, assistant)
   */
  role: MessageRole;
  /**
   * Content of the message
   */
  content: MessageContent[];
  /**
   * Optional tool calls associated with the message
   */
  tool_calls?: Record<string, unknown>[];
  /**
   * Optional thinking process of the model, if applicable
   */
  thinking?: string;
  /**
   * Unique identifier for the message
   */
  id?: number;
  /**
   * Timestamp of when the message was created
   */
  created_at?: Date;
  /**
   * Unique identifier for the conversation
   */
  conversation_id?: number;
}