// Code generated by schema2code at 2025-10-23 12:58:57. DO NOT EDIT.


import { MessageContent } from './MessageContent';

import { MessageRole } from './MessageRole';



/**
 * Message represents a single exchange in the conversation
 */
export interface Message {
  /**
   * Role of the message sender (e.g., user, assistant)
   */
  role: MessageRole;
  /**
   * Content of the message
   */
  content: MessageContent[];
  /**
   * Unique identifier for the message
   */
  id?: number;
  /**
   * Timestamp of when the message was created
   */
  created_at?: Date;
  /**
   * Unique identifier for the conversation
   */
  conversation_id?: number;
}