// Code generated by schema2code at 2025-07-18 21:27:36. DO NOT EDIT.


import { MessageContentType } from './MessageContentType';



/**
 * Content of a message in a chat conversation
 */
export interface MessageContent {
  /**
   * Type of the message content (e.g., text, image, tool call)
   */
  type: MessageContentType;
  /**
   * Text content of the message, if applicable
   */
  text?: string;
  /**
   * URL of the image or resource, if applicable
   */
  url?: string;
}