// Code generated by schema2code at 2025-06-11 16:13:31. DO NOT EDIT.


/**
 * Type of model profile
 */
export enum ModelProfileType {
  Primary = 0,
  PrimarySummary = 1,
  MasterSummary = 2,
  BriefSummary = 3,
  KeyPoints = 4,
  SelfCritique = 5,
  Improvement = 6,
  MemoryRetrieval = 7,
  Analysis = 8,
  ResearchTask = 9,
  ResearchPlan = 10,
  ResearchConsolidation = 11,
  ResearchAnalysis = 12,
  Embedding = 13,
  Formatting = 14,
  ImageGeneration = 115,
}