// Code generated by schema2code at 2025-06-27 14:37:54. DO NOT EDIT.


import { ModelDetails } from './ModelDetails';



/**
 * Model represents a machine learning model used for generating responses
 */
export interface Model {
  /**
   * Unique identifier for the model
   */
  id?: string;
  /**
   * Display name of the model
   */
  name: string;
  /**
   * Identifier used to reference the model
   */
  model: string;
  /**
   * Timestamp of when the model was last modified
   */
  modified_at: string;
  /**
   * Size of the model in bytes
   */
  size: number;
  /**
   * Hash digest identifying the model version
   */
  digest: string;
  /**
   * Additional information about the model
   */
  details: ModelDetails;
  /**
   * Pipeline type used for the model (e.g., "sd3", "sdxl")
   */
  pipeline?: string;
  /**
   * List of LoRA weights associated with the model
   */
  lora_weight_ids?: string[];
}