// Code generated by schema2code at 2025-06-15 17:09:01. DO NOT EDIT.


import { ModelDetails } from './ModelDetails';



/**
 * Model represents a machine learning model used for generating responses
 */
export interface Model {
  /**
   * Display name of the model
   */
  name: string;
  /**
   * Identifier used to reference the model
   */
  model: string;
  /**
   * Timestamp of when the model was last modified
   */
  modified_at: string;
  /**
   * Size of the model in bytes
   */
  size: number;
  /**
   * Hash digest identifying the model version
   */
  digest: string;
  /**
   * Additional information about the model
   */
  details: ModelDetails;
}