// Code generated by schema2code at 2025-06-15 17:09:02. DO NOT EDIT.


import { ModelParameters } from './ModelParameters';

import { ModelProfileImageSettings } from './ModelProfileImageSettings';



/**
 * ModelProfile represents a model profile used for generating responses
 */
export interface ModelProfile {
  /**
   * Unique identifier for the profile
   */
  id: string;
  /**
   * Id of the user who owns the profile
   */
  userId: string;
  /**
   * Name of the profile
   */
  name: string;
  /**
   * Description of the profile
   */
  description?: string;
  /**
   * Name of the model to use
   */
  modelName: string;
  /**
   * Parameters for configuring the model
   */
  parameters: ModelParameters;
  /**
   * System prompt to send to the model
   */
  systemPrompt: string;
  /**
   * Timestamp of when the profile was created
   */
  createdAt: Date;
  /**
   * Timestamp of when the profile was last updated
   */
  updatedAt: Date;
  /**
   * Version of the model
   */
  modelVersion?: string;
  /**
   * Type of the model profile
   */
  type: number;
  /**
   * Image settings for the model profile
   */
  image_settings?: ModelProfileImageSettings;
}