// Code generated by schema2code at 2025-06-27 14:37:54. DO NOT EDIT.


/**
 * ModelDetails contains additional information about a model
 */
export interface ModelDetails {
  /**
   * Identifier of the parent model if this is a derivative
   */
  parent_model?: string;
  /**
   * Format of the model file (e.g., gguf)
   */
  format: string;
  /**
   * Primary model family this belongs to (e.g., llama, phi3)
   */
  family: string;
  /**
   * All model families this belongs to
   */
  families: string[];
  /**
   * Size of model parameters (e.g., '7.2B')
   */
  parameter_size: string;
  /**
   * Level of quantization applied to the model (e.g., 'Q4_0')
   */
  quantization_level: string;
  /**
   * Specialization of the model (e.g., 'LoRA', 'Embedding', 'TextToImage', 'Audio', 'Vision')
   */
  specialization?: 'LoRA' | 'Embedding' | 'TextToImage' | 'Audio' | 'Vision';
  /**
   * Description of the model
   */
  description?: string;
  /**
   * Weight of the model (applies to LoRA models)
   */
  weight?: number;
}