// Code generated by schema2code at 2025-12-01 22:30:34. DO NOT EDIT.
/**
 * Constant values for ParameterTuningStrategy
 */
export const ParameterTuningStrategyValues = {
    /** binary_search */
    BINARY_SEARCH: 'binary_search',
    /** exponential_backoff */
    EXPONENTIAL_BACKOFF: 'exponential_backoff',
    /** conservative_increment */
    CONSERVATIVE_INCREMENT: 'conservative_increment'
};
