// Code generated by schema2code at 2025-11-06 15:13:13. DO NOT EDIT.


/**
 * Minimum values for each parameter that must be maintained
 */
export interface ParameterFloors {
  /**
   * Minimum context size
   */
  n_ctx?: number;
  /**
   * Minimum batch size
   */
  n_batch?: number;
  /**
   * Minimum micro-batch size
   */
  n_ubatch?: number;
  /**
   * Minimum GPU layers (0 = CPU only)
   */
  n_gpu_layers?: number;
}

/**
 * Settings to prevent container crashes during optimization
 */
export interface CrashPrevention {
  /**
   * Test memory allocation before full initialization
   */
  enable_preallocation_test?: boolean;
  /**
   * Memory buffer to reserve (MB) to prevent system OOM
   */
  memory_buffer_mb?: number;
  /**
   * Maximum time to wait for initialization before considering it failed
   */
  timeout_seconds?: number;
  /**
   * Fall back to smaller parameters on failure
   */
  enable_graceful_degradation?: boolean;
}

/**
 * Configuration for optimizing LLM initialization parameters to find maximum values
 */
export interface ParameterOptimizationConfig {
  /**
   * Enable parameter optimization to find maximum viable values
   */
  enabled: boolean;
  /**
   * List of parameters to optimize in order of priority (highest first)
   */
  optimization_priority: 'n_ctx' | 'n_batch' | 'n_ubatch' | 'n_gpu_layers'[];
  /**
   * Minimum values for each parameter that must be maintained
   */
  parameter_floors: ParameterFloors;
  /**
   * Strategy for finding optimal values
   */
  search_strategy: 'binary_search' | 'exponential_backoff' | 'conservative_increment';
  /**
   * Maximum number of search attempts per parameter
   */
  max_search_attempts: number;
  /**
   * Settings to prevent container crashes during optimization
   */
  crash_prevention: CrashPrevention;
}