// Code generated by schema2code at 2025-11-06 18:22:53. DO NOT EDIT.


import { ParameterTuningStrategy } from './ParameterTuningStrategy';



/**
 * Performance parameters for model initialization
 */
export interface PerformanceParameters {
  /**
   * Name of the performance parameter
   */
  parameter_name: 'n_ctx' | 'n_batch' | 'n_ubatch' | 'n_gpu_layers';
  /**
   * Priority of the parameter for optimization (lower number = higher priority)
   */
  priority: number;
  /**
   * Strategy for tuning this parameter
   */
  tuning_strategy: ParameterTuningStrategy;
  /**
   * Maximum number of search attempts for this parameter
   */
  max_search_attempts: number;
  /**
   * Minimum value for the parameter during optimization
   */
  floor?: number;
}