// Code generated by schema2code at 2025-11-14 17:48:45. DO NOT EDIT.


/**
 * Response refinement settings
 */
export interface RefinementConfig {
  /**
   * Enable response filtering
   */
  enable_response_filtering: boolean;
  /**
   * Enable response critique
   */
  enable_response_critique: boolean;
}