// Code generated by schema2code at 2025-11-04 19:01:17. DO NOT EDIT.


/**
 * Format options for engineering responses
 */
export type ResponseFormat = 'detailed_analysis' | 'code_solution' | 'step_by_step_guide' | 'best_practices' | 'troubleshooting';

/**
 * Constant values for ResponseFormat
 */
export const ResponseFormatValues = {
  /** detailed_analysis */
  DETAILED_ANALYSIS: 'detailed_analysis',
  /** code_solution */
  CODE_SOLUTION: 'code_solution',
  /** step_by_step_guide */
  STEP_BY_STEP_GUIDE: 'step_by_step_guide',
  /** best_practices */
  BEST_PRACTICES: 'best_practices',
  /** troubleshooting */
  TROUBLESHOOTING: 'troubleshooting'
} as const;