// Code generated by schema2code at 2026-01-21 18:11:20. DO NOT EDIT.


import { GenerationState } from './GenerationState';



/**
 * A section of a generated response
 */
export interface ResponseSection {
  /**
   * Unique identifier for this section
   */
  id: string;
  /**
   * Order in which this section appeared
   */
  order: number;
  /**
   * Timestamp when section started
   */
  startedAt: number;
  /**
   * Timestamp when section completed (state changed)
   */
  completedAt?: number;
  /**
   * Type of section based on generation state
   */
  type: GenerationState;
  /**
   * Accumulated content for this section
   */
  content?: string;
  /**
   * Tool calls for executing sections
   */
  toolCalls?: ToolCall[];
}