// Code generated by schema2code at 2025-12-12 19:00:49. DO NOT EDIT.


/**
 * Represents a thought or reasoning process from an AI assistant
 */
export interface Thought {
  /**
   * Unique identifier for the thought
   */
  id?: number;
  /**
   * Foreign key reference to the associated message
   */
  message_id?: number;
  /**
   * The thinking/reasoning content
   */
  text: string;
  /**
   * Timestamp when the thought was created
   */
  created_at?: Date;
}