// Code generated by schema2code at 2026-04-21 15:13:49. DO NOT EDIT.


import { SummarizationConfig } from './SummarizationConfig';

import { MemoryConfig } from './MemoryConfig';

import { ModelProfileConfig } from './ModelProfileConfig';

import { ImageGenerationConfig } from './ImageGenerationConfig';

import { GPUConfig } from './GpuConfig';

import { WorkflowConfig } from './WorkflowConfig';

import { ToolConfig } from './ToolConfig';

import { EventStreamConfig } from './EventStreamConfig';



/**
 * User-specific configuration
 */
export interface UserConfig {
  /**
   * User ID
   */
  user_id: string;
  summarization?: SummarizationConfig;
  memory?: MemoryConfig;
  model_profiles?: ModelProfileConfig;
  image_generation?: ImageGenerationConfig;
  gpu_config: GPUConfig;
  workflow: WorkflowConfig;
  tool?: ToolConfig;
  event_stream?: EventStreamConfig;
}