// Code generated by schema2code at 2025-11-13 16:43:15. DO NOT EDIT.


/**
 * List of web search providers
 */
export type WebSearchProviders = 'google' | 'brave' | 'ddg' | 'searx' | 'serper';

/**
 * Constant values for WebSearchProviders
 */
export const WebSearchProvidersValues = {
  /** google */
  GOOGLE: 'google',
  /** brave */
  BRAVE: 'brave',
  /** ddg */
  DDG: 'ddg',
  /** searx */
  SEARX: 'searx',
  /** serper */
  SERPER: 'serper'
} as const;