// Code generated by schema2code at 2025-06-11 16:13:32. DO NOT EDIT.


/**
 * Web search settings
 */
export interface WebSearchConfig {
  /**
   * Whether web search is enabled
   */
  enabled?: boolean;
  /**
   * Auto-detect web search
   */
  auto_detect?: boolean;
  /**
   * Maximum number of results
   */
  max_results?: number;
  /**
   * Include results in response
   */
  include_results?: boolean;
}