# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dev_stats.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'dev_stats.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64\x65v_stats.proto\x12\x05proto\"\xf7\x02\n\x08\x44\x65vStats\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x10\n\x08gpu_util\x18\x03 \x01(\x01\x12\x10\n\x08mem_util\x18\x04 \x01(\x01\x12\x11\n\tmem_total\x18\x05 \x01(\x01\x12\x10\n\x08mem_used\x18\x06 \x01(\x01\x12\x10\n\x08mem_free\x18\x07 \x01(\x01\x12\x0e\n\x06\x64river\x18\x08 \x01(\t\x12\x0c\n\x04name\x18\t \x01(\t\x12\x0e\n\x06serial\x18\n \x01(\t\x12\x14\n\x0c\x64isplay_mode\x18\x0b \x01(\t\x12\x16\n\x0e\x64isplay_active\x18\x0c \x01(\t\x12\x13\n\x0btemperature\x18\r \x01(\x01\x12H\n\x15\x61\x64\x64itional_properties\x18\x0e \x03(\x0b\x32).proto.DevStats.AdditionalPropertiesEntry\x1a;\n\x19\x41\x64\x64itionalPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x0fZ\rmaistro/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dev_stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rmaistro/proto'
  _globals['_DEVSTATS_ADDITIONALPROPERTIESENTRY']._loaded_options = None
  _globals['_DEVSTATS_ADDITIONALPROPERTIESENTRY']._serialized_options = b'8\001'
  _globals['_DEVSTATS']._serialized_start=27
  _globals['_DEVSTATS']._serialized_end=402
  _globals['_DEVSTATS_ADDITIONALPROPERTIESENTRY']._serialized_start=343
  _globals['_DEVSTATS_ADDITIONALPROPERTIESENTRY']._serialized_end=402
# @@protoc_insertion_point(module_scope)
