# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: generate_req.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import model_parameters_pb2 as model__parameters__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12generate_req.proto\x12\x05proto\x1a\x16model_parameters.proto\"\xa3\x02\n\x0bGenerateReq\x12\r\n\x05model\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x0e\n\x06suffix\x18\x03 \x01(\t\x12\x0e\n\x06images\x18\x04 \x03(\t\x12)\n\x06\x66ormat\x18\x05 \x01(\x0b\x32\x19.proto.GenerateReq.Format\x12\'\n\x07options\x18\x06 \x01(\x0b\x32\x16.proto.ModelParameters\x12\x0e\n\x06system\x18\x07 \x01(\t\x12\x10\n\x08template\x18\x08 \x01(\t\x12\x0e\n\x06stream\x18\t \x01(\x08\x12\x0b\n\x03raw\x18\n \x01(\x08\x12\x12\n\nkeep_alive\x18\x0b \x01(\x05\x12\x0f\n\x07\x63ontext\x18\x0c \x01(\t\x12\r\n\x05think\x18\r \x01(\x08\x1a\x0e\n\x06\x46ormatJ\x04\x08\x01\x10\x02\x42\x0fZ\rmaistro/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generate_req_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rmaistro/proto'
  _globals['_GENERATEREQ']._serialized_start=54
  _globals['_GENERATEREQ']._serialized_end=345
  _globals['_GENERATEREQ_FORMAT']._serialized_start=331
  _globals['_GENERATEREQ_FORMAT']._serialized_end=345
# @@protoc_insertion_point(module_scope)
