# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message_type.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'message_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12message_type.proto\x12\x05proto*\xcd\x01\n\x0bMessageType\x12\x1b\n\x17MESSAGETYPE_UNSPECIFIED\x10\x00\x12\x0b\n\x07\x43ONNECT\x10\x01\x12\r\n\tCONNECTED\x10\x02\x12\t\n\x05PAUSE\x10\x03\x12\n\n\x06PAUSED\x10\x04\x12\n\n\x06RESUME\x10\x05\x12\x0b\n\x07RESUMED\x10\x06\x12\n\n\x06\x43\x41NCEL\x10\x07\x12\r\n\tCANCELLED\x10\x08\x12\x0c\n\x08\x43OMPLETE\x10\t\x12\t\n\x05\x45RROR\x10\n\x12\x0b\n\x07WARNING\x10\x0b\x12\x08\n\x04INFO\x10\x0c\x12\n\n\x06\x46\x41ILED\x10\rB\x0fZ\rmaistro/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rmaistro/proto'
  _globals['_MESSAGETYPE']._serialized_start=30
  _globals['_MESSAGETYPE']._serialized_end=235
# @@protoc_insertion_point(module_scope)
