"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
GENERATED CODE - DO NOT EDIT
Generated by schema2code proto generator
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import message_content_type_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class MessageContent(google.protobuf.message.Message):
    """Content of a message in a chat conversation"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TYPE_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    type: message_content_type_pb2.MessageContentType.ValueType
    """Type of the message content (e.g., text, image, tool call)"""
    text: builtins.str
    """Text content of the message, if applicable"""
    url: builtins.str
    """URL of the image or resource, if applicable"""
    def __init__(
        self,
        *,
        type: message_content_type_pb2.MessageContentType.ValueType = ...,
        text: builtins.str = ...,
        url: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["text", b"text", "type", b"type", "url", b"url"]) -> None: ...

global___MessageContent = MessageContent
