# Code generated by schema2code at 2026-02-23 18:50:11. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class WindowConfig(BaseModel):
    """Configuration for window management"""
    max_tokens: Annotated[int, Field(default=8192, description="Maximum tokens per window")]
    """Maximum tokens per window"""
    reserve_tokens: Annotated[int, Field(default=1024, description="Reserved tokens for output")]
    """Reserved tokens for output"""
    overflow_strategy: Annotated[str, Field(default="truncate_oldest", description="Strategy for handling overflow")]
    """Strategy for handling overflow"""

    model_config = ConfigDict(extra="ignore")


class Prioritization(BaseModel):
    """Configuration for context prioritization"""
    priority_order: Annotated[List[str], Field(default_factory=list, description="Order of context priority")]
    """Order of context priority"""
    recent_messages_count: Annotated[int, Field(default=5, description="Number of recent messages to prioritize")]
    """Number of recent messages to prioritize"""
    memory_allocation: Annotated[float, Field(default=0.3, description="Memory allocation ratio")]
    """Memory allocation ratio"""
    summary_allocation: Annotated[float, Field(default=0.2, description="Summary allocation ratio")]
    """Summary allocation ratio"""

    model_config = ConfigDict(extra="ignore")


class Optimization(BaseModel):
    """Configuration for context optimization"""
    enable_compression: Annotated[bool, Field(default=True, description="Enable context compression")]
    """Enable context compression"""
    deduplication: Annotated[bool, Field(default=True, description="Enable deduplication")]
    """Enable deduplication"""
    smart_truncation: Annotated[bool, Field(default=True, description="Enable smart truncation")]
    """Enable smart truncation"""
    cache_optimized_context: Annotated[bool, Field(default=True, description="Enable cache-optimized context")]
    """Enable cache-optimized context"""
    token_counting_method: Annotated[str, Field(default="approximate", description="Method for token counting")]
    """Method for token counting"""

    model_config = ConfigDict(extra="ignore")


class ContextWindowConfig(BaseModel):
    """Configuration for context window management"""
    enabled: Annotated[bool, Field(default=True, description="Enable context window management")]
    """Enable context window management"""
    window_config: Annotated[WindowConfig, Field(default_factory=WindowConfig, description="Window configuration")]
    """Window configuration"""
    prioritization: Annotated[Prioritization, Field(default_factory=Prioritization, description="Prioritization configuration")]
    """Prioritization configuration"""
    optimization: Annotated[Optimization, Field(default_factory=Optimization, description="Optimization configuration")]
    """Optimization configuration"""

    model_config = ConfigDict(extra="ignore")