# Code generated by schema2code at 2026-02-23 18:50:50. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class RefinementConfig(BaseModel):
    """Configuration for response refinement"""
    enable_response_filtering: Annotated[bool, Field(default=True, description="Enable response content filtering")]
    """Enable response content filtering"""
    enable_response_critique: Annotated[bool, Field(default=True, description="Enable response critique and refinement")]
    """Enable response critique and refinement"""

    model_config = ConfigDict(extra="ignore")