# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat_req.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_pb2 as message__pb2
import model_parameters_pb2 as model__parameters__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63hat_req.proto\x12\x05proto\x1a\rmessage.proto\x1a\x16model_parameters.proto\"\xa2\x02\n\x07\x43hatReq\x12\r\n\x05model\x18\x01 \x01(\t\x12 \n\x08messages\x18\x02 \x03(\x0b\x32\x0e.proto.Message\x12\x0e\n\x06stream\x18\x03 \x01(\x08\x12%\n\x06\x66ormat\x18\x04 \x01(\x0b\x32\x15.proto.ChatReq.Format\x12\x17\n\x0f\x63onversation_id\x18\x05 \x01(\x05\x12\x12\n\nkeep_alive\x18\x06 \x01(\x05\x12\'\n\x07options\x18\x07 \x01(\x0b\x32\x16.proto.ModelParameters\x12\'\n\x05tools\x18\x08 \x03(\x0b\x32\x18.proto.ChatReq.ToolsItem\x12\r\n\x05think\x18\t \x01(\x08\x1a\x0e\n\x06\x46ormatJ\x04\x08\x01\x10\x02\x1a\x11\n\tToolsItemJ\x04\x08\x01\x10\x02\x42\x0fZ\rmaistro/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_req_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rmaistro/proto'
  _globals['_CHATREQ']._serialized_start=65
  _globals['_CHATREQ']._serialized_end=355
  _globals['_CHATREQ_FORMAT']._serialized_start=322
  _globals['_CHATREQ_FORMAT']._serialized_end=336
  _globals['_CHATREQ_TOOLSITEM']._serialized_start=338
  _globals['_CHATREQ_TOOLSITEM']._serialized_end=355
# @@protoc_insertion_point(module_scope)
