"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
GENERATED CODE - DO NOT EDIT
Generated by schema2code proto generator
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class DevStats(google.protobuf.message.Message):
    """Schema representing device memory statistics."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class AdditionalPropertiesEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        value: builtins.str
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: builtins.str = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    ID_FIELD_NUMBER: builtins.int
    UUID_FIELD_NUMBER: builtins.int
    GPU_UTIL_FIELD_NUMBER: builtins.int
    MEM_UTIL_FIELD_NUMBER: builtins.int
    MEM_TOTAL_FIELD_NUMBER: builtins.int
    MEM_USED_FIELD_NUMBER: builtins.int
    MEM_FREE_FIELD_NUMBER: builtins.int
    DRIVER_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    SERIAL_FIELD_NUMBER: builtins.int
    DISPLAY_MODE_FIELD_NUMBER: builtins.int
    DISPLAY_ACTIVE_FIELD_NUMBER: builtins.int
    TEMPERATURE_FIELD_NUMBER: builtins.int
    ADDITIONAL_PROPERTIES_FIELD_NUMBER: builtins.int
    id: builtins.str
    """Device identifier."""
    uuid: builtins.str
    """Universally unique identifier for the device."""
    gpu_util: builtins.float
    """GPU utilization percentage."""
    mem_util: builtins.float
    """Memory utilization percentage."""
    mem_total: builtins.float
    """Total memory in megabytes."""
    mem_used: builtins.float
    """Used memory in megabytes."""
    mem_free: builtins.float
    """Free memory in megabytes."""
    driver: builtins.str
    """Driver version."""
    name: builtins.str
    """Device name."""
    serial: builtins.str
    """Device serial number."""
    display_mode: builtins.str
    """Display mode status."""
    display_active: builtins.str
    """Display active status."""
    temperature: builtins.float
    """Device temperature in Celsius."""
    @property
    def additional_properties(self) -> google.protobuf.internal.containers.ScalarMap[builtins.str, builtins.str]:
        """Additional properties as key-value pairs"""

    def __init__(
        self,
        *,
        id: builtins.str = ...,
        uuid: builtins.str = ...,
        gpu_util: builtins.float = ...,
        mem_util: builtins.float = ...,
        mem_total: builtins.float = ...,
        mem_used: builtins.float = ...,
        mem_free: builtins.float = ...,
        driver: builtins.str = ...,
        name: builtins.str = ...,
        serial: builtins.str = ...,
        display_mode: builtins.str = ...,
        display_active: builtins.str = ...,
        temperature: builtins.float = ...,
        additional_properties: collections.abc.Mapping[builtins.str, builtins.str] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["additional_properties", b"additional_properties", "display_active", b"display_active", "display_mode", b"display_mode", "driver", b"driver", "gpu_util", b"gpu_util", "id", b"id", "mem_free", b"mem_free", "mem_total", b"mem_total", "mem_used", b"mem_used", "mem_util", b"mem_util", "name", b"name", "serial", b"serial", "temperature", b"temperature", "uuid", b"uuid"]) -> None: ...

global___DevStats = DevStats
