# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: embedding_response.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x65mbedding_response.proto\x12\x05proto\"\xcb\x01\n\x11\x45mbeddingResponse\x12\r\n\x05model\x18\x01 \x01(\t\x12;\n\nembeddings\x18\x02 \x03(\x0b\x32\'.proto.EmbeddingResponse.EmbeddingsList\x12\x16\n\x0etotal_duration\x18\x03 \x01(\x05\x12\x15\n\rload_duration\x18\x04 \x01(\x05\x12\x19\n\x11prompt_eval_count\x18\x05 \x01(\x05\x1a \n\x0e\x45mbeddingsList\x12\x0e\n\x06values\x18\x01 \x03(\x01\x42\x0fZ\rmaistro/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_response_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rmaistro/proto'
  _globals['_EMBEDDINGRESPONSE']._serialized_start=36
  _globals['_EMBEDDINGRESPONSE']._serialized_end=239
  _globals['_EMBEDDINGRESPONSE_EMBEDDINGSLIST']._serialized_start=207
  _globals['_EMBEDDINGRESPONSE_EMBEDDINGSLIST']._serialized_end=239
# @@protoc_insertion_point(module_scope)
