"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
GENERATED CODE - DO NOT EDIT
Generated by schema2code proto generator
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ImageGenerateRequest(google.protobuf.message.Message):
    """Request for generating an image"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROMPT_FIELD_NUMBER: builtins.int
    WIDTH_FIELD_NUMBER: builtins.int
    HEIGHT_FIELD_NUMBER: builtins.int
    INFERENCE_STEPS_FIELD_NUMBER: builtins.int
    GUIDANCE_SCALE_FIELD_NUMBER: builtins.int
    LOW_MEMORY_MODE_FIELD_NUMBER: builtins.int
    NEGATIVE_PROMPT_FIELD_NUMBER: builtins.int
    MODEL_FIELD_NUMBER: builtins.int
    LORAS_FIELD_NUMBER: builtins.int
    IMAGE_ID_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    FILENAME_FIELD_NUMBER: builtins.int
    prompt: builtins.str
    """The prompt for image generation"""
    width: builtins.int
    """Width of the generated image"""
    height: builtins.int
    """Height of the generated image"""
    inference_steps: builtins.int
    """Number of inference steps"""
    guidance_scale: builtins.float
    """Guidance scale for image generation"""
    low_memory_mode: builtins.bool
    """Whether to use low memory mode"""
    negative_prompt: builtins.str
    """Negative prompt for image generation"""
    model: builtins.str
    """Model to use for image generation"""
    image_id: builtins.int
    """ID of the image to use as a base for image generation (for img2img)"""
    url: builtins.str
    """URL of the image to use as a base for image generation (for img2img)"""
    filename: builtins.str
    """Name of the file to save the generated image as"""
    @property
    def loras(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.str]:
        """List of LoRA models to apply to the image generation"""

    def __init__(
        self,
        *,
        prompt: builtins.str = ...,
        width: builtins.int = ...,
        height: builtins.int = ...,
        inference_steps: builtins.int = ...,
        guidance_scale: builtins.float = ...,
        low_memory_mode: builtins.bool = ...,
        negative_prompt: builtins.str = ...,
        model: builtins.str = ...,
        loras: collections.abc.Iterable[builtins.str] | None = ...,
        image_id: builtins.int = ...,
        url: builtins.str = ...,
        filename: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["filename", b"filename", "guidance_scale", b"guidance_scale", "height", b"height", "image_id", b"image_id", "inference_steps", b"inference_steps", "loras", b"loras", "low_memory_mode", b"low_memory_mode", "model", b"model", "negative_prompt", b"negative_prompt", "prompt", b"prompt", "url", b"url", "width", b"width"]) -> None: ...

global___ImageGenerateRequest = ImageGenerateRequest
