"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
GENERATED CODE - DO NOT EDIT
Generated by schema2code proto generator
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ImageGenerateResponse(google.protobuf.message.Message):
    """Response from generating an image"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    IMAGE_FIELD_NUMBER: builtins.int
    DOWNLOAD_FIELD_NUMBER: builtins.int
    image: builtins.str
    """Base64-encoded image"""
    download: builtins.str
    """URL to download the image"""
    def __init__(
        self,
        *,
        image: builtins.str = ...,
        download: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["download", b"download", "image", b"image"]) -> None: ...

global___ImageGenerateResponse = ImageGenerateResponse
