# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import chat_req_pb2 as chat__req__pb2
import chat_response_pb2 as chat__response__pb2
import generate_req_pb2 as generate__req__pb2
import embedding_req_pb2 as embedding__req__pb2
import image_generation_request_pb2 as image__generation__request__pb2
import image_generation_response_pb2 as image__generation__response__pb2
import generate_response_pb2 as generate__response__pb2
import embedding_response_pb2 as embedding__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x05proto\x1a\x0e\x63hat_req.proto\x1a\x13\x63hat_response.proto\x1a\x12generate_req.proto\x1a\x13\x65mbedding_req.proto\x1a\x1eimage_generation_request.proto\x1a\x1fimage_generation_response.proto\x1a\x17generate_response.proto\x1a\x18\x65mbedding_response.proto2\x93\x02\n\x10InferenceService\x12\x33\n\nChatStream\x12\x0e.proto.ChatReq\x1a\x13.proto.ChatResponse0\x01\x12?\n\x0eGenerateStream\x12\x12.proto.GenerateReq\x1a\x17.proto.GenerateResponse0\x01\x12=\n\x0cGetEmbedding\x12\x13.proto.EmbeddingReq\x1a\x18.proto.EmbeddingResponse\x12J\n\rGenerateImage\x12\x1b.proto.ImageGenerateRequest\x1a\x1c.proto.ImageGenerateResponseB\x0fZ\rmaistro/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rmaistro/proto'
  _globals['_INFERENCESERVICE']._serialized_start=221
  _globals['_INFERENCESERVICE']._serialized_end=496
# @@protoc_insertion_point(module_scope)
