# Generated stub file for inference.proto.inference_pb2_grpc
# This file helps IDEs recognize protobuf generated types

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar, Iterable, Mapping, Optional, Text, Union, List, Dict, Any, Sequence

class chat__req__pb2(_message.Message):
    DESCRIPTOR: ClassVar[_descriptor.Descriptor]
    def __init__(self, **kwargs) -> None: ...
    def HasField(self, field_name: str) -> bool: ...
    def ClearField(self, field_name: str) -> None: ...

class chat__response__pb2(_message.Message):
    DESCRIPTOR: ClassVar[_descriptor.Descriptor]
    def __init__(self, **kwargs) -> None: ...
    def HasField(self, field_name: str) -> bool: ...
    def ClearField(self, field_name: str) -> None: ...

class embedding__req__pb2(_message.Message):
    DESCRIPTOR: ClassVar[_descriptor.Descriptor]
    def __init__(self, **kwargs) -> None: ...
    def HasField(self, field_name: str) -> bool: ...
    def ClearField(self, field_name: str) -> None: ...

class embedding__response__pb2(_message.Message):
    DESCRIPTOR: ClassVar[_descriptor.Descriptor]
    def __init__(self, **kwargs) -> None: ...
    def HasField(self, field_name: str) -> bool: ...
    def ClearField(self, field_name: str) -> None: ...

class generate__req__pb2(_message.Message):
    DESCRIPTOR: ClassVar[_descriptor.Descriptor]
    def __init__(self, **kwargs) -> None: ...
    def HasField(self, field_name: str) -> bool: ...
    def ClearField(self, field_name: str) -> None: ...

class generate__response__pb2(_message.Message):
    DESCRIPTOR: ClassVar[_descriptor.Descriptor]
    def __init__(self, **kwargs) -> None: ...
    def HasField(self, field_name: str) -> bool: ...
    def ClearField(self, field_name: str) -> None: ...

class image__generation__request__pb2(_message.Message):
    DESCRIPTOR: ClassVar[_descriptor.Descriptor]
    def __init__(self, **kwargs) -> None: ...
    def HasField(self, field_name: str) -> bool: ...
    def ClearField(self, field_name: str) -> None: ...

class image__generation__response__pb2(_message.Message):
    DESCRIPTOR: ClassVar[_descriptor.Descriptor]
    def __init__(self, **kwargs) -> None: ...
    def HasField(self, field_name: str) -> bool: ...
    def ClearField(self, field_name: str) -> None: ...

class InferenceServiceServicer:
    def __init__(self) -> None: ...

class InferenceServiceStub:
    def __init__(self, channel: Any) -> None: ...
