"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
GENERATED CODE - DO NOT EDIT
Generated by schema2code proto generator
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MessageType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MessageTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MessageType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MESSAGETYPE_UNSPECIFIED: _MessageType.ValueType  # 0
    CONNECT: _MessageType.ValueType  # 1
    CONNECTED: _MessageType.ValueType  # 2
    PAUSE: _MessageType.ValueType  # 3
    PAUSED: _MessageType.ValueType  # 4
    RESUME: _MessageType.ValueType  # 5
    RESUMED: _MessageType.ValueType  # 6
    CANCEL: _MessageType.ValueType  # 7
    CANCELLED: _MessageType.ValueType  # 8
    COMPLETE: _MessageType.ValueType  # 9
    ERROR: _MessageType.ValueType  # 10
    WARNING: _MessageType.ValueType  # 11
    INFO: _MessageType.ValueType  # 12
    FAILED: _MessageType.ValueType  # 13

class MessageType(_MessageType, metaclass=_MessageTypeEnumTypeWrapper):
    """Type of message"""

MESSAGETYPE_UNSPECIFIED: MessageType.ValueType  # 0
CONNECT: MessageType.ValueType  # 1
CONNECTED: MessageType.ValueType  # 2
PAUSE: MessageType.ValueType  # 3
PAUSED: MessageType.ValueType  # 4
RESUME: MessageType.ValueType  # 5
RESUMED: MessageType.ValueType  # 6
CANCEL: MessageType.ValueType  # 7
CANCELLED: MessageType.ValueType  # 8
COMPLETE: MessageType.ValueType  # 9
ERROR: MessageType.ValueType  # 10
WARNING: MessageType.ValueType  # 11
INFO: MessageType.ValueType  # 12
FAILED: MessageType.ValueType  # 13
global___MessageType = MessageType
