# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
import message_content_pb2 as message__content__pb2
import message_role_pb2 as message__role__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15message_content.proto\x1a\x12message_role.proto\"\x83\x02\n\x07Message\x12 \n\x04role\x18\x01 \x01(\x0e\x32\x12.proto.MessageRole\x12&\n\x07\x63ontent\x18\x02 \x03(\x0b\x32\x15.proto.MessageContent\x12\x30\n\ntool_calls\x18\x03 \x03(\x0b\x32\x1c.proto.Message.ToolCallsItem\x12\x10\n\x08thinking\x18\x04 \x01(\t\x12\n\n\x02id\x18\x05 \x01(\x05\x12.\n\ncreated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0f\x63onversation_id\x18\x07 \x01(\x05\x1a\x15\n\rToolCallsItemJ\x04\x08\x01\x10\x02\x42\x0fZ\rmaistro/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\rmaistro/proto'
  _globals['_MESSAGE']._serialized_start=101
  _globals['_MESSAGE']._serialized_end=360
  _globals['_MESSAGE_TOOLCALLSITEM']._serialized_start=339
  _globals['_MESSAGE_TOOLCALLSITEM']._serialized_end=360
# @@protoc_insertion_point(module_scope)
