"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
GENERATED CODE - DO NOT EDIT
Generated by schema2code proto generator
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MessageRole:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MessageRoleEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MessageRole.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MESSAGEROLE_UNSPECIFIED: _MessageRole.ValueType  # 0
    USER: _MessageRole.ValueType  # 1
    ASSISTANT: _MessageRole.ValueType  # 2
    SYSTEM: _MessageRole.ValueType  # 3
    TOOL: _MessageRole.ValueType  # 4
    AGENT: _MessageRole.ValueType  # 5
    OBSERVER: _MessageRole.ValueType  # 6

class MessageRole(_MessageRole, metaclass=_MessageRoleEnumTypeWrapper):
    """Role of a participant in a chat conversation"""

MESSAGEROLE_UNSPECIFIED: MessageRole.ValueType  # 0
USER: MessageRole.ValueType  # 1
ASSISTANT: MessageRole.ValueType  # 2
SYSTEM: MessageRole.ValueType  # 3
TOOL: MessageRole.ValueType  # 4
AGENT: MessageRole.ValueType  # 5
OBSERVER: MessageRole.ValueType  # 6
global___MessageRole = MessageRole
