"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
GENERATED CODE - DO NOT EDIT
Generated by schema2code proto generator
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import message_content_pb2
import message_role_pb2
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class Message(google.protobuf.message.Message):
    """Message represents a single exchange in the conversation"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class ToolCallsItem(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        def __init__(
            self,
        ) -> None: ...

    ROLE_FIELD_NUMBER: builtins.int
    CONTENT_FIELD_NUMBER: builtins.int
    TOOL_CALLS_FIELD_NUMBER: builtins.int
    THINKING_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    CONVERSATION_ID_FIELD_NUMBER: builtins.int
    role: message_role_pb2.MessageRole.ValueType
    """Role of the message sender (e.g., user, assistant)"""
    thinking: builtins.str
    """Optional thinking process of the model, if applicable"""
    id: builtins.int
    """Unique identifier for the message"""
    conversation_id: builtins.int
    """Id of the conversation this message belongs to"""
    @property
    def content(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[message_content_pb2.MessageContent]:
        """Content of the message"""

    @property
    def tool_calls(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Message.ToolCallsItem]:
        """Optional tool calls associated with the message"""

    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """Timestamp of when the message was created"""

    def __init__(
        self,
        *,
        role: message_role_pb2.MessageRole.ValueType = ...,
        content: collections.abc.Iterable[message_content_pb2.MessageContent] | None = ...,
        tool_calls: collections.abc.Iterable[global___Message.ToolCallsItem] | None = ...,
        thinking: builtins.str = ...,
        id: builtins.int = ...,
        created_at: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        conversation_id: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_at", b"created_at"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["content", b"content", "conversation_id", b"conversation_id", "created_at", b"created_at", "id", b"id", "role", b"role", "thinking", b"thinking", "tool_calls", b"tool_calls"]) -> None: ...

global___Message = Message
