"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
GENERATED CODE - DO NOT EDIT
Generated by schema2code proto generator
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.internal.enum_type_wrapper
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MessageContentType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MessageContentTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MessageContentType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MESSAGECONTENTTYPE_UNSPECIFIED: _MessageContentType.ValueType  # 0
    TEXT: _MessageContentType.ValueType  # 1
    IMAGE: _MessageContentType.ValueType  # 2
    TOOL_CALL: _MessageContentType.ValueType  # 3
    IMAGE_GENERATION: _MessageContentType.ValueType  # 4
    AUDIO: _MessageContentType.ValueType  # 5
    VIDEO: _MessageContentType.ValueType  # 6
    IMAGE_EDIT: _MessageContentType.ValueType  # 7
    FILE: _MessageContentType.ValueType  # 8

class MessageContentType(_MessageContentType, metaclass=_MessageContentTypeEnumTypeWrapper):
    """Type of content in a message"""

MESSAGECONTENTTYPE_UNSPECIFIED: MessageContentType.ValueType  # 0
TEXT: MessageContentType.ValueType  # 1
IMAGE: MessageContentType.ValueType  # 2
TOOL_CALL: MessageContentType.ValueType  # 3
IMAGE_GENERATION: MessageContentType.ValueType  # 4
AUDIO: MessageContentType.ValueType  # 5
VIDEO: MessageContentType.ValueType  # 6
IMAGE_EDIT: MessageContentType.ValueType  # 7
FILE: MessageContentType.ValueType  # 8
global___MessageContentType = MessageContentType
