# Code generated by schema2code at 2026-02-23 18:50:09. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class CircuitBreakerConfig(BaseModel):
    """Circuit breaker configuration for fail-safe operations"""
    base_timeout: Annotated[float, Field(..., description="Base timeout in seconds")]
    """Base timeout in seconds"""
    deep_research_timeout: Annotated[float, Field(..., description="Timeout for deep research operations")]
    """Timeout for deep research operations"""
    max_retries: Annotated[int, Field(..., description="Maximum number of retry attempts")]
    """Maximum number of retry attempts"""
    cooldown_period: Annotated[float, Field(..., description="Cooldown period after circuit opens")]
    """Cooldown period after circuit opens"""
    enable_perplexity_guard: Annotated[bool, Field(default=False, description="Enable perplexity-based guardrails")]
    """Enable perplexity-based guardrails"""
    perplexity_window: Annotated[int, Field(default=40, description="Window size for perplexity calculation")]
    """Window size for perplexity calculation"""
    perplexity_threshold: Annotated[float, Field(default=10.0, description="Perplexity threshold for triggering guardrails")]
    """Perplexity threshold for triggering guardrails"""
    avg_logprob_floor: Annotated[float, Field(default=-6.0, description="Average logprob floor")]
    """Average logprob floor"""
    enable_repetition_detection: Annotated[bool, Field(default=False, description="Enable repetition detection")]
    """Enable repetition detection"""
    repetition_ngram: Annotated[int, Field(default=6, description="N-gram size for repetition detection")]
    """N-gram size for repetition detection"""
    repetition_threshold: Annotated[int, Field(default=6, description="Repetition threshold")]
    """Repetition threshold"""
    min_tokens_for_eval: Annotated[int, Field(default=20, description="Minimum tokens for evaluation")]
    """Minimum tokens for evaluation"""
    perplexity_log_interval_tokens: Annotated[int, Field(default=20, description="Interval for perplexity logging")]
    """Interval for perplexity logging"""
    log_repetition_events: Annotated[bool, Field(default=True, description="Log repetition events")]
    """Log repetition events"""
    tool_gen_repetition_ngram: Annotated[int, Field(default=4, description="N-gram size for tool generation repetition detection")]
    """N-gram size for tool generation repetition detection"""
    tool_gen_repetition_threshold: Annotated[int, Field(default=3, description="Repetition threshold for tool generation")]
    """Repetition threshold for tool generation"""

    model_config = ConfigDict(extra="ignore")