# Code generated by schema2code at 2026-02-23 18:50:12. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ComputationalRequirement(BaseModel):
    """Computational requirement for a task"""
    min_memory_mb: Annotated[int, Field(..., description="Minimum required memory in MB")]
    """Minimum required memory in MB"""
    min_gpu_layers: Annotated[int, Field(default=0, description="Minimum required GPU layers")]
    """Minimum required GPU layers"""
    estimated_time_seconds: Annotated[Optional[float], Field(default=None, description="Estimated execution time in seconds")] = None
    """Estimated execution time in seconds"""

    model_config = ConfigDict(extra="ignore")