# Code generated by schema2code at 2026-02-23 18:50:10. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class CrashPrevention(BaseModel):
    """Configuration for preventing crashes during model execution"""
    enable_preallocation_test: Annotated[bool, Field(default=False, description="Enable preallocation test before model loading")]
    """Enable preallocation test before model loading"""
    memory_buffer_mb: Annotated[int, Field(default=4096, description="Memory buffer in MB")]
    """Memory buffer in MB"""
    timeout_seconds: Annotated[int, Field(default=120, description="Timeout in seconds")]
    """Timeout in seconds"""
    enable_graceful_degradation: Annotated[bool, Field(default=False, description="Enable graceful degradation on memory pressure")]
    """Enable graceful degradation on memory pressure"""

    model_config = ConfigDict(extra="ignore")