# Code generated by schema2code at 2026-02-23 18:50:14. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class EventStreamConfig(BaseModel):
    """Configuration for event streaming"""
    enabled: Annotated[bool, Field(default=True, description="Enable event streaming")]
    """Enable event streaming"""
    buffer_size: Annotated[int, Field(default=1000, description="Buffer size for events")]
    """Buffer size for events"""
    flush_interval_ms: Annotated[int, Field(default=100, description="Flush interval in milliseconds")]
    """Flush interval in milliseconds"""
    max_events_per_batch: Annotated[int, Field(default=100, description="Maximum events per batch")]
    """Maximum events per batch"""
    enable_compression: Annotated[bool, Field(default=True, description="Enable event compression")]
    """Enable event compression"""

    model_config = ConfigDict(extra="ignore")