# Code generated by schema2code at 2026-02-23 18:50:19. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ImageGenerationConfig(BaseModel):
    """Configuration for image generation"""
    enabled: Annotated[bool, Field(default=True, description="Enable image generation")]
    """Enable image generation"""
    storage_directory: Annotated[str, Field(default="images", description="Directory for storing generated images")]
    """Directory for storing generated images"""
    max_image_size: Annotated[int, Field(default=2048, description="Maximum image size in pixels")]
    """Maximum image size in pixels"""
    retention_hours: Annotated[int, Field(default=72, description="Image retention period in hours")]
    """Image retention period in hours"""
    auto_prompt_refinement: Annotated[bool, Field(default=True, description="Enable automatic prompt refinement")]
    """Enable automatic prompt refinement"""
    width: Annotated[int, Field(default=1024, description="Generated image width")]
    """Generated image width"""
    height: Annotated[int, Field(default=1024, description="Generated image height")]
    """Generated image height"""
    inference_steps: Annotated[int, Field(default=50, description="Number of inference steps")]
    """Number of inference steps"""
    guidance_scale: Annotated[float, Field(default=7.5, description="Guidance scale for generation")]
    """Guidance scale for generation"""
    low_memory_mode: Annotated[bool, Field(default=False, description="Enable low memory mode")]
    """Low memory mode for generation"""
    negative_prompt: Annotated[str, Field(default="blurry, distorted, low quality, pixelated", description="Negative prompt for generation")]
    """Negative prompt for generation"""

    model_config = ConfigDict(extra="ignore")