# Code generated by schema2code at 2026-02-23 18:50:35. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .message_role import MessageRole
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class MemoryFragment(BaseModel):
    """A fragment of memory content"""
    role: Annotated[MessageRole, Field(..., description="Role of the participant")]
    """Role of the participant"""
    content: Annotated[str, Field(..., description="Content of the memory fragment")]
    """Content of the memory fragment"""
    created_at: Annotated[datetime, Field(..., description="Timestamp when the fragment was created")]
    """Timestamp when the fragment was created"""

    model_config = ConfigDict(extra="ignore")