# Code generated by schema2code at 2026-02-23 18:50:46. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ModelProfileConfig(BaseModel):
    """Configuration for model profiles"""
    primary_profile_id: Annotated[str, Field(..., description="Primary model profile ID")]
    """Primary model profile ID"""
    summarization_profile_id: Annotated[str, Field(..., description="Summarization model profile ID")]
    """Summarization model profile ID"""
    master_summary_profile_id: Annotated[str, Field(..., description="Master summary model profile ID")]
    """Master summary model profile ID"""
    brief_summary_profile_id: Annotated[str, Field(..., description="Brief summary model profile ID")]
    """Brief summary model profile ID"""
    key_points_profile_id: Annotated[str, Field(..., description="Key points model profile ID")]
    """Key points model profile ID"""
    self_critique_profile_id: Annotated[str, Field(..., description="Self critique model profile ID")]
    """Self critique model profile ID"""
    improvement_profile_id: Annotated[str, Field(..., description="Improvement model profile ID")]
    """Improvement model profile ID"""
    memory_retrieval_profile_id: Annotated[str, Field(..., description="Memory retrieval model profile ID")]
    """Memory retrieval model profile ID"""
    analysis_profile_id: Annotated[str, Field(..., description="Analysis model profile ID")]
    """Analysis model profile ID"""
    research_task_profile_id: Annotated[str, Field(..., description="Research task model profile ID")]
    """Research task model profile ID"""
    research_plan_profile_id: Annotated[str, Field(..., description="Research plan model profile ID")]
    """Research plan model profile ID"""
    research_consolidation_profile_id: Annotated[str, Field(..., description="Research consolidation model profile ID")]
    """Research consolidation model profile ID"""
    research_analysis_profile_id: Annotated[str, Field(..., description="Research analysis model profile ID")]
    """Research analysis model profile ID"""
    embedding_profile_id: Annotated[str, Field(..., description="Embedding model profile ID")]
    """Embedding model profile ID"""
    formatting_profile_id: Annotated[str, Field(..., description="Formatting model profile ID")]
    """Formatting model profile ID"""
    image_generation_prompt_profile_id: Annotated[str, Field(..., description="Image generation prompt model profile ID")]
    """Image generation prompt model profile ID"""
    image_generation_profile_id: Annotated[str, Field(..., description="Image generation model profile ID")]
    """Image generation model profile ID"""
    engineering_profile_id: Annotated[str, Field(..., description="Engineering model profile ID")]
    """Engineering model profile ID"""
    reranking_profile_id: Annotated[str, Field(..., description="Reranking model profile ID")]
    """Reranking model profile ID"""

    model_config = ConfigDict(extra="ignore")