# Code generated by schema2code at 2026-02-23 18:50:48. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat

from .crash_prevention import CrashPrevention
from .performance_parameter import PerformanceParameter


class ParameterOptimizationConfig(BaseModel):
    """Configuration for parameter optimization"""

    enabled: Annotated[
        bool, Field(default=False, description="Enable parameter optimization")
    ]
    """Enable parameter optimization"""
    parameters: Annotated[
        List[PerformanceParameter],
        Field(default_factory=list, description="List of parameters to optimize"),
    ]
    """List of parameters to optimize"""
    crash_prevention: Annotated[
        CrashPrevention,
        Field(
            default_factory=CrashPrevention,
            description="Crash prevention configuration",
        ),
    ]
    """Crash prevention configuration"""

    model_config = ConfigDict(extra="ignore")
