# Code generated by schema2code at 2026-02-23 18:51:01. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class RequiredCapability(BaseModel):
    """Required capability for a task"""
    name: Annotated[str, Field(..., description="Name of the capability")]
    """Name of the capability"""
    level: Annotated[int, Field(..., description="Required level")]
    """Required level"""
    description: Annotated[Optional[str], Field(default=None, description="Description of the capability")] = None
    """Description of the capability"""

    model_config = ConfigDict(extra="ignore")