# Code generated by schema2code at 2026-02-23 18:51:03. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ResourceUsage(BaseModel):
    """Resource usage metrics"""
    cpu_percent: Annotated[Optional[float], Field(default=None, description="CPU usage percentage")] = None
    """CPU usage percentage"""
    memory_mb: Annotated[Optional[float], Field(default=None, description="Memory usage in MB")] = None
    """Memory usage in MB"""
    gpu_percent: Annotated[Optional[float], Field(default=None, description="GPU usage percentage")] = None
    """GPU usage percentage"""
    gpu_memory_mb: Annotated[Optional[float], Field(default=None, description="GPU memory usage in MB")] = None
    """GPU memory usage in MB"""
    timestamp: Annotated[datetime, Field(..., description="Timestamp of measurement")]
    """Timestamp of measurement"""

    model_config = ConfigDict(extra="ignore")