# Code generated by schema2code at 2026-02-23 18:51:10. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class SummarizationConfig(BaseModel):
    """Configuration for summarization"""
    enabled: Annotated[bool, Field(default=True, description="Enable summarization")]
    """Enable summarization"""
    messages_before_summary: Annotated[int, Field(default=10, description="Number of messages before summarization")]
    """Number of messages before summarization"""
    summaries_before_consolidation: Annotated[int, Field(default=3, description="Number of summaries before consolidation")]
    """Number of summaries before consolidation"""
    embedding_dimension: Annotated[int, Field(default=1536, description="Embedding dimension for similarity calculation")]
    """Embedding dimension for similarity calculation"""
    max_summary_levels: Annotated[int, Field(default=3, description="Maximum number of summary levels")]
    """Maximum number of summary levels"""
    summary_weight_coefficient: Annotated[float, Field(default=0.5, description="Weight coefficient for summary importance")]
    """Weight coefficient for summary importance"""

    model_config = ConfigDict(extra="ignore")