# Code generated by schema2code at 2026-02-23 18:51:14. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class TodoItem(BaseModel):
    """A todo item"""
    id: Annotated[Optional[int], Field(default=None, description="Unique identifier")] = None
    """Unique identifier"""
    title: Annotated[str, Field(..., description="Title of the todo item")]
    """Title of the todo item"""
    description: Annotated[Optional[str], Field(default=None, description="Description of the todo item")] = None
    """Description of the todo item"""
    completed: Annotated[bool, Field(default=False, description="Whether the todo item is completed")]
    """Whether the todo item is completed"""
    created_at: Annotated[Optional[datetime], Field(default=None, description="Timestamp of creation")] = None
    """Timestamp of creation"""
    due_at: Annotated[Optional[datetime], Field(default=None, description="Due date")] = None
    """Due date"""

    model_config = ConfigDict(extra="ignore")