# Code generated by schema2code at 2026-02-23 18:51:17. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class WebSearchConfig(BaseModel):
    """Configuration for web search functionality"""
    enabled: Annotated[bool, Field(default=True, description="Enable web search")]
    """Enable web search"""
    auto_detect: Annotated[bool, Field(default=True, description="Enable automatic search trigger detection")]
    """Enable automatic search trigger detection"""
    max_results: Annotated[int, Field(default=5, description="Maximum search results to return")]
    """Maximum search results to return"""
    include_results: Annotated[bool, Field(default=True, description="Include search results in response")]
    """Include search results in response"""
    max_urls_deep: Annotated[int, Field(default=3, description="Maximum depth for URL crawling")]
    """Maximum depth for URL crawling"""
    engines: Annotated[List[str], Field(default_factory=lambda: ["google", "bing", "duckduckgo", "startpage"], description="Search engines to use")]
    """Search engines to use"""
    categories: Annotated[List[str], Field(default_factory=list, description="Search categories")]
    """Search categories"""
    language: Annotated[str, Field(default="en", description="Search language")]
    """Search language"""
    safesearch: Annotated[int, Field(default=1, description="Safe search level (0=off, 1=moderate, 2=strict)")]
    """Safe search level (0=off, 1=moderate, 2=strict)"""
    time_range: Annotated[str, Field(default="", description="Time range for search results")]
    """Time range for search results"""
    searx_host: Annotated[str, Field(default="", description="SearxNG host URL")]
    """SearxNG host URL"""
    timeout: Annotated[float, Field(default=30.0, description="Search timeout in seconds")]
    """Search timeout in seconds"""
    user_agent: Annotated[str, Field(default="LLMMLLab-WebSearch/1.0", description="User agent for search requests")]
    """User agent for search requests"""
    enable_caching: Annotated[bool, Field(default=True, description="Enable search result caching")]
    """Enable search result caching"""
    cache_ttl: Annotated[int, Field(default=300, description="Cache TTL in seconds")]
    """Cache TTL in seconds"""

    model_config = ConfigDict(extra="ignore")