# Code generated by schema2code at 2026-01-21 18:11:20. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ApiKeyResponse(BaseModel):
    """Response when creating an API key (includes plaintext key once)"""
    id: str = Field(..., description="Unique identifier (UUID)")
    """Unique identifier (UUID)"""
    user_id: str = Field(..., description="User ID that owns this key")
    """User ID that owns this key"""
    key: str = Field(..., description="The actual API key (returned only on creation, never stored plaintext)")
    """The actual API key (returned only on creation, never stored plaintext)"""
    name: str = Field(..., description="Human-readable name for this key")
    """Human-readable name for this key"""
    created_at: datetime = Field(..., description="When the key was created")
    """When the key was created"""
    expires_at: Optional[datetime] = Field(default=None, description="When the key expires (null = never)")
    """When the key expires (null = never)"""
    scopes: List[str] = Field(..., description="API scopes this key has access to (e.g., 'chat', 'generate', 'embed')")
    """API scopes this key has access to (e.g., 'chat', 'generate', 'embed')"""

    class Config:
        extra = "ignore"