# Code generated by schema2code at 2026-01-21 18:11:20. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ApiKey(BaseModel):
    """API key for IDE and external service integration"""
    id: str = Field(..., description="Unique identifier (UUID)")
    """Unique identifier (UUID)"""
    user_id: str = Field(..., description="User ID that owns this key")
    """User ID that owns this key"""
    key_hash: str = Field(..., description="SHA-256 hash of the actual API key (never store plaintext)")
    """SHA-256 hash of the actual API key (never store plaintext)"""
    name: str = Field(..., description="Human-readable name for this key")
    """Human-readable name for this key"""
    created_at: datetime = Field(..., description="When the key was created")
    """When the key was created"""
    last_used_at: Optional[datetime] = Field(default=None, description="When the key was last used")
    """When the key was last used"""
    expires_at: Optional[datetime] = Field(default=None, description="When the key expires (null = never)")
    """When the key expires (null = never)"""
    is_revoked: Optional[bool] = Field(default=None, description="Whether this key has been revoked")
    """Whether this key has been revoked"""
    scopes: List[str] = Field(..., description="API scopes this key has access to (e.g., 'chat', 'generate', 'embed')")
    """API scopes this key has access to (e.g., 'chat', 'generate', 'embed')"""

    class Config:
        extra = "ignore"