# Code generated by schema2code at 2025-08-19 15:55:21. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""Authentication configuration"""
class AuthConfig(BaseModel):
    # JWKS URI
    jwks_uri: str = Field(..., description="JWKS URI")
    # Audience
    audience: str = Field(..., description="Audience")
    # Client ID
    client_id: str = Field(..., description="Client ID")
    # Client secret
    client_secret: str = Field(..., description="Client secret")

    class Config:
        extra = "ignore"