# Code generated by schema2code at 2025-10-30 18:03:41. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .complexity_level import ComplexityLevel
from .computational_requirement import ComputationalRequirement
from .model_profile_type import ModelProfileType
from .required_capability import RequiredCapability
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class CapabilityProfileMapping(BaseModel):
    """Mapping from required capabilities to appropriate model profile types"""
    capability: Annotated[RequiredCapability, Field(..., description="The required capability")]
    """The required capability"""
    compatible_profiles: Annotated[List[ModelProfileType], Field(..., description="List of model profile types that can fulfill this capability")]
    """List of model profile types that can fulfill this capability"""
    preferred_profile: Annotated[ModelProfileType, Field(..., description="Preferred model profile type for this capability")]
    """Preferred model profile type for this capability"""
    minimum_complexity_level: Annotated[Optional[ComplexityLevel], Field(default=None, description="Minimum complexity level where this capability mapping applies")] = None
    """Minimum complexity level where this capability mapping applies"""
    computational_requirements: Annotated[Optional[List[ComputationalRequirement]], Field(default=None, description="Computational requirements imposed by this capability")] = None
    """Computational requirements imposed by this capability"""

    class Config:
        extra = "ignore"