# Code generated by schema2code at 2025-07-18 21:27:38. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .message import Message
from .message_role import MessageRole
from .message_content import MessageContent
from .message_content_type import MessageContentType
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""ChatResponse represents a response from the chat API"""
class ChatResponse(BaseModel):
    # Indicates whether the generation is complete
    done: bool
    # The message content and metadata returned by the model
    message: Optional[Message] = None
    # Timestamp when the response was created
    created_at: datetime
    # The name or identifier of the model used for generation
    model: str
    # Array of numbers representing the tokenized context
    context: Optional[List[float]] = None
    # Specific indicator of how or why the generation finished
    finish_reason: Optional[str] = None
    # Total time taken for the entire generation process in milliseconds
    total_duration: Optional[float] = None
    # Time taken to load the model in milliseconds
    load_duration: Optional[float] = None
    # Number of tokens in the prompt that were evaluated
    prompt_eval_count: Optional[float] = None
    # Time taken to evaluate the prompt tokens in milliseconds
    prompt_eval_duration: Optional[float] = None
    # Total number of tokens evaluated
    eval_count: Optional[float] = None
    # Time taken for token evaluation in milliseconds
    eval_duration: Optional[float] = None

    class Config:
        extra = "ignore"