# Code generated by schema2code at 2026-01-21 18:11:21. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .complexity_level import ComplexityLevel
from .computational_requirement import ComputationalRequirement
from .document import Document
from .generation_state import GenerationState
from .intent_analysis import IntentAnalysis
from .message import Message
from .message_content import MessageContent
from .message_content_type import MessageContentType
from .message_role import MessageRole
from .model_profile_type import ModelProfileType
from .node_metadata import NodeMetadata
from .required_capability import RequiredCapability
from .resource_usage import ResourceUsage
from .response_format import ResponseFormat
from .technical_domain import TechnicalDomain
from .thought import Thought
from .todo_item import TodoItem
from .tool_call import ToolCall
from .workflow_type import WorkflowType
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ChatResponse(BaseModel):
    """ChatResponse represents a response from the chat API"""
    done: Optional[bool] = Field(default=True, description="Indicates whether the generation is complete")
    """Indicates whether the generation is complete"""
    message: Optional[Message] = Field(default=None, description="The message content and metadata returned by the model")
    """The message content and metadata returned by the model"""
    created_at: Optional[datetime] = Field(default=None, description="Timestamp when the response was created")
    """Timestamp when the response was created"""
    context: Optional[List[List[float]]] = Field(default=None, description="Vectors representing the tokenized context (embeddings)")
    """Vectors representing the tokenized context (embeddings)"""
    finish_reason: Optional[str] = Field(default=None, description="Specific indicator of how or why the generation finished")
    """Specific indicator of how or why the generation finished"""
    total_duration: Optional[float] = Field(default=None, description="Total time taken for the entire generation process in milliseconds")
    """Total time taken for the entire generation process in milliseconds"""
    load_duration: Optional[float] = Field(default=None, description="Time taken to load the model in milliseconds")
    """Time taken to load the model in milliseconds"""
    prompt_eval_count: Optional[float] = Field(default=None, description="Number of tokens in the prompt that were evaluated")
    """Number of tokens in the prompt that were evaluated"""
    prompt_eval_duration: Optional[float] = Field(default=None, description="Time taken to evaluate the prompt tokens in milliseconds")
    """Time taken to evaluate the prompt tokens in milliseconds"""
    eval_count: Optional[float] = Field(default=None, description="Total number of tokens evaluated")
    """Total number of tokens evaluated"""
    eval_duration: Optional[float] = Field(default=None, description="Time taken for token evaluation in milliseconds")
    """Time taken for token evaluation in milliseconds"""
    processing: Optional[str] = Field(default=None, description="Optional responses generated during message processing")
    """Optional responses generated during message processing"""
    state: Optional[GenerationState] = Field(default=None, description="Optional state information from the model")
    """Optional state information from the model"""
    prev_state: Optional[GenerationState] = Field(default=None, description="Previous state information from the model before the current generation")
    """Previous state information from the model before the current generation"""
    metadata: Optional[NodeMetadata] = Field(default=None, description="Additional metadata about the response")
    """Additional metadata about the response"""
    observer_messages: Optional[List[str]] = Field(default=None, description="OBSERVER role messages that should be displayed as temporary floating notifications")
    """OBSERVER role messages that should be displayed as temporary floating notifications"""
    todos: Optional[List[TodoItem]] = Field(default=None, description="List of TODO items extracted from the response")
    """List of TODO items extracted from the response"""

    class Config:
        extra = "ignore"