# Code generated by schema2code at 2025-10-26 22:52:23. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from typing import Annotated
from .complexity_level import ComplexityLevel
from .computational_requirement import ComputationalRequirement
from .intent_analysis import IntentAnalysis
from .message import Message
from .message_content import MessageContent
from .message_content_type import MessageContentType
from .message_role import MessageRole
from .required_capability import RequiredCapability
from .resource_usage import ResourceUsage
from .response_format import ResponseFormat
from .technical_domain import TechnicalDomain
from .thought import Thought
from .tool_call import ToolCall
from .workflow_type import WorkflowType
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ChatResponse(BaseModel):
    """ChatResponse represents a response from the chat API"""
    done: Annotated[Optional[bool], Field(default=True, description="Indicates whether the generation is complete")]
    """Indicates whether the generation is complete"""
    message: Annotated[Optional[Message], Field(default=None, description="The message content and metadata returned by the model")]
    """The message content and metadata returned by the model"""
    created_at: Annotated[Optional[datetime], Field(default=None, description="Timestamp when the response was created")]
    """Timestamp when the response was created"""
    context: Annotated[Optional[List[List[float]]], Field(default=None, description="Vectors representing the tokenized context (embeddings)")]
    """Vectors representing the tokenized context (embeddings)"""
    finish_reason: Annotated[Optional[str], Field(default=None, description="Specific indicator of how or why the generation finished")]
    """Specific indicator of how or why the generation finished"""
    total_duration: Annotated[Optional[float], Field(default=None, description="Total time taken for the entire generation process in milliseconds")]
    """Total time taken for the entire generation process in milliseconds"""
    load_duration: Annotated[Optional[float], Field(default=None, description="Time taken to load the model in milliseconds")]
    """Time taken to load the model in milliseconds"""
    prompt_eval_count: Annotated[Optional[float], Field(default=None, description="Number of tokens in the prompt that were evaluated")]
    """Number of tokens in the prompt that were evaluated"""
    prompt_eval_duration: Annotated[Optional[float], Field(default=None, description="Time taken to evaluate the prompt tokens in milliseconds")]
    """Time taken to evaluate the prompt tokens in milliseconds"""
    eval_count: Annotated[Optional[float], Field(default=None, description="Total number of tokens evaluated")]
    """Total number of tokens evaluated"""
    eval_duration: Annotated[Optional[float], Field(default=None, description="Time taken for token evaluation in milliseconds")]
    """Time taken for token evaluation in milliseconds"""
    processing: Annotated[Optional[str], Field(default=None, description="Optional responses generated during message processing")]
    """Optional responses generated during message processing"""
    channels: Annotated[Optional[Dict[str, Any]], Field(default=None, description="Additional structured channels extracted from the response (tool calls, status, etc.)")]
    """Additional structured channels extracted from the response (tool calls, status, etc.)"""
    observer_messages: Annotated[Optional[List[str]], Field(default=None, description="OBSERVER role messages that should be displayed as temporary floating notifications")]
    """OBSERVER role messages that should be displayed as temporary floating notifications"""
    analyses: Annotated[Optional[List[IntentAnalysis]], Field(default=None, description="Analytical insights or summaries related to the chat response")]
    """Analytical insights or summaries related to the chat response"""

    class Config:
        extra = "ignore"