# Code generated by schema2code at 2025-09-29 10:09:12. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class ComputationalRequirement(str, Enum):
    """Types of computational requirements that can be imposed by capabilities or analysis"""
    HIGH_MEMORY = 'high_memory'
    GPU_ACCELERATION = 'gpu_acceleration'
    PARALLEL_PROCESSING = 'parallel_processing'
    REAL_TIME_PROCESSING = 'real_time_processing'
    LARGE_DATA_HANDLING = 'large_data_handling'
    COMPLEX_REASONING = 'complex_reasoning'
    MULTI_MODAL_PROCESSING = 'multi_modal_processing'
    EXTERNAL_API_CALLS = 'external_api_calls'
    FILE_OPERATIONS = 'file_operations'
    DATABASE_OPERATIONS = 'database_operations'