# Code generated by schema2code at 2025-09-30 12:13:06. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class RateLimit(BaseModel):
    enabled: bool = Field(default=True)
    requests_per_minute: int = Field(default=60, ge=1, le=1000)

    class Config:
        extra = "ignore"

class HealthCheck(BaseModel):
    enabled: bool = Field(default=True)
    interval_seconds: int = Field(default=30, ge=5, le=300)

    class Config:
        extra = "ignore"

class ComposerServiceConfig(BaseModel):
    """Composer service system configuration (non-user configurable)"""
    host: str = Field(default='0.0.0.0', description="Service host address")
    """Service host address"""
    port: int = Field(default=8001, description="Service port", ge=1024, le=65535)
    """Service port"""
    debug: bool = Field(default=False, description="Enable debug mode")
    """Enable debug mode"""
    reload: bool = Field(default=False, description="Enable auto-reload in development")
    """Enable auto-reload in development"""
    log_level: str = Field(default='INFO', description="Logging level")
    """Logging level"""
    enable_cors: bool = Field(default=True, description="Enable CORS middleware")
    """Enable CORS middleware"""
    cors_origins: List[str] = Field(default_factory=lambda: ['*'], description="Allowed CORS origins")
    """Allowed CORS origins"""
    max_request_size: int = Field(default=10485760, description="Maximum request size in bytes", ge=1048576, le=104857600)
    """Maximum request size in bytes"""
    rate_limit: RateLimit = Field(...)
    health_check: HealthCheck = Field(...)

    class Config:
        extra = "ignore"