# Code generated by schema2code at 2025-09-17 14:04:36. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class ComplexityLevel(str, Enum):
    """Complexity level assessment for requests and operations"""
    TRIVIAL = 'TRIVIAL'
    SIMPLE = 'SIMPLE'
    MODERATE = 'MODERATE'
    COMPLEX = 'COMPLEX'
    SPECIALIZED = 'SPECIALIZED'