# Code generated by schema2code at 2025-08-19 15:55:21. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .auth_config import AuthConfig
from .database_config import DatabaseConfig
from .image_generation_config import ImageGenerationConfig
from .inference_service import InferenceService
from .inference_service_config import InferenceServiceConfig
from .internal_config import InternalConfig
from .memory_config import MemoryConfig
from .model_profile_config import ModelProfileConfig
from .preferences_config import PreferencesConfig
from .rabbitmq_config import RabbitmqConfig
from .redis_config import RedisConfig
from .refinement_config import RefinementConfig
from .server_config import ServerConfig
from .summarization_config import SummarizationConfig
from .web_search_config import WebSearchConfig
from .web_search_providers import WebSearchProviders
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""Application configuration"""
class Config(BaseModel):
    server: ServerConfig
    database: DatabaseConfig
    redis: RedisConfig
    rabbitmq: RabbitmqConfig
    auth: AuthConfig
    inference_services: InferenceServiceConfig
    summarization: SummarizationConfig
    memory: MemoryConfig
    web_search: WebSearchConfig
    preferences: PreferencesConfig
    model_profiles: ModelProfileConfig
    refinement: RefinementConfig
    image_generation: ImageGenerationConfig
    # Log level
    log_level: str = Field(..., description="Log level")
    internal: Optional[InternalConfig] = None

    class Config:
        extra = "ignore"