# Code generated by schema2code at 2025-09-28 20:45:40. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .circuit_breaker_config import CircuitBreakerConfig
from .conversation import Conversation
from .event_stream_config import EventStreamConfig
from .gpu_config import GPUConfig
from .image_generation_config import ImageGenerationConfig
from .image_metadata import ImageMetadata
from .intent import Intent
from .memory_config import MemoryConfig
from .message import Message
from .message_content import MessageContent
from .message_content_type import MessageContentType
from .message_role import MessageRole
from .model_profile_config import ModelProfileConfig
from .preferences_config import PreferencesConfig
from .refinement_config import RefinementConfig
from .summarization_config import SummarizationConfig
from .tool_config import ToolConfig
from .user_config import UserConfig
from .web_search_config import WebSearchConfig
from .web_search_providers import WebSearchProviders
from .workflow_config import WorkflowConfig
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ConversationCtx(BaseModel):
    """Manages context for a conversation, including messages, summaries, and retrieved memories. Provides methods for adding messages, summarizing conversations, and retrieving relevant context.
"""
    messages: List[Message] = Field(..., description="List of messages in the conversation")
    """List of messages in the conversation"""
    notes: List[str] = Field(..., description="List of notes related to the conversation")
    """List of notes related to the conversation"""
    images: List[ImageMetadata] = Field(..., description="List of images associated with the conversation")
    """List of images associated with the conversation"""
    conversation: Conversation = Field(..., description="The conversation object")
    """The conversation object"""
    current_user_message: Optional[Message] = Field(default=None, description="The current message from the user")
    """The current message from the user"""
    intent: Optional[Intent] = Field(default=None, description="The intent detected from the user's message")
    """The intent detected from the user's message"""
    user_config: Optional[UserConfig] = Field(default=None, description="User-specific configuration and preferences")
    """User-specific configuration and preferences"""

    class Config:
        extra = "ignore"