# Code generated by schema2code at 2025-07-18 21:27:39. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""Schema representing device memory statistics."""
class DevStats(BaseModel):
    # Device identifier.
    id: str
    # Universally unique identifier for the device.
    uuid: str
    # GPU utilization percentage.
    gpu_util: float
    # Memory utilization percentage.
    mem_util: float
    # Total memory in megabytes.
    mem_total: float
    # Used memory in megabytes.
    mem_used: float
    # Free memory in megabytes.
    mem_free: float
    # Driver version.
    driver: str
    # Device name.
    name: str
    # Device serial number.
    serial: str
    # Display mode status.
    display_mode: str
    # Display active status.
    display_active: str
    # Device temperature in Celsius.
    temperature: float

    class Config:
        extra = "ignore"