# Code generated by schema2code at 2026-01-21 18:11:21. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class Document(BaseModel):
    """A document/file attachment with metadata and content"""
    id: Optional[int] = Field(default=None, description="Unique identifier for the file attachment")
    """Unique identifier for the file attachment"""
    message_id: int = Field(..., description="ID of the message this attachment belongs to")
    """ID of the message this attachment belongs to"""
    user_id: str = Field(..., description="ID of the user who uploaded this attachment")
    """ID of the user who uploaded this attachment"""
    filename: str = Field(..., description="Original filename of the attachment")
    """Original filename of the attachment"""
    content_type: str = Field(..., description="MIME type of the file")
    """MIME type of the file"""
    file_size: int = Field(..., description="Size of the file in bytes")
    """Size of the file in bytes"""
    content: str = Field(..., description="File content (base64 encoded for binary files, plain text for text files)")
    """File content (base64 encoded for binary files, plain text for text files)"""
    text_content: Optional[str] = Field(default=None, description="Extracted text content for searchability (null for images)")
    """Extracted text content for searchability (null for images)"""
    created_at: datetime = Field(..., description="Timestamp when the attachment was created")
    """Timestamp when the attachment was created"""
    updated_at: Optional[datetime] = Field(default=None, description="Timestamp when the attachment was last updated")
    """Timestamp when the attachment was last updated"""

    class Config:
        extra = "ignore"