# Code generated by schema2code at 2025-08-19 21:10:14. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""Schema for DynamicTool object"""
class DynamicTool(BaseModel):
    # The name of the tool
    name: str = Field(..., description="The name of the tool")
    # Description of what the tool does
    description: str = Field(..., description="Description of what the tool does")
    # The tool's implementation code
    code: str = Field(..., description="The tool's implementation code")
    # The name of the function to be called
    function_name: str = Field(..., description="The name of the function to be called")
    # Parameters for the tool with string values
    parameters: Optional[Dict[str, str]] = Field(default=None, description="Parameters for the tool with string values")

    class Config:
        extra = "ignore"