# Code generated by schema2code at 2025-08-25 18:35:10. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""Schema for DynamicTool object"""
class DynamicTool(BaseModel):
    # The unique identifier for the tool
    id: Optional[int] = Field(default=None, description="The unique identifier for the tool")
    # The unique identifier for the user
    user_id: Any = Field(..., description="The unique identifier for the user")
    # The name of the tool
    name: str = Field(..., description="The name of the tool")
    # Description of what the tool does
    description: str = Field(..., description="Description of what the tool does")
    # The tool's embedding vector
    embedding: Optional[List[float]] = Field(default=None, description="The tool's embedding vector")
    # The tool's implementation code
    code: str = Field(..., description="The tool's implementation code")
    # The name of the function to be called
    function_name: str = Field(..., description="The name of the function to be called")
    # Parameters for the tool with string values
    parameters: Optional[Dict[str, str]] = Field(default=None, description="Parameters for the tool with string values")
    # The timestamp when the tool was created
    created_at: Optional[datetime] = Field(default=None, description="The timestamp when the tool was created")
    # The timestamp when the tool was last updated
    updated_at: Optional[datetime] = Field(default=None, description="The timestamp when the tool was last updated")

    class Config:
        extra = "ignore"