# Code generated by schema2code at 2025-10-26 22:52:25. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from typing import Annotated
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class EmbeddingResponse(BaseModel):
    """Represents the response for an embedding request"""
    model: Annotated[str, Field(...)]
    embeddings: Annotated[List[List[float]], Field(...)]
    total_duration: Annotated[int, Field(...)]
    load_duration: Annotated[int, Field(...)]
    prompt_eval_count: Annotated[int, Field(...)]

    class Config:
        extra = "ignore"