# Code generated by schema2code at 2025-11-04 15:31:04. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class ExecutionState(str, Enum):
    """Enumeration of possible execution states for pipelines"""
    INITIALIZED = 'INITIALIZED'
    RUNNING = 'RUNNING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    TERMINATED = 'TERMINATED'