# Code generated by schema2code at 2026-01-21 18:11:22. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class ExecutionState(str, Enum):
    """Enumeration of possible execution states for pipelines"""
    INITIALIZED = 'INITIALIZED'
    RUNNING = 'RUNNING'
    COMPLETED = 'COMPLETED'
    FAILED = 'FAILED'
    TERMINATED = 'TERMINATED'