# Code generated by schema2code at 2025-12-01 11:47:11. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class GenerationState(str, Enum):
    """Current state of the generation process."""
    ANALYZING = 'analyzing'
    THINKING = 'thinking'
    EXECUTING = 'executing'
    RESPONDING = 'responding'