# Code generated by schema2code at 2025-10-26 22:52:26. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from typing import Annotated
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class GenerateResponse(BaseModel):
    """GenerateResponse represents a request to the Ollama embeddings API"""
    model: Annotated[str, Field(...)]
    created_at: Annotated[Optional[str], Field(default=None)]
    response: Annotated[str, Field(...)]
    done: Annotated[bool, Field(...)]
    done_reason: Annotated[Optional[str], Field(default=None)]
    context: Annotated[Optional[List[int]], Field(default=None, description="context IDs for the response")]
    """context IDs for the response"""
    prompt_eval_count: Annotated[Optional[int], Field(default=None)]
    prompt_eval_duration: Annotated[Optional[float], Field(default=None)]
    eval_count: Annotated[Optional[int], Field(default=None)]
    eval_duration: Annotated[Optional[float], Field(default=None)]
    total_duration: Annotated[Optional[float], Field(default=None)]
    load_duration: Annotated[Optional[float], Field(default=None)]

    class Config:
        extra = "ignore"