# Code generated by schema2code at 2026-01-21 18:11:21. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class GenerationState(str, Enum):
    """Current state of the generation process."""
    ANALYZING = 'analyzing'
    THINKING = 'thinking'
    EXECUTING = 'executing'
    RESPONDING = 'responding'
    FORMATTING = 'formatting'