# Code generated by schema2code at 2025-07-18 21:27:39. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""Response from generating an image"""
class ImageGenerateResponse(BaseModel):
    # Base64-encoded image
    image: str
    # URL to download the image
    download: str

    class Config:
        extra = "ignore"