# Code generated by schema2code at 2025-10-26 22:52:26. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from typing import Annotated
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ImageGenerateResponse(BaseModel):
    """Response from generating an image"""
    image: Annotated[str, Field(..., description="Base64-encoded image")]
    """Base64-encoded image"""
    download: Annotated[str, Field(..., description="URL to download the image")]
    """URL to download the image"""

    class Config:
        extra = "ignore"