# Code generated by schema2code at 2025-06-27 14:38:00. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""Request for generating an image"""
class ImageGenerateRequest(BaseModel):
    # The prompt for image generation
    prompt: str
    # Width of the generated image
    width: Optional[int] = None
    # Height of the generated image
    height: Optional[int] = None
    # Number of inference steps
    inference_steps: Optional[int] = None
    # Guidance scale for image generation
    guidance_scale: Optional[float] = None
    # Whether to use low memory mode
    low_memory_mode: Optional[bool] = None
    # Negative prompt for image generation
    negative_prompt: Optional[str] = None
    # Model to use for image generation
    model: Optional[str] = None
    # List of LoRA models to apply to the image generation
    loras: Optional[List[str]] = None

    class Config:
        extra = "ignore"