# Code generated by schema2code at 2025-09-15 15:05:46. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class InferenceService(BaseModel):
    """Inference service configuration"""
    base_url: str = Field(..., description="Base URL for the inference service")
    """Base URL for the inference service"""

    class Config:
        extra = "ignore"