# Code generated by schema2code at 2025-10-27 09:47:27. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated
from datetime import datetime, date, time, timedelta
from .complexity_level import ComplexityLevel
from .computational_requirement import ComputationalRequirement
from .required_capability import RequiredCapability
from .response_format import ResponseFormat
from .technical_domain import TechnicalDomain
from .workflow_type import WorkflowType
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class IntentAnalysis(BaseModel):
    """Detailed analysis of user intent for smart tool generation"""
    workflow_type: Annotated[WorkflowType, Field(..., description="Primary intent category identified from the user message")]
    """Primary intent category identified from the user message"""
    complexity_level: Annotated[ComplexityLevel, Field(..., description="Assessed complexity level of the request")]
    """Assessed complexity level of the request"""
    required_capabilities: Annotated[List[RequiredCapability], Field(..., description="Set of capabilities required to fulfill the request")]
    """Set of capabilities required to fulfill the request"""
    domain_specificity: Annotated[float, Field(..., description="Domain specificity score (0-1, higher = more domain-specific)", ge=0.0, le=1.0)]
    """Domain specificity score (0-1, higher = more domain-specific)"""
    reusability_potential: Annotated[float, Field(..., description="Reusability potential score (0-1, higher = more reusable)", ge=0.0, le=1.0)]
    """Reusability potential score (0-1, higher = more reusable)"""
    confidence: Annotated[float, Field(..., description="Confidence in the analysis (0-1)", ge=0.0, le=1.0)]
    """Confidence in the analysis (0-1)"""
    response_format: Annotated[Optional[ResponseFormat], Field(default=None, description="Suggested response format for the user")] = None
    """Suggested response format for the user"""
    technical_domain: Annotated[Optional[TechnicalDomain], Field(default=None, description="Identified technical domain if applicable")] = None
    """Identified technical domain if applicable"""
    requires_tools: Annotated[bool, Field(default=False, description="Whether this intent specifically requires tool execution")]
    """Whether this intent specifically requires tool execution"""
    requires_custom_tools: Annotated[bool, Field(default=False, description="Whether this intent requires custom/dynamic tool generation")]
    """Whether this intent requires custom/dynamic tool generation"""
    tool_complexity_score: Annotated[float, Field(..., description="Tool complexity score (0-1, higher = more complex tools needed)", ge=0.0, le=1.0)]
    """Tool complexity score (0-1, higher = more complex tools needed)"""
    computational_requirements: Annotated[ComputationalRequirement, Field(..., description="Computational requirements assessment for the request")]
    """Computational requirements assessment for the request"""

    class Config:
        extra = "ignore"