# Code generated by schema2code at 2025-10-26 22:52:34. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from typing import Annotated
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class Intent(BaseModel):
    """Represents the intent detected from a user's message"""
    web_search: Annotated[Optional[bool], Field(default=None, description="Indicates if the intent involves a web search")]
    """Indicates if the intent involves a web search"""
    memory: Annotated[Optional[bool], Field(default=None, description="Indicates if the intent involves memory retrieval")]
    """Indicates if the intent involves memory retrieval"""
    deep_research: Annotated[Optional[bool], Field(default=None, description="Indicates if the intent involves deep research")]
    """Indicates if the intent involves deep research"""
    image_generation: Annotated[Optional[bool], Field(default=None, description="Indicates if the intent involves image generation")]
    """Indicates if the intent involves image generation"""
    statically_discovered: Annotated[Optional[bool], Field(default=None, description="Indicates if the intent was statically discovered")]
    """Indicates if the intent was statically discovered"""

    class Config:
        extra = "ignore"