# Code generated by schema2code at 2025-07-09 14:22:10. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""LoraWeight contains information about a LoRA weight file"""
class LoraWeight(BaseModel):
    # Unique identifier for the LoRA weight
    id: str
    # Name of the LoRA weight
    name: str
    # Identifier of the parent model this LoRA weight is associated with
    parent_model: str
    # Name of the weight file (e.g., 'lora.safetensors')
    weight_name: Optional[str] = None
    # Name of the adapter (e.g., 'uncensored')
    adapter_name: Optional[str] = None

    class Config:
        extra = "ignore"