# Code generated by schema2code at 2026-01-21 18:11:21. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class MemorySource(str, Enum):
    """Source type for a memory"""
    SUMMARY = 'summary'
    """Memory type for conversation summaries"""
    MESSAGE = 'message'
    """Memory type for conversation messages"""
    SEARCH = 'search'
    """Memory type for search topic syntheses"""
    DOCUMENT = 'document'
    """Memory type for documents and file attachments"""