# Code generated by schema2code at 2025-07-18 21:27:39. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .message_content_type import MessageContentType
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""Content of a message in a chat conversation"""
class MessageContent(BaseModel):
    # Type of the message content (e.g., text, image, tool call)
    type: MessageContentType
    # Text content of the message, if applicable
    text: Optional[str] = None
    # URL of the image or resource, if applicable
    url: Optional[str] = None

    class Config:
        extra = "ignore"