# Code generated by schema2code at 2025-10-27 09:47:30. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated
from datetime import datetime, date, time, timedelta
from .message_content import MessageContent
from .message_content_type import MessageContentType
from .message_role import MessageRole
from .resource_usage import ResourceUsage
from .thought import Thought
from .tool_call import ToolCall
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class Message(BaseModel):
    """Message represents a single exchange in the conversation"""
    role: Annotated[MessageRole, Field(..., description="Role of the message sender (e.g., user, assistant)")]
    """Role of the message sender (e.g., user, assistant)"""
    content: Annotated[List[MessageContent], Field(..., description="Content of the message")]
    """Content of the message"""
    id: Annotated[Optional[int], Field(default=None, description="Unique identifier for the message")] = None
    """Unique identifier for the message"""
    created_at: Annotated[Optional[datetime], Field(default=None, description="Timestamp of when the message was created")] = None
    """Timestamp of when the message was created"""
    conversation_id: Annotated[Optional[int], Field(default=None, description="Unique identifier for the conversation")] = None
    """Unique identifier for the conversation"""
    thoughts: Annotated[Optional[List[Thought]], Field(default=None, description="Array of thoughts or reasoning processes from the assistant")] = None
    """Array of thoughts or reasoning processes from the assistant"""
    tool_calls: Annotated[Optional[List[ToolCall]], Field(default=None, description="Array of tool calls associated with the message")] = None
    """Array of tool calls associated with the message"""

    class Config:
        extra = "ignore"