# Code generated by schema2code at 2025-10-26 22:52:35. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from typing import Annotated
from .message_content_type import MessageContentType
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class MessageContent(BaseModel):
    """Content of a message in a chat conversation"""
    type: Annotated[MessageContentType, Field(..., description="Type of the message content (e.g., text, image, tool call)")]
    """Type of the message content (e.g., text, image, tool call)"""
    text: Annotated[Optional[str], Field(default=None, description="Text content of the message, if applicable")]
    """Text content of the message, if applicable"""
    url: Annotated[Optional[str], Field(default=None, description="URL of the image or resource, if applicable")]
    """URL of the image or resource, if applicable"""

    class Config:
        extra = "ignore"