# Code generated by schema2code at 2025-07-09 14:22:11. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""ModelDetails contains additional information about a model"""
class ModelDetails(BaseModel):
    # Identifier of the parent model if this is a derivative
    parent_model: Optional[str] = None
    # Format of the model file (e.g., gguf)
    format: str
    # Primary model family this belongs to (e.g., llama, phi3)
    family: str
    # All model families this belongs to
    families: List[str]
    # Size of model parameters (e.g., '7.2B')
    parameter_size: str
    # Level of quantization applied to the model (e.g., 'Q4_0')
    quantization_level: Optional[str] = None
    # Data type of the model (e.g., 'float16', 'bfloat16')
    dtype: Optional[str] = None
    # Precision of the model (e.g., 'fp16', 'bf16')
    precision: Optional[str] = None
    # Specialization of the model (e.g., 'LoRA', 'Embedding', 'TextToImage', 'Audio', 'Vision')
    specialization: Optional[str] = None
    # Description of the model
    description: Optional[str] = None
    # Weight of the model (applies to LoRA models)
    weight: Optional[float] = None

    class Config:
        extra = "ignore"