# Code generated by schema2code at 2025-08-05 21:51:08. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""ModelProfileImageSettings represents the image settings for a model profile"""
class ModelProfileImageSettings(BaseModel):
    # Height of the image in pixels
    height: Optional[int] = Field(default=None, description="Height of the image in pixels")
    # Width of the image in pixels
    width: Optional[int] = Field(default=None, description="Width of the image in pixels")
    # Number of inference steps
    inference_steps: Optional[int] = Field(default=None, description="Number of inference steps")
    # Guidance scale for image generation
    guidance_scale: Optional[float] = Field(default=None, description="Guidance scale for image generation")
    # Whether to use low memory mode
    low_memory_mode: Optional[bool] = Field(default=None, description="Whether to use low memory mode")
    # Negative prompt for image generation
    negative_prompt: Optional[str] = Field(default=None, description="Negative prompt for image generation")
    # Name of the LoRA model to use for image generation
    lora_model: Optional[str] = Field(default=None, description="Name of the LoRA model to use for image generation")

    class Config:
        extra = "ignore"