# Code generated by schema2code at 2026-01-21 18:11:22. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ModelDetails(BaseModel):
    """ModelDetails contains additional information about a model"""
    parent_model: Optional[str] = Field(default=None, description="Identifier of the parent model if this is a derivative")
    """Identifier of the parent model if this is a derivative"""
    format: str = Field(..., description="Format of the model file (e.g., gguf)")
    """Format of the model file (e.g., gguf)"""
    gguf_file: Optional[str] = Field(default=None, description="Path to the GGUF file if applicable")
    """Path to the GGUF file if applicable"""
    clip_model_path: Optional[str] = Field(default=None, description="Path to the CLIP model file for multimodal models (e.g., mmproj file)")
    """Path to the CLIP model file for multimodal models (e.g., mmproj file)"""
    family: str = Field(..., description="Primary model family this belongs to (e.g., llama, phi3)")
    """Primary model family this belongs to (e.g., llama, phi3)"""
    families: List[str] = Field(..., description="All model families this belongs to")
    """All model families this belongs to"""
    parameter_size: str = Field(..., description="Size of model parameters (e.g., '7.2B')")
    """Size of model parameters (e.g., '7.2B')"""
    quantization_level: Optional[str] = Field(default=None, description="Level of quantization applied to the model (e.g., 'Q4_0')")
    """Level of quantization applied to the model (e.g., 'Q4_0')"""
    dtype: Optional[str] = Field(default=None, description="Data type of the model (e.g., 'float16', 'bfloat16')")
    """Data type of the model (e.g., 'float16', 'bfloat16')"""
    precision: Optional[str] = Field(default=None, description="Precision of the model (e.g., 'fp16', 'bf16')")
    """Precision of the model (e.g., 'fp16', 'bf16')"""
    specialization: Optional[str] = Field(default=None, description="Specialization of the model (e.g., 'LoRA', 'Embedding', 'TextToImage', 'Audio', 'Vision')")
    """Specialization of the model (e.g., 'LoRA', 'Embedding', 'TextToImage', 'Audio', 'Vision')"""
    description: Optional[str] = Field(default=None, description="Description of the model")
    """Description of the model"""
    weight: Optional[float] = Field(default=None, description="Weight of the model (applies to LoRA models)")
    """Weight of the model (applies to LoRA models)"""
    size: int = Field(..., description="Size of the model in bytes")
    """Size of the model in bytes"""
    original_ctx: int = Field(..., description="Original context window size of the model")
    """Original context window size of the model"""
    n_layers: Optional[int] = Field(default=None, description="Number of layers in the model")
    """Number of layers in the model"""
    hidden_size: Optional[int] = Field(default=None, description="Hidden size of the model")
    """Hidden size of the model"""
    n_heads: Optional[int] = Field(default=None, description="Number of attention heads in the model")
    """Number of attention heads in the model"""
    n_kv_heads: Optional[int] = Field(default=None, description="Number of key-value heads in the model")
    """Number of key-value heads in the model"""
    clip_model_size: Optional[int] = Field(default=None, description="Size of the CLIP model in bytes, if applicable")
    """Size of the CLIP model in bytes, if applicable"""

    class Config:
        extra = "ignore"