# Code generated by schema2code at 2025-07-01 15:06:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .model_details import ModelDetails
from .lora_weight import LoraWeight
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""Model represents a machine learning model used for generating responses"""
class Model(BaseModel):
    # Unique identifier for the model
    id: Optional[str] = None
    # Display name of the model
    name: str
    # Identifier used to reference the model
    model: str
    # Timestamp of when the model was last modified
    modified_at: str
    # Size of the model in bytes
    size: int
    # Hash digest identifying the model version
    digest: str
    # Additional information about the model
    details: ModelDetails
    # Pipeline type used for the model (e.g., "sd3", "sdxl")
    pipeline: Optional[str] = None
    # List of LoRA weights associated with the model
    lora_weights: Optional[List[LoraWeight]] = None

    class Config:
        extra = "ignore"