# Code generated by schema2code at 2025-06-11 16:13:32. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""ModelDetails contains additional information about a model"""
class ModelDetails(BaseModel):
    # Identifier of the parent model if this is a derivative
    parent_model: str
    # Format of the model file (e.g., gguf)
    format: str
    # Primary model family this belongs to (e.g., llama, phi3)
    family: str
    # All model families this belongs to
    families: List[str]
    # Size of model parameters (e.g., '7.2B')
    parameter_size: str
    # Level of quantization applied to the model (e.g., 'Q4_0')
    quantization_level: str

    class Config:
        extra = "ignore"