# Code generated by schema2code at 2025-09-14 21:38:46. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class GPUConfig(BaseModel):
    """Configuration for GPU memory management and device allocation"""
    no_kv_offload: Optional[bool] = Field(default=False, description="Force KV cache to CPU instead of GPU (saves VRAM)")
    """Force KV cache to CPU instead of GPU (saves VRAM)"""
    main_gpu: Optional[int] = Field(default=-1, description="Main GPU device index (-1 for auto-selection)", ge=-1)
    """Main GPU device index (-1 for auto-selection)"""
    main_gpu_device_id: Optional[str] = Field(default=None, description="Device ID/name for main GPU (overrides main_gpu index)")
    """Device ID/name for main GPU (overrides main_gpu index)"""
    tensor_split: Optional[List[float]] = Field(default=None, description="Fraction of model to put on each GPU (must sum to 1.0)")
    """Fraction of model to put on each GPU (must sum to 1.0)"""
    tensor_split_devices: Optional[List[str]] = Field(default=None, description="Device IDs/names corresponding to tensor_split fractions")
    """Device IDs/names corresponding to tensor_split fractions"""
    n_cpu_moe: Optional[int] = Field(default=0, description="Number of MoE layers to keep on CPU (gpt-oss models only)", ge=0)
    """Number of MoE layers to keep on CPU (gpt-oss models only)"""
    split_mode: Optional[str] = Field(default='layer', description="How to split model across devices")
    """How to split model across devices"""
    offload_kqv: Optional[bool] = Field(default=True, description="Offload key/query/value tensors to GPU (opposite of no_kv_offload)")
    """Offload key/query/value tensors to GPU (opposite of no_kv_offload)"""

    class Config:
        extra = "ignore"

class ModelParameters(BaseModel):
    """Parameters for configuring a language model"""
    num_ctx: Optional[int] = Field(default=None, description="Size of the context window")
    """Size of the context window"""
    repeat_last_n: Optional[int] = Field(default=None, description="Number of tokens to consider for repetition penalties")
    """Number of tokens to consider for repetition penalties"""
    repeat_penalty: Optional[float] = Field(default=None, description="Penalty for repetitions")
    """Penalty for repetitions"""
    temperature: Optional[float] = Field(default=None, description="Sampling temperature; higher values produce more creative outputs")
    """Sampling temperature; higher values produce more creative outputs"""
    seed: Optional[int] = Field(default=None, description="Random seed for reproducibility")
    """Random seed for reproducibility"""
    stop: Optional[List[str]] = Field(default=None, description="Sequences where the model should stop generating")
    """Sequences where the model should stop generating"""
    num_predict: Optional[int] = Field(default=None, description="Maximum number of tokens to predict")
    """Maximum number of tokens to predict"""
    top_k: Optional[int] = Field(default=None, description="Limits next token selection to top K options")
    """Limits next token selection to top K options"""
    top_p: Optional[float] = Field(default=None, description="Limits next token selection to tokens comprising the top P probability mass (nucleus sampling)")
    """Limits next token selection to tokens comprising the top P probability mass (nucleus sampling)"""
    min_p: Optional[float] = Field(default=None, description="Minimum probability threshold for token selection")
    """Minimum probability threshold for token selection"""
    think: Optional[bool] = Field(default=None, description="Whether to enable \"thinking\" mode for the model")
    """Whether to enable \"thinking\" mode for the model"""
    max_tokens: Optional[int] = Field(default=None, description="Maximum number of tokens to generate in a single response")
    """Maximum number of tokens to generate in a single response"""
    n_parts: Optional[int] = Field(default=None, description="Number of parts to split the model into. -1 means auto.")
    """Number of parts to split the model into. -1 means auto."""
    batch_size: Optional[int] = Field(default=None, description="Batch size for processing inputs")
    """Batch size for processing inputs"""
    gpu_config: Optional[GPUConfig] = Field(default=None, description="GPU configuration settings for memory management and device allocation")
    """GPU configuration settings for memory management and device allocation"""

    class Config:
        extra = "ignore"