# Code generated by schema2code at 2025-09-17 14:04:49. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .circuit_breaker_config import CircuitBreakerConfig
from .gpu_config import GPUConfig
from .model_parameters import ModelParameters
from .model_profile_image_settings import ModelProfileImageSettings
import uuid
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class GPUConfig(BaseModel):
    """Configuration for GPU memory management and device allocation"""
    no_kv_offload: Optional[bool] = Field(default=False, description="Force KV cache to CPU instead of GPU (saves VRAM)")
    """Force KV cache to CPU instead of GPU (saves VRAM)"""
    main_gpu: Optional[int] = Field(default=-1, description="Main GPU device index (-1 for auto-selection)", ge=-1)
    """Main GPU device index (-1 for auto-selection)"""
    main_gpu_device_id: Optional[str] = Field(default=None, description="Device ID/name for main GPU (overrides main_gpu index)")
    """Device ID/name for main GPU (overrides main_gpu index)"""
    tensor_split: Optional[List[float]] = Field(default=None, description="Fraction of model to put on each GPU (must sum to 1.0)")
    """Fraction of model to put on each GPU (must sum to 1.0)"""
    tensor_split_devices: Optional[List[str]] = Field(default=None, description="Device IDs/names corresponding to tensor_split fractions")
    """Device IDs/names corresponding to tensor_split fractions"""
    split_mode: Optional[str] = Field(default='layer', description="How to split model across devices")
    """How to split model across devices"""
    offload_kqv: Optional[bool] = Field(default=True, description="Offload key/query/value tensors to GPU (opposite of no_kv_offload)")
    """Offload key/query/value tensors to GPU (opposite of no_kv_offload)"""

    class Config:
        extra = "ignore"

class ModelProfile(BaseModel):
    """ModelProfile represents a model profile used for generating responses"""
    id: Optional[uuid.UUID] = Field(default=None, description="Unique identifier for the profile")
    """Unique identifier for the profile"""
    user_id: str = Field(..., description="Id of the user who owns the profile")
    """Id of the user who owns the profile"""
    name: str = Field(..., description="Name of the profile")
    """Name of the profile"""
    description: Optional[str] = Field(default=None, description="Description of the profile")
    """Description of the profile"""
    model_name: str = Field(..., description="Name of the model to use")
    """Name of the model to use"""
    parameters: ModelParameters = Field(..., description="Parameters for configuring the model")
    """Parameters for configuring the model"""
    system_prompt: str = Field(..., description="System prompt to send to the model")
    """System prompt to send to the model"""
    created_at: Optional[datetime] = Field(default=None, description="Timestamp of when the profile was created")
    """Timestamp of when the profile was created"""
    updated_at: Optional[datetime] = Field(default=None, description="Timestamp of when the profile was last updated")
    """Timestamp of when the profile was last updated"""
    model_version: Optional[str] = Field(default=None, description="Version of the model")
    """Version of the model"""
    type: int = Field(..., description="Type of the model profile")
    """Type of the model profile"""
    image_settings: Optional[ModelProfileImageSettings] = Field(default=None, description="Image settings for the model profile")
    """Image settings for the model profile"""
    think: Optional[bool] = Field(default=None, description="Whether to use think mode for the model profile")
    """Whether to use think mode for the model profile"""
    circuit_breaker: Optional[CircuitBreakerConfig] = Field(default=None, description="Optional circuit breaker configuration that overrides global settings")
    """Optional circuit breaker configuration that overrides global settings"""
    gpu_config: Optional[GPUConfig] = Field(default=None, description="Optional GPU configuration that overrides global settings")
    """Optional GPU configuration that overrides global settings"""

    class Config:
        extra = "ignore"