# Code generated by schema2code at 2025-10-13 21:56:14. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ErrorDetails(BaseModel):
    """Error information if node execution failed"""
    error_type: Optional[str] = Field(default=None, description="Type/class of the error")
    """Type/class of the error"""
    error_message: Optional[str] = Field(default=None, description="Human-readable error message")
    """Human-readable error message"""
    stack_trace: Optional[str] = Field(default=None, description="Stack trace for debugging")
    """Stack trace for debugging"""

    class Config:
        extra = "ignore"

class NodeMetadata(BaseModel):
    """Metadata structure for workflow node execution tracking"""
    node_name: str = Field(..., description="Human-readable name of the node")
    """Human-readable name of the node"""
    node_id: str = Field(..., description="Unique identifier for this specific node instance")
    """Unique identifier for this specific node instance"""
    node_type: str = Field(..., description="Class name of the node for type identification")
    """Class name of the node for type identification"""
    execution_time: datetime = Field(..., description="ISO timestamp when node execution started")
    """ISO timestamp when node execution started"""
    user_id: Optional[str] = Field(default=None, description="User identifier associated with this execution")
    """User identifier associated with this execution"""
    conversation_id: Optional[int] = Field(default=None, description="Conversation identifier for this execution context", ge=0)
    """Conversation identifier for this execution context"""
    model_name: Optional[str] = Field(default=None, description="Name of the model being used (for pipeline nodes)")
    """Name of the model being used (for pipeline nodes)"""
    profile_type: Optional[str] = Field(default=None, description="Model profile type for pipeline execution")
    """Model profile type for pipeline execution"""
    priority: Optional[str] = Field(default=None, description="Pipeline execution priority level")
    """Pipeline execution priority level"""
    streaming: Optional[bool] = Field(default=None, description="Whether this execution uses streaming responses")
    """Whether this execution uses streaming responses"""
    is_cached: Optional[bool] = Field(default=None, description="Whether this execution uses a cached pipeline")
    """Whether this execution uses a cached pipeline"""
    cache_key: Optional[str] = Field(default=None, description="Cache key used for pipeline caching")
    """Cache key used for pipeline caching"""
    tool_count: Optional[int] = Field(default=None, description="Number of tools available or executed", ge=0)
    """Number of tools available or executed"""
    intent_classification: Optional[str] = Field(default=None, description="Classified intent for routing decisions")
    """Classified intent for routing decisions"""
    memory_operations: Optional[List[str]] = Field(default=None, description="Memory operations performed by this node")
    """Memory operations performed by this node"""
    error_details: Optional[ErrorDetails] = Field(default=None, description="Error information if node execution failed")
    """Error information if node execution failed"""

    class Config:
        extra = "ignore"