# Code generated by schema2code at 2026-01-21 18:11:22. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class OOMRecoveryAttemptData(BaseModel):
    """Single OOM recovery attempt configuration and result"""
    attempt: int = Field(..., description="Attempt number in the recovery sequence", ge=1)
    """Attempt number in the recovery sequence"""
    strategy: str = Field(..., description="Recovery strategy used in this attempt")
    """Recovery strategy used in this attempt"""
    n_ctx: int = Field(..., description="Context window size used in this attempt", ge=1)
    """Context window size used in this attempt"""
    n_batch: int = Field(..., description="Batch size used in this attempt", ge=1)
    """Batch size used in this attempt"""
    n_ubatch: int = Field(..., description="Micro-batch size used in this attempt", ge=1)
    """Micro-batch size used in this attempt"""
    n_gpu_layers: int = Field(..., description="Number of GPU layers used in this attempt", ge=-1)
    """Number of GPU layers used in this attempt"""
    success: bool = Field(..., description="Whether this attempt was successful")
    """Whether this attempt was successful"""
    error_message: str = Field(..., description="Error message if the attempt failed")
    """Error message if the attempt failed"""

    class Config:
        extra = "ignore"