# Code generated by schema2code at 2025-12-01 11:47:39. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .crash_prevention import CrashPrevention
from .parameter_tuning_strategy import ParameterTuningStrategy
from .performance_parameter import PerformanceParameter
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ParameterOptimizationConfig(BaseModel):
    """Configuration for optimizing LLM initialization parameters to find maximum values"""
    enabled: Annotated[bool, Field(default=False, description="Enable parameter optimization to find maximum viable values")]
    """Enable parameter optimization to find maximum viable values"""
    parameters: Annotated[List[PerformanceParameter], Field(..., description="List of performance parameters to optimize")]
    """List of performance parameters to optimize"""
    crash_prevention: Annotated[CrashPrevention, Field(..., description="Settings to prevent container crashes during optimization")]
    """Settings to prevent container crashes during optimization"""

    class Config:
        extra = "ignore"