# Code generated by schema2code at 2026-01-21 18:11:23. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .parameter_tuning_strategy import ParameterTuningStrategy
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class PerformanceParameter(BaseModel):
    """Performance parameters for model initialization"""
    parameter_name: str = Field(..., description="Name of the performance parameter")
    """Name of the performance parameter"""
    priority: int = Field(..., description="Priority of the parameter for optimization (lower number = higher priority)", ge=1)
    """Priority of the parameter for optimization (lower number = higher priority)"""
    tuning_strategy: ParameterTuningStrategy = Field(..., description="Strategy for tuning this parameter")
    """Strategy for tuning this parameter"""
    max_search_attempts: int = Field(..., description="Maximum number of search attempts for this parameter", ge=1, le=20)
    """Maximum number of search attempts for this parameter"""
    floor: int = Field(..., description="Minimum value for the parameter during optimization", ge=1)
    """Minimum value for the parameter during optimization"""
    operator: str = Field(..., description="Operator to adjust the parameter value during optimization")
    """Operator to adjust the parameter value during optimization"""
    modifier: int = Field(..., description="Modifier value to apply with the operator during optimization")
    """Modifier value to apply with the operator during optimization"""
    max_value: int = Field(..., description="Maximum value for the parameter during optimization", ge=1)
    """Maximum value for the parameter during optimization"""

    class Config:
        extra = "ignore"