# Code generated by schema2code at 2026-01-24 15:23:42. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class PipelinePriority(Enum):
    """Pipeline priority levels for cache eviction and resource management"""
    LOW = 1
    MEDIUM = 5
    NORMAL = 10
    HIGH = 11
    CRITICAL = 20