# Code generated by schema2code at 2025-09-11 12:52:24. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class PipelineError(BaseModel):
    """Error information from pipeline execution"""
    error_id: str = Field(..., description="Unique error identifier")
    """Unique error identifier"""
    error_type: str = Field(..., description="Category of error")
    """Category of error"""
    error_code: Optional[str] = Field(default=None, description="Specific error code")
    """Specific error code"""
    message: str = Field(..., description="Human-readable error message")
    """Human-readable error message"""
    details: Optional[str] = Field(default=None, description="Detailed error information")
    """Detailed error information"""
    stack_trace: Optional[str] = Field(default=None, description="Stack trace if applicable")
    """Stack trace if applicable"""
    context: Optional[Dict[str, Any]] = Field(default=None, description="Additional context about the error")
    """Additional context about the error"""
    timestamp: datetime = Field(..., description="When error occurred")
    """When error occurred"""
    recoverable: Optional[bool] = Field(default=None, description="Whether the error is recoverable")
    """Whether the error is recoverable"""

    class Config:
        extra = "ignore"