# Code generated by schema2code at 2025-08-05 21:51:09. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""User preferences"""
class PreferencesConfig(BaseModel):
    # Default profile ID
    default_profile_id: Optional[str] = Field(default=None, description="Default profile ID")
    # Theme
    theme: Optional[str] = Field(default=None, description="Theme")
    # Font size
    font_size: Optional[int] = Field(default=None, description="Font size")
    # Notifications enabled
    notifications_on: Optional[bool] = Field(default=None, description="Notifications enabled")
    # Language
    language: Optional[str] = Field(default=None, description="Language")

    class Config:
        extra = "ignore"