# Code generated by schema2code at 2025-07-01 15:06:59. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr



class RabbitmqConfig(BaseModel):
    # Whether RabbitMQ is enabled
    enabled: bool
    # RabbitMQ host
    host: str
    # RabbitMQ port
    port: int
    # RabbitMQ user
    user: str
    # RabbitMQ password
    password: str
    # RabbitMQ virtual host
    vhost: str

    class Config:
        extra = "ignore"