# Code generated by schema2code at 2025-10-26 22:52:34. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from typing import Annotated
from .optimal_parameters import OptimalParameters
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class RecoveryStrategy(BaseModel):
    """Recovery strategy result with optimal parameters and strategy name"""
    parameters: Annotated[OptimalParameters, Field(..., description="Optimal parameters for the strategy")]
    """Optimal parameters for the strategy"""
    strategy_name: Annotated[str, Field(..., description="Name of the recovery strategy applied")]
    """Name of the recovery strategy applied"""

    class Config:
        extra = "ignore"