# Code generated by schema2code at 2025-08-05 21:51:09. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr



"""Response refinement settings"""
class RefinementConfig(BaseModel):
    # Enable response filtering
    enable_response_filtering: bool = Field(..., description="Enable response filtering")
    # Enable response critique
    enable_response_critique: bool = Field(..., description="Enable response critique")

    class Config:
        extra = "ignore"