# Code generated by schema2code at 2026-03-06 23:17:20. DO NOT EDIT.


from __future__ import annotations
from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .generation_state import GenerationState
from .resource_usage import ResourceUsage
from .tool_call import ToolCall
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class ResponseSection(BaseModel):
    """A section of a generated response"""
    id: Annotated[str, Field(..., description="Unique identifier for this section")]
    """Unique identifier for this section"""
    order: Annotated[int, Field(..., description="Order in which this section appeared")]
    """Order in which this section appeared"""
    startedAt: Annotated[int, Field(..., description="Timestamp when section started")]
    """Timestamp when section started"""
    completedAt: Annotated[Optional[int], Field(default=None, description="Timestamp when section completed (state changed)")] = None
    """Timestamp when section completed (state changed)"""
    type: Annotated[GenerationState, Field(..., description="Type of section based on generation state")]
    """Type of section based on generation state"""
    content: Annotated[Optional[str], Field(default=None, description="Accumulated content for this section")] = None
    """Accumulated content for this section"""
    toolCalls: Annotated[Optional[List[ToolCall]], Field(default=None, description="Tool calls for executing sections")] = None
    """Tool calls for executing sections"""

    model_config = ConfigDict(extra="ignore")