# Code generated by schema2code at 2025-10-26 22:52:38. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from typing import Annotated
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ServerConfig(BaseModel):
    """Server configuration"""
    host: Annotated[str, Field(..., description="Server host")]
    """Server host"""
    port: Annotated[int, Field(..., description="Server port")]
    """Server port"""
    base_url: Annotated[str, Field(..., description="Base URL")]
    """Base URL"""

    class Config:
        extra = "ignore"