# Code generated by schema2code at 2025-09-19 14:17:46. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class SocketConnectionType(str, Enum):
    """SocketConnectionType represents the type of connection used in a WebSocket communication"""
    IMAGE = 'image'
    CHAT = 'chat'
    STATUS = 'status'