# Code generated by schema2code at 2025-10-26 22:52:40. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from typing import Annotated
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class SummaryType(str, Enum):
    """Types of summaries supported by the SummarizationAgent"""
    PRIMARY = 'primary'
    MASTER = 'master'
    BRIEF = 'brief'
    KEY_POINTS = 'key_points'