# Code generated by schema2code at 2025-11-14 17:48:47. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class SummaryStyle(str, Enum):
    """Styles of summaries supported by the SummarizationAgent"""
    CONCISE = 'concise'
    DETAILED = 'detailed'
    BULLET_POINTS = 'bullet_points'
    STRUCTURED = 'structured'