# Code generated by schema2code at 2025-10-30 18:04:03. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from .dev_stats import DevStats
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class SystemGPUStats(BaseModel):
    """System-wide GPU statistics for dynamic multi-GPU systems"""
    total_gpus: Annotated[int, Field(..., description="Total number of GPU devices in the system", ge=0)]
    """Total number of GPU devices in the system"""
    total_memory: Annotated[float, Field(..., description="Total GPU memory across all devices in MB", ge=0)]
    """Total GPU memory across all devices in MB"""
    total_available_memory: Annotated[float, Field(..., description="Total available GPU memory across all devices in MB", ge=0)]
    """Total available GPU memory across all devices in MB"""
    gpus: Annotated[List[DevStats], Field(..., description="List of individual GPU device information")]
    """List of individual GPU device information"""

    class Config:
        extra = "ignore"