# Code generated by schema2code at 2026-01-21 18:11:23. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .dev_stats import DevStats
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class SystemGPUStats(BaseModel):
    """System-wide GPU statistics for dynamic multi-GPU systems"""
    total_gpus: int = Field(..., description="Total number of GPU devices in the system", ge=0)
    """Total number of GPU devices in the system"""
    total_memory: float = Field(..., description="Total GPU memory across all devices in MB", ge=0)
    """Total GPU memory across all devices in MB"""
    total_available_memory: float = Field(..., description="Total available GPU memory across all devices in MB", ge=0)
    """Total available GPU memory across all devices in MB"""
    gpus: List[DevStats] = Field(..., description="List of individual GPU device information")
    """List of individual GPU device information"""

    class Config:
        extra = "ignore"