# Code generated by schema2code at 2025-10-23 11:39:17. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class Thought(BaseModel):
    """Represents a thought or reasoning process from an AI assistant"""
    id: Optional[int] = Field(default=None, description="Unique identifier for the thought")
    """Unique identifier for the thought"""
    message_id: Optional[int] = Field(default=None, description="Foreign key reference to the associated message")
    """Foreign key reference to the associated message"""
    text: str = Field(..., description="The thinking/reasoning content")
    """The thinking/reasoning content"""
    created_at: Optional[datetime] = Field(default=None, description="Timestamp when the thought was created")
    """Timestamp when the thought was created"""

    class Config:
        extra = "ignore"