# Code generated by schema2code at 2025-10-23 12:59:48. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class TodoItem(BaseModel):
    """Represents a user todo list item with priority and status tracking"""
    id: Optional[int] = Field(default=None, description="Unique identifier for the todo item")
    """Unique identifier for the todo item"""
    user_id: Optional[str] = Field(default=None, description="Identifier of the user who owns this todo item")
    """Identifier of the user who owns this todo item"""
    title: str = Field(..., description="Brief title or summary of the todo item")
    """Brief title or summary of the todo item"""
    description: Optional[str] = Field(default=None, description="Detailed description of the todo task")
    """Detailed description of the todo task"""
    status: str = Field(..., description="Current status of the todo item")
    """Current status of the todo item"""
    priority: str = Field(..., description="Priority level of the todo item")
    """Priority level of the todo item"""
    due_date: Optional[datetime] = Field(default=None, description="Optional due date for the todo item")
    """Optional due date for the todo item"""
    created_at: Optional[datetime] = Field(default=None, description="Timestamp when the todo item was created")
    """Timestamp when the todo item was created"""
    updated_at: Optional[datetime] = Field(default=None, description="Timestamp when the todo item was last updated")
    """Timestamp when the todo item was last updated"""

    class Config:
        extra = "ignore"