# Code generated by schema2code at 2025-10-01 20:47:08. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .available_tool import AvailableTool
from .dynamic_tool import DynamicTool
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ToolNeeds(BaseModel):
    """Schema for tool needs analysis"""
    available_tools: List[AvailableTool] = Field(...)
    needs_dynamic_tool: bool = Field(...)
    dynamic_tool: Optional[DynamicTool] = Field(default=None)

    class Config:
        extra = "ignore"