# Code generated by schema2code at 2025-10-26 22:52:41. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from typing import Annotated
from .dynamic_tool import DynamicTool
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class ToolNeeds(BaseModel):
    """Schema for tool needs analysis"""
    available_tools: Annotated[List[str], Field(..., description="List of available tool names")]
    """List of available tool names"""
    needs_dynamic_tool: Annotated[bool, Field(...)]
    dynamic_tool: Annotated[Optional[DynamicTool], Field(default=None)]

    class Config:
        extra = "ignore"