# Code generated by schema2code at 2026-01-21 18:11:23. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from .circuit_breaker_config import CircuitBreakerConfig
from .crash_prevention import CrashPrevention
from .event_stream_config import EventStreamConfig
from .gpu_config import GPUConfig
from .image_generation_config import ImageGenerationConfig
from .memory_config import MemoryConfig
from .model_profile_config import ModelProfileConfig
from .parameter_optimization_config import ParameterOptimizationConfig
from .parameter_tuning_strategy import ParameterTuningStrategy
from .performance_parameter import PerformanceParameter
from .summarization_config import SummarizationConfig
from .tool_config import ToolConfig
from .workflow_config import WorkflowConfig
from pydantic import BaseModel, Field, AnyUrl, EmailStr, conint, confloat



class GPUConfig(BaseModel):
    """Configuration for GPU memory management and device allocation"""
    no_kv_offload: Optional[bool] = Field(default=False, description="Force KV cache to CPU instead of GPU (saves VRAM)")
    """Force KV cache to CPU instead of GPU (saves VRAM)"""
    gpu_layers: Optional[int] = Field(default=None, description="Explicit number of model layers to place on GPU (-1 means all layers). If unset, heuristic allocation/backoff is used.")
    """Explicit number of model layers to place on GPU (-1 means all layers). If unset, heuristic allocation/backoff is used."""
    main_gpu: Optional[int] = Field(default=-1, description="Main GPU device index (-1 for auto-selection)", ge=-1)
    """Main GPU device index (-1 for auto-selection)"""
    main_gpu_device_id: Optional[str] = Field(default=None, description="Device ID/name for main GPU (overrides main_gpu index)")
    """Device ID/name for main GPU (overrides main_gpu index)"""
    tensor_split: Optional[List[float]] = Field(default=None, description="Fraction of model to put on each GPU (must sum to 1.0)")
    """Fraction of model to put on each GPU (must sum to 1.0)"""
    tensor_split_devices: Optional[List[str]] = Field(default=None, description="Device IDs/names corresponding to tensor_split fractions")
    """Device IDs/names corresponding to tensor_split fractions"""
    split_mode: Optional[str] = Field(default="layer", description="How to split model across devices")
    """How to split model across devices"""
    offload_kqv: Optional[bool] = Field(default=True, description="Offload key/query/value tensors to GPU (opposite of no_kv_offload)")
    """Offload key/query/value tensors to GPU (opposite of no_kv_offload)"""

    class Config:
        extra = "ignore"

class UserConfig(BaseModel):
    """User-specific configuration"""
    user_id: str = Field(..., description="User ID")
    """User ID"""
    summarization: SummarizationConfig = Field(...)
    memory: MemoryConfig = Field(...)
    model_profiles: ModelProfileConfig = Field(...)
    image_generation: ImageGenerationConfig = Field(...)
    circuit_breaker: CircuitBreakerConfig = Field(...)
    gpu_config: GPUConfig = Field(...)
    parameter_optimization: ParameterOptimizationConfig = Field(...)
    workflow: WorkflowConfig = Field(...)
    tool: ToolConfig = Field(...)
    event_stream: Optional[EventStreamConfig] = Field(default=None)

    class Config:
        extra = "ignore"