# Code generated by schema2code at 2025-10-27 15:41:16. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class WorkflowType(str, Enum):
    """Supported workflow types for composer orchestration.
"""
    GENERAL = 'general'
    RESEARCH = 'research'
    ENGINEERING = 'engineering'
    CREATIVE = 'creative'
    IMAGE_GENERATION = 'image_generation'
    IMAGE_REFINEMENT = 'image_refinement'
    ANALYSIS = 'analysis'
    PLANNING = 'planning'
    FOCUSED = 'focused'