# Code generated by schema2code at 2025-10-01 20:47:08. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union
from datetime import datetime, date, time, timedelta
from enum import Enum
from pydantic import BaseModel, Field, AnyUrl, EmailStr, constr



class WorkflowType(str, Enum):
    """Supported workflow types for composer orchestration.

- CHAT: Standard conversational workflow with RAG and tool support
- RESEARCH: Research workflow with configurable RAG depth and synthesis
- MULTI_AGENT: Multi-agent orchestration workflow with handoffs
- CREATIVE: Creative content generation workflow with refinement"""
    CHAT = 'CHAT'
    RESEARCH = 'RESEARCH'
    MULTI_AGENT = 'MULTI_AGENT'
    CREATIVE = 'CREATIVE'