#!/usr/bin/env python3
"""
Debug System Prompt Test - Check if our engineering system prompt changes took effect
"""

import asyncio
import os
import sys

sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

from utils.logging import llmmllogger
from db import storage
from models import Message, MessageRole, MessageContent, MessageContentType, IntentAnalysis
from composer.graph.state import WorkflowState
from composer.nodes.agents.engineering import EngineeringAgentNode
from composer.agents.engineering_agent import EngineeringAgent
from models.default_model_profiles import DEFAULT_ENGINEERING_PROFILE

logger = llmmllogger.bind(component="debug_system_prompt")


async def test_system_prompt():
    """Test what system prompt is actually being used by engineering agent."""
    
    logger.info("🔧 Testing Engineering Agent System Prompt")
    
    # Initialize database if needed
    if not storage.initialized:
        logger.info("📊 Initializing database connection...")
        from server.config import DB_CONNECTION_STRING
        if DB_CONNECTION_STRING:
            await storage.initialize(DB_CONNECTION_STRING)
            logger.info("✅ Database initialized")
        else:
            logger.error("No DB connection string available")
            return
    
    # Check what system prompt is in the profile
    logger.info(f"🔍 DEFAULT_ENGINEERING_PROFILE system_prompt: {DEFAULT_ENGINEERING_PROFILE.system_prompt}")
    
    # Create engineering agent and check profile
    engineering_agent = EngineeringAgent(
        profile=DEFAULT_ENGINEERING_PROFILE,
        node_metadata=None,
        pipeline_factory=None,
    )
    
    logger.info(f"🔍 EngineeringAgent profile system_prompt: {engineering_agent.profile.system_prompt}")
    
    # Create test messages
    user_query = "How can I implement JWT authentication in FastAPI?"
    test_messages = [
        Message(
            role=MessageRole.USER,
            content=[MessageContent(
                type=MessageContentType.TEXT,
                text=user_query,
                url=None
            )]
        ),
    ]
    
    # Create test state with intent classification
    test_state = WorkflowState(
        messages=test_messages,
        user_id="test_user",
        conversation_id=123,
        intent_classification=[
            IntentAnalysis(
                workflow_type="WorkflowType.ENGINEERING",
                technical_domain=None,
                response_format=None,
            )
        ],
    )
    
    logger.info(f"📝 Test query: {user_query}")
    logger.info("🤖 Creating engineering node...")
    
    # Create engineering node
    engineering_node = EngineeringAgentNode()
    
    logger.info("🤖 Calling engineering node...")
    result = await engineering_node(test_state)
    
    logger.info(f"🔍 Engineering node result type: {type(result)}")
    logger.info(f"🔍 Original messages: {len(test_state.messages)}, Result messages: {len(result.messages)}")
    
    # Check if new messages were added
    if len(result.messages) > len(test_state.messages):
        new_message = result.messages[-1]
        logger.info(f"✅ New message generated: type={new_message.type}, length={len(new_message.content)}")
        logger.info("================================================================================")
        logger.info("FULL ENGINEERING RESPONSE:")
        logger.info("================================================================================") 
        logger.info(new_message.content)
        logger.info("================================================================================")
        
        # Check if response looks technical
        response_lower = new_message.content.lower()
        technical_indicators = ['jwt', 'fastapi', 'authentication', 'token', 'endpoint', 'code', 'import', 'def', 'class']
        found_indicators = [term for term in technical_indicators if term in response_lower]
        
        if found_indicators:
            logger.info(f"✅ Response contains technical content: {found_indicators}")
        else:
            logger.info("❌ Response does not appear to contain technical content")
            
        # Check for generic indicators
        generic_indicators = ["i'm ready to help", "what would you like", "please share", "how can i help"]
        found_generic = [term for term in generic_indicators if term in response_lower]
        
        if found_generic:
            logger.info(f"⚠️  Response contains generic language: {found_generic}")
        else:
            logger.info("✅ Response does not contain obvious generic language")
            
    else:
        logger.error("❌ No new messages generated by engineering node")
        logger.info("🔍 Debugging message contents:")
        for i, msg in enumerate(result.messages):
            logger.info(f"  Message {i}: type={msg.type}, content_length={len(msg.content)}")
            logger.info(f"  Content preview: {msg.content[:100]}...")


if __name__ == "__main__":
    asyncio.run(test_system_prompt())